# The Protests Of Yesterday

The lives of philosophers are dull. Descartes might figure as the hero of a romance, but Descartes is an exception. Fichte belongs to the rule. The story of his manhood is one of poverty which is not poignant, and of successes which were not great. 

In a work on this thinker, Professor Adamson notes one fact which is palpitant in truth and lucidity; it is to the effect that Europe today does not hold ten students of that marvellous sophist. And yet Fichte is one of the most insolent of dissenters. To the ordinary reader his negations are inexplicable; they comprise the denial of the reality of the external world. This denial, which is known as akosmism, is pantheism's twin sister. Pantheism admits no other reality than Nature; and akosmism, taking one step further, declines to admit any reality at all. Of the two, pantheism has been the more fruitful. It began with the Vedas; ran through Eleatic and Neo-platonic philosophy; was caught up by Scott Erigena and handed to Bruno, who passed it to Spinoza. Another thread or two runs through the Talmud, the Kabbala, the theories of Maimonides, Gerson and Chesdai Creskas; and there are tangles of it in the beliefs of mediaeval communities, in the heresies of the Beghards and Beguines, the Turlupins and Adamites; but with their unravelment the reader need not be wearied. Akosmism has found fewer adherents. Like pantheism, it began with the Vedas, or, more correctly, with the Vedanta philosophy; left broad traces in Greece; revived for a moment during the Renaissance; and then sank back into obscurity until Fichte, Kant aiding, brought it to light anew. Between the two systems there is this cardinal distinction. Pantheism and science have never been other than the best of friends. There is nothing in the one that has ever been seriously opposed by the other. But akosmism and science look at each other askant. They have as much in common as have the poet and the mathematician. 

The clearest idea of Fichte's akosmism, or rather the clearest idea of its charm and futility, is conveyed in a work entitled the *Bestimmung des Menschen* the Vocation of Man. The work is divided into three parts: Doubt, Knowledge and Faith. The first part, Doubt, opens with an inquiry concerning that mystery within us that calls itself "I," and an examination of Nature that vaunts itself real. From this inquiry and from this examination, Fichte discovers that man is but a link in a chain of necessity, a part of that force which, amid the everlasting revo- lution and mutation of things, is the sum and substance of all that is. 

And that chain of necessity! Was there ever anything more delicately interconnected? One has but to look at it to see that its rivets are so tight that they make it impossible for anything to be other than it is. Take, for instance, a single grain of sand on the seashore, and fancy that it lies a few feet further inland than it actually does. The mental operation is, admittedly, most easy to perform; but note the consequences. For that grain of sand to be a few feet further inland, then must the wind which bore it have been stronger than it was; then must the state of the atmosphere which occasioned the wind have been different from what it was, and the previous changes different; in fact, it is necessary to presuppose an entirely different temperature from that which actually existed. We must also suppose a different constitution of the bodies which influenced the temperature, the barrenness or fertility of countries, on which depend the health of man and the duration of life. Interfere, therefore, with that grain of sand, and it is within the range of possibilities that in such a state of weather as was necessary to move it but a few feet further inland, some one, long ago, may have died of cold or hunger - long ago, before the birth of that son from whom the sophist himself descended; and behold, Fichte would have been spared the trials of life, and prevented, too, from solving every problem, and leaving the student nothing to do but to bore himself to death.

From Fichte's logic, therefore, the necessity which compels everything to be precisely as it is, is amply demonstrated. Nevertheless, doubt is not yet banished. It is true he has proved the existence of man to be but a manifestation of a force whose operation is determined by the whole of the universe, but into the nature of that force he is unable to look. And even could he, of what use would it be? It would not help him to regulate his actions. Nature is the last one to contradict herself, and she allows no one to contradict her. The force that acts on us and in us makes us what we are and to attempt to; make ourselves otherwise than it has been appointed we should be, is a task which may be pleasant, but which assuredly is useless. In the chain of necessity we are all interlinked: fight free who may. They who have done so have reached that bourne from which no traveller returns. 

We may rejoice and repent, we may form good resolutions; but the joy and the repentance and the good resolutions come to us of themselves, and not until it is appointed that they shall do so. When they do come, however sincere the repentance may be, however magnificent the resolutions, the course of things moves on unchanged and changeless as before. We lie in the lap of necessity. Should Nature destine one man to be wise and to be brave, wise and brave he will be. Should she destine another to be scatterbrained and imbecile, scatterbrained and imbecile will he become. There is no merit, no blame, to be ascribed to her or to them. The wishes that throb in our hearts may rebel, but the great Mother snuffs them out like a candle. She is governed herself. Her laws are ours. 

It is in musings of this description that Fichte stretches his hand to Spinoza and denies that man is a free agent. At best he is a conscious automaton. But what if he were not even that?  Is there any one thing of which he is certain? 

> Dreams are true while they last, and do we not live in dreams?

Fichte asks himself the same question, and looking with introspective eye for an answer, discovers the purely subjective character of all human knowledge. He sees that he has no consciousness of things in themselves, only a consciousness of a consciousness of them. Were he blind, what would he know of colour? Were he deaf, what would he know of song? Were he without imagination, doubt, hope and fear would have no meaning. Such knowledge as man possesses is merely a knowledge of himself; beyond it, consciousness never goes. When it seems to do otherwise, when man assumes to be conscious of an object - the sun, for instance - he has merely the consciousness of a supposition of an object, which supposition he identifies with sensation and takes for the object itself. 

It has been hinted that akosmism and science are at odds, but on this point they agree. As a matter of fact, and one admitted by all decorous scholars, we none of us see the sun. What we do see are certain modifications of light in immediate relation to our organ of vision. And in this connection it is not improper to note that no two persons see the same modifications of the same light, and that for the reason that each person sees a different complement of rays acting on his own individual retina. 

But to return to Fichte, and to put his idea less technically, it is a self-evident proposition that we neither see our sight, feel our touch, nor yet have a higher sense by which things affecting the organs of sense are perceived. It is therefore not difficult to accept the axiom that our consciousness of external existence is merely the product of our presentative faculty. The difficulty lies in the application, for with it all reality vanishes. "In that which we call intuitive knowledge, we contemplate only ourselves, and our consciousness is and can be only a consciousness of the modifications of our own existence. If, therefore, the external world arises before us only through our own consciousness, it follows that what is particular and multiform in the external world can arise in no other way; and if the connection between ourselves and what is external to us is simply a connection of thought, then is the connection of the multifarious objects of the external world simply this and no other."

The whole of the material world is, then, but a cerebral phenomenon. There is no being, no real existence. The only things that exist are pictures, and these pictures know themselves after the fashion of pictures. They are pictures which float past, without there being anything past which they float - pictures which picture nothing, images without significance and without an aim. Reality is a dream, without a world of which the dream might be, or a mind that might dream it. It is a dream which is woven together in a dream of itself. Intuition is the dream; thought, the source of fancied reality, is the dream of that dream.

In this charming manner, Fichte, after divesting himself of doubt and attaining perfect knowledge, mounts into a higher sphere which he terms Faith. Into the austerities of this abstraction it is unnecessary to follow him and it will perhaps suffice to note that the conclusion amounts to the assertion that where the canaille believe that things are as they appear, because they must, the philosopher believes because he will. After a deduction such as that, one may well exclaim against the uselessness of philosophy in general, and the Fichtean branch in particular.

Fichte's metaphysical hysterics excited the wildest hilarity. His formula I = I, on which in an earlier work he had sounded all the changes, was popularly supposed to mean his own indi- vidual ego. Fichte, however, meant nothing of the sort. The "I" he used in the impersonal sense which is conveyed in such expressions as "it rains," "it snows." The "I" represented the force that pervades all things, and which in man arrives at a consciousness of self. But Fichte was not a clear writer - few Germans are; and if he was taken *au pied de la lettre* the fault was his own. In any event, his philosophy was largely ridiculed. Heine is witness to the fact that a cartoon was circulated which represented a goose whose liver had become so big that the bird was undecided whether she was all goose or all liver. Across her Fichtean breast ran the legend I = I. The reality of his idealism, however, was not taken so easily. The Philistines waxed wroth. Heine represents a burgomeister as exclaiming, "That man thinks I don't exist, does he? Why I'm stouter than he and his superior too!" The ladies asked, "Doesn't he at least believe in the existence of his wife?" "Of course not." "And does Madame Fichte permit that?" 

But with whatever facetiousness the matter may be viewed, the question of an external world has been, and is still, one of the great battlefields of metaphysics. The realists clamour that their opponents are colossal in their errors; the idealists answer, "Tu quoque." Among the latter, few have been more vehement than Fichte. He defended his belief with all the heavy artillery of the German dictionary, and entrenched himself with logic. It was, however, merely on speculative principles that he contended that our knowledge of mind and matter is only a consciousness of what Sir William Hamilton has christened "various bundles of baseless appearances." He did not deny the veracity of consciousness; he denied the veracity of its testimony, a distinction as subtle as it is valid. For all practical purposes the material world - including Madame Fichte - was to him not only thoroughly real, but it went spinning through space at the rate of nineteen miles a second. And it was merely the certainty of uncertainty, the haunting conviction of the unreliability of the perceptions which in earlier days led Socrates to maintain that the only thing he knew was that he knew nothing, which caused Fichte to discriminate between what he believed and what he saw. 

But however unreal the world might be in theory, he was quite sure that for everyday purposes it was the worst one possible. Indeed, Fichte was not only an akosmist, he was a pessimist too, a combination which seemed so alluring to Lammenais, that after a debauch in Fichteana he was pleased to describe the world as a shadow of that which is not, an echoless sound from nowhere, the chuckle of Satan in chaos. 

Fichte's successor was Schelling. In place of the abstractions of his precursor, this gentleman presented an adventurous mysticism. Both were idealists; but where the one extracted the real from the ideal, the other reversed the proceeding. The transcendentalism which they professed in common, is the history of consciousness to the highest degree of its development. Fichte tiara'd his system with faith; Schelling crowned his own with aesthetics. To the latter, the universe was a poem whose strophies were writ in metaphysical formulas, a phrase which may be taken to mean that he was exquisitely alive to the beauties of Nature and yet unable to picture them in readable prose. His real master was Spinoza, and his philosophy in consequence presents some of the serenest forms of pantheistic belief. 

The harmony to which he was alive prefigured to him the agency of a supreme Principle; of a Being eternally unconscious; veiled from the sight of man by the purity of enveloping light, and apprehensible only through intellectual intuition. On the skirts of this intuition he suspended knowledge. Above it he poised art - "the revelation of that Absolute in which subject and object coincide; in which the conscious and the unconscious unite." 

"That which we call Nature," he said, "is a poem writ in mysterious hieroglyphics, but in which, were they decipherable, whoso lists might read the Odyssey of the Spirit, preyed upon by illusion, ever seeking, ever fleeing itself. ... Nature is to the artist that which it is to the philosopher; the ideal world ceaselessly appearing in finite forms; the wan reflection of a universe which does not stretch beyond the mind, but rests within it." 

The fundamental idea of the entire system amounts in brief to this: earth, sea and sky, and all that in them is, are, in their essence, emanations, or, as Leibnitz has it, fulgurations of an eternal and unconscious activity. Detached from the primordial matrix, these manifestations, though interconnected, are without permanent reality. The finite world is an illusion. The infinite alone exists. 

This idea, while not unalluring, is passably vague. But vagueness has no terrors for those who wish to be mystified, and that there were many such is evident from contemporary accounts of the enthusiasm with which it was greeted. The enthusiasm, however, was as impermanent as Schelling's own reality. His disciples flocked to a rival teacher, to Hegel, whose name has the sound of a knell. 

The doctrine which this gentleman advanced, and which today is to be sought for in seventeen massive in-octavos, may be regarded as the apotheosis of the arrière-pensée. Hegel was the chameleon of philosophy. He believed in nothing; and not only did he believe in nothing, but he possessed no fixity of disbelief. Whenever it is possible to pin him down, it is always on a contradiction that the pinning is accomplished. He was an anatomist of thought, a midwife of paradox. No phase, no flutter of consciousness, escaped his diagnostic. He analysed and dissected, but he did not build, or at least only on negations. He created doubts, not convictions. He made disbelievers, not converts. It was he who should have said, "Ich bin der Geist der stets verneint."

It may be noted, parenthetically, that the proposition of which Plato caught a glimpse, and which Descartes dimly perceived, the proposition that man is the one centre of thought, formed the sum and substance of Kant's teaching. "Look," he admonished the reader, "look at time and at space. They are but categories of thought. Time is not, nor yet is space. They are appearances which the mind creates, and with which we envelop the universe." This idealism, which in Kant was partial, in Fichte subjective, and in Schelling objective, became absolute with Hegel. To him, illusion was the one permanency, the one cause, and man but the shadow of its effects.

In its widest sense, Hegel's philosophy is an attempt to make the acquaintance of Schelling's primordial entity —the Absolute. As a necessary preparation he annihilated the finite, or, to use his own language, the categories of the finite which stood in his way; and when he had done so, behold, the Absolute had crumbled with them. The heavens were void. There has been nothing, there is nothing, there will be nothing, save a constant evolution, a continuous develop- ment, with death for a goal. And, after all, what is the lesson that history conveys? What, indeed, if it be not this, that whatever is born, is born to die. 

The idolatry, the infatuation of Hegel's disciples was without precedent or parallel. The streets and beer-halls echoed with discussions on the identity of contradictories. The Idea, the Absolute, the Ich and the non-Ich, were every night topics. Metaphysics hung over Berlin like a London fog. Hegel was not only a popular teacher, he was a national idol. His dialectic prestidigitations had all the charm which attaches to the unfathomable. That he was a charlatan is clear, but that he was revered is certain. Among the group of mourners that assembled about his tomb, one, a theologian, likened him to Jesus. More recently, Scherer compared him to Napoleon. Yet on his deathbed Hegel was heard to mutter, " Only one man understood my philosophy, and he only half-caught its import." 

After such a confession, one might well offer him the viaticum and hum a requiem over his seventeen in-octavos. And yet in vain. Hegel's influence is too substantial to be quieted by any requiescat, however determined. In spite of the hilarity of the impolite, his spectre looms through the most rational forms of contemporary negation. In the core of his philosophy there broods a sphinx that still defies. 

When the bewilderment which Hegel excited subsided, the faith which he had inculcated was questioned; belief soon gave way to heresies, and the metaphysical assembly divided itself into dissenting camps. From one of these issued the philosophy which counted Emerson and Carlyle among its exponents. In the uproar of another, Strauss, Feuerbach, Bruno and Stirner have pointed to an eternal grave and taken the nimbus from a god. It is owing to the instruction of a third that Vacherot has occupied his time in showing that the idea of perfection is God, but that perfection does not exist; and it was something of the original spirit that smoothed the way for the amiable fumisteries of Ernest Kenan.

In the days when Hegelism was at its apogee, there appeared in Berlin a young man who declined to take any other part in the general intoxication than that of spectre at the feast. His contempt for the sophist, the pachyderm hydrocephali, and all the pedantic eunuchs who made up what he was wont to term the apocalyptic retinue of the bestia trionfante, was sumptuous in its magnificence. So sumptuous even, that he took counsel from an attorney as to the exact limit his contempt might reach without making him amenable to a suit for defamation. Then, reassured, he began an attack. "Hegel's philosophy," he said, "is sufficient to cause an atrophy of the intellect. It is a crystallised paralogism, an abracadabra, a puff of bombast, and a wish wash of phrases which in its monstrous construction compels the mind to form impossible contradictions." For its preparation he offered a receipt which is homeopathic in its simplicity. "Dilute a minimum of thought in five hundred pages of nauseous phraseology, and for the rest trust to the Teuton patience of the reader." 

A few years before, this violent yet cautious young man had written a work which he signed in full letters, Arthur Schopenhauer, and entitled, *Die Welt als Wille und Vorstellung*. This work, which he thought would shake the sophistry of all civilisation, had been left unnoticed and neglected on the back book-shelves of its Leipzig publisher. It is said that he smarted at this inattention, and that his aggressiveness and contempt of Hegel, and not of Hegel alone, but of Fichte and Schelling, the three sophists, as he was pleased to call them, was the outcome of envy. Whether or not this statement is true, is a matter of small importance. The point to be noted is, that thirty years later Hegel was largely forgotten, and the works of his obscure opponent were welcomed with an enthusiasm which has been expanding ever since.

"The World as Will and Idea" is an atheology compounded of Buddhism, Tauism and Epicurism, a mosaic of Oriental and classic negations worked out by an original and brilliant thinker. If the seventeen in-octavos already alluded to may be regarded as the apotheosis of the arribre-pensee, then, in comparison, this philosophy, together with its complementary monographs, represents the renaissance of common sense. 

Schopenhauer was not a pantheist. Had he possessed any of the views of ordinary orthodoxy^ the belief, for instance, in 

> L'univers Où règne un Jehovah dont Satan est l'envers,

he might possibly have read the banns over Nature and Satan, but he never would have identified the former with God. Nor was Schopenhauer a materialist. He was a theorematist of force, but atoms found no place in his system. Yet if he must be catalogued, it will perhaps be safest to say that he was an idealist who saw the inutility of dream. Kant's *Krittk*, from which all German metaphysics proceeds, had shown him that reason must either be confined within the limits of experience, or else let loose into an absolute idealism. The three sophists had disgusted him with the supersensible, and yet he felt suffocated in the narrow limits of the real. There was yet a middle course, and that course he took. It was useless to ask whence the world comes or whither it tends, but it would not be impertinent to state *what it is*; and the statement which Schopenhauer made to the public was to the effect that the world is but the perception of a perceiver, a simple representation, a mere idea which man carries with him to the tomb, and which in the absence of a thinker to think it would not exist at all. 

In the *Cogita*, a notebook of which extracts have been selected by Schopenhauer's literary executor, [^9] is the following passage: "Two things were before me, two bodies, regularly formed, beautiful to see. One was a vase of jaspar, with a border and handles of gold. The other was an organism, a man. When I had admired them sufficiently from without, I begged the genie who accompanied me to let me visit within. This permission was accorded. In the vase I found nothing save the pressure of weight, and between the parts some obscure reciprocal tendency which I have heard designated as cohesion and affinity. But when I entered the other object, my surprise was so great as to be almost untellable in legends : and fairy-tales there is nothing more unbelievable than the spectacle which I beheld. In this object, or rather in its upper end, called the head, and which from without looks like anything else, I saw nothing less than the world itself; I saw the immensity of space in which all is contained, the immensity of time in which everything moves, and therewith the prodigious variety of objects that fill both space and time ; but, what is most astounding, I saw myself coming and going! That is what I discovered in this object that was barely larger than a large fruit; in this object which the headsman can dissever with a single blow, and that, too, in such wise as to plunge into sudden and eternal night the whole of the world that it contains. And the amusing part of it all is, that if objects of this sort did not sprout like mushrooms, continuously prepared to receive a universe that is ever ready to subside into chaos, and did not give and take like a ball the great idea (Vorstellung) which is identical in each, and of which the identity is expressed with the word objectivity, the world would no longer exist." 

Schopenhauer was not far from agreeing with Berkeley that the world is a phantasmagoria, a transformation-scene existing in fancy, or, as the Brahmans declared, a mirage evoked for the entertainment of the Supreme. The source and origin of the exterior world lay in the representative faculty which creates it and with which it disappears. Matter, according to him, is a lie that is truth; it is not an illusion, it is correlative with the intelligence; the two rise and fall together; separated, they could not exist; one is a reflection of the other. Properly speaking, they are the same thing examined from different points. But what is this same thing? Schopenhauer answers with a word. It is Will. 

This Will should not be taken to mean the conscious act of a higher Intelligence. It is a force, invariable, identical and equal, of which gravitation, electricity, heat - in fact, every form of activity from the fall of an apple to the founding of a monarchy, from a cataclysm to a blade of grass, from the choir of planets to the invisible molecule - is merely a derivative and nothing more. In Nature, it is a blind, unconscious power; in man, it is the foundation of being. 

This theory, which Schopenhauer expounded with a great luxuriance of vivid argument, and in a style that is crystal in its clarity, coincides in the aptest manner with the doctrine of evolution. During the early ages of the world's formation, the objectivity of this force was, he says, limited to inferior forms but when the conflict of chemical forces had ended, atnd the granite, like a tombstone, covered the combatants, it irrupted in the world of plant and forest. The air, decarbonised, was then prepared for animal life, and the Will's objectivity realised a new form. Fish and crustaceans filled the sea, gigantic reptiles covered the earth, and gradually through innumerable forms, each more perfect than the last, the propulsion ascended to man. 

Schopenhauer declined to believe that either here or in another planet a being superior to man could possibly exist; and that for the reason that with enlarged intelligence he would consider life too deplorable to be supported for a moment. As a consequence, the Will's objectivity can ascend no higher. Its latest manifestation is even the final term of its progress, for with it has come the possibiUty of its denial, the possibility that some day it may be throttled into extinction and choked back into the chaos from which it sprang. 

In all the grades of its manifestations. Will, he taught, dispenses with any end or aim. It simply and ceaselessly strives, for striving is its sole nature. But as any hindrance of this striving, through an obstacle placed between it and its temporary aim, is called suffering, and the absence of any obstacle, satisfaction, - it follows, if the obstacles it meets outnumber the facilities it encounters, that, having no final end or aim, there can be no end and no measure of suffering. 

That pain does outbalance pleasure is a fact too well established to need discussion here. Pain begins with the lowest types of animal life, becomes acute with the nervous system of the vertebrates, increases in proportion to the development of the intelligence; and as intelligence attains distinctness, pain advances with it, until what Mr. Swinburne calls the gift of tears finds its supreme expression in man. And man is not a being to be envied. He is the concretion of a thousand necessities. His life, as Schopenhauer has it, is a fight for existence, with the certainty of defeat in the end; and even when his existence is assured, there comes a struggle with a shadowy burden, an effort to kill time, and a vain attempt to escape ennui.

Nor is ennui a minor evil. It is not every one who can get away from himself Schopenhauer could, it is true; but in so doing he noted that its ravages depicted on the human countenance an expression of absolute despair, and made beings who love each other as little as men do, seek eagerly the society of each other. In this way, between effort and attainment, the life of man rolls on. The wish is in its nature pain, and satisfaction soon begets satiety. No matter what fortune may have done, no matter what a man may be or what he may possess, pain can never be avoided. Efforts to banish it effect, if successful, only a change of form. It may appear as want or care for the maintenance of life. If this preoccupation be removed, back it comes again in the mask of love, jealousy, hatred or ambition; and if it gain entrance through none of these avatars, it comes as simple boredom, against which we strive as best we may. Even in this latter case, if we get the upper hand, we shall hardly do so, Schopenhauer says, without letting pain in again in one of its earlier forms. And then the dance begins afresh for life, like a pendulum, swings ever backward and forward between pain and ennui. 

The one relief, a relief which at best is momentary and accidental, is in that impersonal contemplation in which the individual is effaced, and only the pure, knowing subject subsists. This condition Schopenhauer praises as the painless state which Epicurus described as the highest good, the bliss of the gods. Therein man is freed from the yoke of Will; the penal servitude of daily life ceases as for a sabbath; the wheel of Ixion stands still. The cause of this he was at no loss to explain, and he did so, it may be added, in a manner poetically logical and peculiar to himself. 

"Every desire is born of a need, of a privation or of a suffering. When satisfied, it is lulled; but for one that is satisfied, how many are unappeased! Desire, moreover, is of long duration its exigencies are infinite; while pleasure is brief and narrowly measured. Pleasure, too, is but an apparition that is destined to be succeeded by another. The first is a vanished illusion the second an illusion that lingers still. Nothing is capable of appeasing Will, nor of permanently arresting it. The best we can do is like the alms tossed to a beggar, which, in preserving his life today, prolongs his misery tomorrow. While, then, we are dominated by desires and ruled by Will, so long as we give ourselves up to hopes that delude and fears that alarm, we have neither peace nor happiness. But when an accident, an interior harmony lifting us for the moment from out the torrent of desire, delivers the spirit from the oppression of Will, turns our attention from everything that solicits it, and all things seem as freed from the allurements of hope and personal interest, then repose, vainly pursued, yet ever intangible, comes to us of itself, bearing with open hands the plenitude of the gift of peace."

Contemplation is then an affranchisement. It delivers us for a moment from ourselves; it suspends the activity of Will; and in raising man out of misery into the pure world of ideas, brings him a foretaste of that repose which is the freedom of the non-existent. But the liberation from the trammels of Will which is found in art and disinterested contemplation, is a solace that is momentary and accidental. That which is more desirable is a complete and unfettered freedom. The cause of evil is known; it is the affirmation of the Will-to-live. The remedy is its denial. The Will affirms itself when, after an acquaintance with life, it persists as much in willing as in the first moment when it was a mere blind necessity. The Will denies itself when it renounces life, when it frees itself through a persistent abdication, and abolishes itself of its own accord. 

In this there is no question of suicide. For suicide, far from being a denial of the Will-to-live, is one of its strongest affirmations. The man who takes his own life really wants to live.

What he does not want are the miseries and trials attendant on his particular existence. He abolishes the individual, but not the race. The species continues, and pain with it. To be scientifically annihilated, life should be aboHshed not only in its suffering, but in its empty pleasures as well. Its entire inanity should be recognised, and the whole root cut once and for all. In explaining in what manner this is to be accomplished, Schopenhauer carried his reader far off into the shadows of the Orient. On the one side is the lethargy of the Rishis; on the other, the Tauists drugged with opium while above all rises the phantasy of the East, the dogma of metempsychosis. As the present writer has elsewhere explained, [^10] Schopenhauer gives the name of Will to that force which in Indian philosophy is held to resurrect with man across successive lives, and with which the horror of ulterior existences reappears. It is from this nightmare that we are summoned to awake, but in the summons we are told that the awakening can only come with a recognition of the true nature of the dream. The work to be accomplished is therefore less physical than moral. We are not to strangle ourselves in sleep; we are to rise out of it in meditation. 

"In man," Schopenhauer says, "the Will-to-live advances to consciousness, to that point where it can choose between its continuance or abolition. Man is the saviour. Nature awaits her redemption through him. He is at once the priest and the victim." 

If, then, in the succeeding generations the appetite for liberty has been so highly cultivated that a widespread and united compassion is felt for all things, then through continence absolute and universal, that condition will be produced in which subject and object disappear, and - the sigh of the egotist Will once choked thereby into a death-rattle - the world, delivered from pain, will pass into that peace which passeth all understanding, into the Prajna-Paramita, the "beyond all knowledge," the Buddhist goal where nothing is. 

"It is this," Schopenhauer exclaims in his concluding paragraph, "it is this that the Hindus have expressed in the empty terms of Nirvana and re-absorption in Brahm. I am, of course, that what remains after the abolition of the Will, is without eifect on those in whom it still works. But to those in whom it has been crushed, what is this world of ours, with its suns and stellar systems? *Nothing*"

Among thinking people, Schopenhauer's admirers are today sufficiently frequent to defy enumeration. The theory of force, which was his chief originality, has found few serious adherents; fewer still are they who pin any faith to his plan for the extinction of humanity; it is his classic insistance on the immedicable misery of life, it is the pessimism which he expounded, but which was no more his own invention than is atheism, that has multiplied the translations and editions of his works. For thirty years these works were unnoticed. But Schopenhauer, who was very blithe in his misanthropy, snapped his fingers at the inattention of the public he knew that Time, who is at least a gentleman, would bring him his due unasked. "My death," he said, "will be a canonisation, the extreme unction, a baptism." Yet before he died, fame and honours came and found him unsurprised. "Time has brought his roses at last," he said. "But see," he added, touching his silvered hair, "they are white." 

The most prominent of Schopenhauer's successors is Dr. Eduard von Hartmann. On many points this gentleman separates widely from the master. In matters ontological and teleological there is a variance that is noticeably large. But their pessimism is the same; if any difference is discernible, it is merely in this, that the tone of the later comer has gained from recent science the steadiness and assurance that comes of broader knowledge. 

Dr. von Hartmann, who sits at the head of contemporary metaphysicians, is a transcendental realist. His doctrine is a pantheism, or, as he prefers to call it, a monism, in which nihilism and idealism are found in equal parts, and one which has given to Hegelism a new and unexpected activity. Nature to him is truly divine; but the misery of existence is irremediable, or at least will continue to be so until advancing science has taught in what way the clamour of life may be quelled. That which the Hindu termed Atma, that which Spinoza designated as Substance - in short, the universal and indetectable force which has made all things what they are, is called by him the Unconscious. The Unconscious is sovereignly wise, and the world is admirable in every respect; it is existence that is irreclaimable in its misery. 

The originality of this philosophy consists in a theory of optimistic evolution as counterbalanced by a pessimistic analysis of life; but the originality is not lost in its conclusion, in which it is argued that, as the world's progressus tends neither to universal nor individual happiness, the great aim of science should be to emancipate man from a love of life, and in this wise lead the world back to chaos. The interest of the Unconscious is opposed to our own. It is to our advantage not to live; it is to the advantage of the Unconscious that we should do so, and that others should be brought into existence through us. The Unconscious, therefore, in the further- ment of its aims, has surrounded man with such illusions as are capable of deluding him into a belief that life is a pleasant thing well worth the living. The instincts within us are the different forms beneath which the desire to live is at work, and with which the Unconscious moulds man to its profit. Hence the energy witlessly expended for the protection of an existence which is but the right to suifer; hence the erroneous idea which is formed of the happiness derivable from life; and hence, too, the modification of past disenchantments through the influence of fresh and newer hopes. But when in the old age of the world, when humanity has divested itself of the belief that happiness is obtainable in this life, when it has lost all faith in the promise of another - in fact, when every illusion has been dissipated, when hope, love, ambition and gold are recognized as chimeras, or at least as incen- tives to activity which cause more pain than pleasure - then, science aiding, humanity will perform its own execution, and Time at last will cease to be. 

Such is Dr. von Hartmann's conception of life, and such is the idea he has formed of the destiny of the world. In regard to the latter, nothing need now be said; but it may be noted that to the general public his theory of pleasure and pain has not seemed wholly satisfactory. There have been many attempts to confute his pessimism, and many attempts to show that life, so far from being immedicable in its misery, is a well-spring of delight. And to many, doubtless, it has so seemed. But a point of view is not an argument. Whether life is held to be valuable, or whether it is held to be valueless, its nature in either case remains unchanged. To the obtuse it is usually the one; to the sensitive it is generally the other. But to the impersonal observer, the disinterested witness, to him who looks back through the shudders of history, and who gazes into a future that will be as inexplicable as the past, to him who feels some sympathy for the suffering, some compassion for the distressed and some pity for those in pain, life seldom seems other than an immense, an unnecessary affliction. 

Why, asked Voltaire, with that leer which de Musset has made immortal. Why is there anything? An answer often given to this question is, that the ultimate reason of things is discoverable only in matter and motion. In theological circles the advocates of this explanation are not in good repute. In polite society it is considered as bad form to hold such theories as it is to carve salad or guillotine asparagus. In fact, beyond the jurisdiction of the scientific world the materialist has a bad name. The pantheist, *passe encore*. Pantheism is vague and poetic, and apprehended with difficulty. But the materialist brings a different guitar. His conception of the universe demands but little study to seem tolerably clear. Besides, in his heart he seems to say, There is no God, and the appearance of that inward speech is not compatible with good manners. Society has a stronger leaning to affirmations than to negations; in fact, as Rousseau has pointed out, the average intellect prefers to be wrong in its belief than to have none at all. The materialist, standing as he does in opposition to theological tenets, is therefore eyed askant, and, what is more, is called an atheist when his back is turned. 

Parenthetically it may be noted that the historical definition of an atheist is a citizen who refuses to worship the gods which the authorities of the state have appointed as worthy of worship. In modern parlance the word has acquired a sharper tone, and is generally used in reference to whoso disbelieves in the supernatural. In the coming centuries it is possible that it will cease to be a term of reproach. Indeed, its rehabilitation has in certain quarters already begun. But be this as it may, there are still few thinkers who hear themselves called atheists without ex- periencing some bewilderment. "Tell a philosopher," Heine said, "that his theories are atheistic, and he will be as much surprised as would a geometrician on learning that his triangles were red." The denomination is as impertinent to the views of the one, as the colour is to the triangles of the other. Not every one, however, has had the privilege of sitting at Heine's feet, and the expression continues to be flung, with more or less vigour, at all systems of rationalistic thought, though at none more virulently than at materialism. 

As has been hinted in earlier chapters, materialism is as old as philosophy itself. In India, it was a precursor of Buddhism; in China, it antedates Laou-tze: In classic antiquity, Democritus, Epicurus and Lucretius were among its advocates. Arrested by Christianity, it was imprisoned all through the middle ages; but when» over a century ago, it at last escaped, thrones and altars fell before it. It is, however, only within recent years that materialism received the endorsements of science. The standard-bearer of this movement, a movement all the more significant in that it was a reaction against Hegelian abstractions, was Moleschott. His principal work, the *Krieslauf des Lebens*, awoke Germany from her stupor. It was attacked, applauded and abused. The thinking world, which since Hegel's death had been twirling its thumbs, turned toward it expectant eyes. The hypothesis of an indefinite circulation of matter passing ceaselessly from life to death and from death to life, was old enough to seem quite new, and the axiom. Without force, no matter; without matter, no force, was listened to with grave attention.

The *Kreislauf des Lebens* inspired any number of affiliated works. Vogt, Lowenthal, Czolbe and Eudolphe Wagner made themselves prominent in its defence. Old-fashioned methods were abandoned. Psychology was put aside. Since there was no psyche, of what use could it be? Metaphysics was relegated to the night from which it had sprung. Modem materialism determined to support its dogmas with the sciences which are called exact. And Biichner, mailed with astronomy, chemistry, geology, physiology and natural history, produced in *Kraft und Stoff* the textbook of the new belief. There-after it only needed a hymnal to be complete. The deficiency has been supplied by Richepin's *Blasphèmes*.

The first principle of scientific materialism is the inseparability of matter and force. Matter is not a vague substance on which force grapples from without. In the absence of the one, the the other is inconceivable, save perhaps by way of hypothesis. Without force, matter would enter at once into a formless void. Without matter, force would fade into a region of pure abstractions. Endeavour, for instance, to represent matter without force, that is, without the power of cohesion or affinity, attraction or repulsion, and, presto ! the very idea of matter disappears. In like measure, an effort to represent force without matter results in a similar denouement. 

The second principle is that force and matter are indestructible. There are transformations there are varieties in their manifestations, but in the sum of their effects the intensity is undiminished. Burn a log of wood, and the scales of a chemist will show that not a particle of matter has been destroyed. "Annihilate a particle of matter," said Spinoza, "and the world will crumble." Not an atom can lose itself in immensity, and to immensity not an atom can be added. The flux and reflux of things show beneath incessant variations the same persistent and invariable aggregate. There is a circulation of materials of which each fortuitous combination has its beginning and its end, but in some one form or another the materials meet again and interconnect anew. 

As with matter, so with force. What disappears on one side re-appears on another. Friction produces fire, motion is obtained by steam. The amount of movement expended is recovered in the amount of heat; the amount of heat dissipated is recovered in the amount of motion. Force, then, like matter, is immortals It may be transformed, but never destroyed. From these considerations, materialism concludes, that, as that which is indestructible can have had no beginning, matter and force cannot have been created. Ex nihilo nihil, in nihilum nil posse reverti. The transformation of something into- nothing is as inconceivable, says Lebon, as is the creation of something from nothing. And Taine adds, "There is nothing but matter and motion. Space is the infinity of matter, as time is the eternity of motion." Matter and force are, then, eternal. But eternity is shared alone by them. Dust we are, to dust we shall return. 

Matter and force being eternal, their laws are immutable. Were it otherwise, the properties of matter would change, and on the tablets of experience no change is recorded. Nature has never varied. Her laws are the mechanical relation of forces which, in disclosing no trace of a higher Will, turn superstition into a vagabond that has not where to lay its head. Time, in which all things unroll, is the great, the one creator. 

The novelty of modern materialism, a novelty which distinguishes it from other systems, is that it claims to rest its affirmations on a basis which is strictly scientific. Its explanation of the universe by means of the action of natural forces, its reduction of natural forces to the variable modes of the force inherent in nature, are indeed supported by physics, chemistry and physiology. But into certain regions that it attempts to pene- trate, it has not been preceded by any avant- courier that at all resembles exact knowledge. 

The hypothesis that the attraction of all ponderable matter which maintains the planets in their orbits, must at one time have been in a condition to mould the universe from the cosmic dust spread through space, is the starting point of materialistic cosmogony. This hypothesis, hazarded by Kant, signed by Laplace and attested by Herschel, is crowned by another, which is as opulent in vistas as is the retrospect of the first. It is to the effect that the earth, like her lost satellite whose fragments have deluged the globe, will in turn be disembowelled and tossed through space. Historically these hypotheses are not new. Entertaining as the conjunction may appear, they are part of Buddhist lore. But they are a part of Buddhism which is as vague as it is poetic. In materialism, if there is less vagueness, there is also less poetry. Materialism is nothing if not matter-of-fact. Starting, then, from the hypothesis that a mass of cosmic matter originally filled the space which our planetary system occupies, and that, in accordance with the laws of gravitation which draw the parts to the centre, the sun was formed by the gradual concentration of its elements, it is not difficult to fancy a fragment of nebulosity detached from the centre and shot through space, developing first in a collection of gases, then into molecules that the rotatory movement fused and ignited, and which in cooling formed a crust above an interior furnace. This flight of fancy accomplished, it is yet easier to imagine the condensation of vapours into rain, the growth of plants and the birth of the monera from which man descends. 

And life? Is it then, as Marcus Aurelius in his sceptred melancholy suggested, but a halt between two eternities? Bah! Away with phrases A bottle containing carbonate of ammonia, chloride of potassium, phosphate of soda, chalk, magnesia, sulphuric acid and silex, is life in its most ideal, in its completest expression. 

Some sixty million years ago, when primitive man blinked at a brighter sky than ours, he thought of the archeolithic ape, if he thought at all, as an inferior animal. And, indeed, there could have been little in common between the shuddering orang-outang and the speechless yet ferocious troglodyte who with an uprooted tree crushed the skull of a lion and then sucked the fuming brain.

The link between the two was as undiscernible to him as to the theologian of today. And yet, as Huxley has pointed out, the anatomical difference between man and a gorilla is less than between a gorilla and an inferior ape. And, to pursue the same line of argument, the difference between a Shakespeare and a savage is infinitely greater than between a savage and a brute. Why, a magpie is cleverer than the aboriginal Australian; but at the same time the cleverness of a magpie is not a proof of the evolution of man. 

The old coquette, this world of ours, conceals her age, but her biography is under our feet. As we read backwards through it, her years mount up into ten hundred millions. The date of that initial catastrophe, her birth, is yet unreached but we know enough of her past to be sure that it has been long enough and sufficiently immoral for many things to happen of which our philosophy may dream though it cannot prove. Among these things are spontaneous generation and the descent of man. When these are substantiated? materialism will have proved its claim; its sway will be undisputed; but until then, its arguments have as much evidential value as so many astro gals. 

In attempting to explain the organic by the inorganic, the main argument was the alleged birth of insects in putrefied matter. This argument was routed by Redi, who enveloped some meat in a light gauze, on which, a little later, eggs were found to have been deposited by passing flies, and at once the mystery was explained. The discovery of the microscope brought new hopes to the materialists. The animalculae which were found in certain infusions appeared to have been produced without the assistance of antecedent germs. The falsity of this conclusion was demonstrated by Schwann, and the hypothesis of abiogenesis was abandoned, until Pouchet brought it again into fashion. But experiments recently made by M. Pasteur contradict those made by Pouchet; and so far as contemporary science is competent to give a decision, the arguments of the anti-vitalists are inadequate to support their case. 

But though the theory of spontaneous generation must be abandoned, at least for the moment, the materialists are by no means at their wits' end. Life has arisen in some manner, and why not from the interaction of molecular forces?

One of the most charming hypotheses on this subject was advanced a few years ago by Sir William Thomson. To this gentleman, life, or perhaps it would be better to say a germ potentially alive, that is, having within itself the ten- dency to assume a definite living form, first visited the earth in a meteor. If it is proper to assume that meteors are fragments of shattered and once peopled worlds, it may be assumed with equal propriety that some of these fragments are partially intact. The moment, then, that it is admitted that beside our own there are a number of life-supporting worlds and that other worlds have existed in anterior epochs, it would not seem improbable that germ-bearing meteors have moved and do still move through space. As a consequence, any germ-bearing meteor which fell upon the earth during the time when it was destitute of life may have been the unconscious cause of the failure which we are now enjoying. 

Dr. Zoellner, a German scientist trained in all the illiberalities of ofiicial optimism, attempted to refute this hypothesis on the ground that when a meteor enters our atmosphere, the friction of the air makes it incandescent and consequently incapable of preserving and transporting any germ, however potentially alive. To this refutation Helmholtz made answer, that only the surface of meteors become heated, and that germs might readily remain unharmed in interior crevices, or if on the surface might on reaching our atmosphere be blown from their conveyance by the wind, and that, too, before the heat was great enough to cause their destruction. But if this solution be accepted, the origin of life on other planets remains still to be explained. It may be then, as Helmholtz has suggested, that life is co-eternal with matter, and its germs, transported from one planet to another, develop wherever they find a propitious spot. But this, too, is merely an hypothesis, and one that has not the slightest evidence in its favour. The enigma of life is for the present a part of the unknowable. But whether it will always remain so is another question. The differences which once were sup- posed to constitute a barrier between the verte- brate and the non-vertebrate no longer exist. The modifications by which the quadrupedal reptile became a bipedal bird have been clearly shown. Forty years ago, there was no evidence that such a demonstration would ever be made. Forty years hence, who shall say but that the missing link may be discovered, or the manufacture of the organic from the inorganic begun? As Professor Huxley has hinted, no one who has watched the gradual development of a complicated animal from the protoplasm which con- stitutes the egg of a frog or a hen, will deny that a similar evolution of the whole animal world from a like foundation is at least within the bounds of possibility.

Of the various creeds which man has been pleased to invent, the youngest is positivism. The position which this system of thought has acquired is due to its own merit. It cannot, like pantheism, look back through the terraces of time and claim the quaterings of race. Nor can it, like materialism, bedeck itself with Greek insignia. Among philosophies, positivism is a parvenu. As such, it is viewed with scorn, enthusiasm and indifference. 

Positivism made its debut a little over forty years ago. Its name was its fortune. There was in the sound of it an invitation to nearer acquaintance. But when the acquaintance was made, the name was found to partake of the nature of a lure. Relativism, if less attractive, would have been a clearer description. For positivism, if positive at all, is positive that there is nothing positive. Its sponsor was Auguste Comte.

If the realisation of the ambitions of youth may be regarded as the criterion of a successful career, the life of this thinker cannot be con- sidered a failure. At a comparatively early age the outlines of his doctrine appear to have been clearly defined. The outlines sprang of a suggestion of Saint-Simon, who was wont to declare that all knowledge should be co-ordinated into one vast and comprehensive synthesis, but their development was accomplished without material indebtedness. In synthetising knowledge into a single system of thought, Comte proposed nothing less than the abolishment of theology and meta-physics, and the re-organisation of the Occident through a philosophy of his own manufacture. In 1842, the sixth and last volume of this philosophy was given to the public, and with it the knell of all religions was supposed to have been rung. Ten years later, to the utter bewilderment of his disciples, Comte proclaimed the necessity of founding a new religion, of which the sovereign pontiff was to be none other than himself. 

In an earlier paragraph it has been hinted that positivism is positive that there is nothing positive, a phrase which, from a Comtist stand- point, may be taken to mean that the essence of things escapes us. We can understand the interconnection of facts - that is, their direct antecedents and immediate sequences - but the initial causes and ultimate results are inaccessible to the intellect. In a word, there is nothing except material phenomena and the laws thereof. As this principle is the pivot on which the entire philosophy turns, a momentary examination may not be without benefit. 

Many a sceptic has filled his hours in showing that things are not what they seem, but none of them, however revolutionary, have disputed the reality of consciousness, or denied the phenomena that are manifest in thought, feeling and volition. In affirming, therefore, that the objects apprehended by the senses are the only apprehensible phenomena, positivism apparently displays a radicalism which is as audacious as it is novel. It is of course possible and even proper to regard thought, feeling and volition as products of the body, but it would be a misuse of language to assert that they are material phenomena; and, as positivism's first tenet is that there is nothing except material phenomena, it would seem that, like any other screw, the before-mentioned pivot is loose. On the other hand, it may be objected that the phenomena called internal are unobservable, and that any attempt to distinguish them from their external elements results merely in demonstrating the vainness of the endeavour. If this view be accepted, positivism is found less rickety than it first appeared, and the introductory statement may be welcomed at once and without further hesitation. 

If, then, as positivism asserts, the essence of things escapes us, any speculation on the origin and purpose of the world is profitless. On such and kindred subjects the mind should be without conjecture. It is only natural that man should have been on the *qui vive* in his effort to discover efficient and final causes, but his effort has never been successful. "If God did not exist," said Voltaire, "the world would have invented him." " Which," a wit replied, "is precisely what the world has done." 

The mobility of phenomena, the fugitiveness of sensations, the impermanency of the actual, the real which each moment ends and begins anew, have, in all ages, incited to a knowledge of the unknowable. But the knowledge has not been obtained, and it was in view of the impracticability of the attempt that Comte ventured to suggest what may be termed a middle course. In the effort to pierce the impenetrable, humanity, he said, has passed and is still passing through certain stages of thought which correspond to those of childhood, adolescence and maturity. The first is the age of theology; the second, of metaphysics; and the third, of science. This doctrine, which is known as the law of the three states, conveys the suggestion alluded to, together with a theory which is as liberal as the sea. It runs somewhat as follows:

In the infancy of thought, Nature is dowered with the same illusions to which man himself is subjected. Every object is animated, and the government of the universe is ascribed, not to invariable laws, but to sentient and intelligent beings. In everything that occurs is seen the manifestation of a direct intention, and each particular event is attributed to forces which are but the aggrandisements of those of man. In the advance of thought, these forces, whose prowess is discernible in effects which man is impotent to produce, become the gods, invisible yet multitudinous. Then, gradually, as arises the capacity of co-ordinating phenomena into separate groups, the number of divinities diminishes, until, through processes of generalisation, they are reduced to one, and behold, man has passed out of fetishism into polytheism, and from thence to a belief in a unique Creator. 

But there is a further advance of thought, and in its train comes the suggestion that the uniformity noticeable in the universe is incompatible with the theory of an arbitrary Will. The initial conceptions are dismissed, the celestial and inaccessible reason of things is banished, and realised abstractions are accepted instead. Nature is governed, not by an external power, but by internal and occult qualities. The reign of dryads and nymphs is passed, and their place is usurped by entities, by theories which deal with a plastic force and a vital principle. This is the second, or metaphysical state, which is of advantage in being a negation of the first and a preparation for the third, which latter is reached when men, weary of explanations that explain nothing, discover that what is necessary for the mind is not obligatory for things, and that a cause which is conceived by the one need not have a place among the others. Such is the positive, or scientific state of mind, to which, according to Comte, all humanity tends; and such, too, is the middle course which he recommended to thoughtful and decorous persons.

Stripped of its verbal husks, the law of the three states may be reduced to a truism. In seeking the reason of things, men look first above, then within, and finally confess themselves vanquished. 

The law of the three states which Stuart Mill called the backbone of the entire philosophy, but which is not particularly new nor particularly convincing - not new, because sketched by Kant in outline, and not convincing, because Comte himself declined to be bound by - it is supplemented by a classification of sciences from out of which was drawn a fresh one, called sociology.

In the study of facts, the interpretation of the experience which is written between the lines of history, sociology was to be the lever in the substitution of science for religion. It was to terminate the conflict between theology, which demands order without progress, and metaphysics, which aims at progress and turns its back on order. It was to arrest the retrogression of the one, and still the anarchy of the other. In the government of life it was to replace religion with science, and give to intelligence the guiding strings of the world. 

In mapping this programme, Comte fancied that sociology could be raised to the level of an exact science, and that through its influence all enlightened nations would join hands in the profession of identical doctrines. In the Utopias in which he then lost himself, he planned a reorganisation of society on a basis which, if suggestive of Plato's Republic, is otherwise without value or allurement. There is, he pointed out, no such thing as liberalism in astronomy, physics or chemistry; and if it be otherwise in ethics and politics, it is because neither of them possess established principles. When they acquire them, as they will do when positivism begins its sway, the force of public opinion will disappear. A corporation of philosophers, salaried by the State and treated with the greatest respect, will have the entire charge of education, together with the right to counsel and direct each citizen in his private and public life, and enjoy, moreover, such an amount of authority over students and thinkers as will enable them to prevent the latter from squandering their time and knowledge in speculations that are valueless to humanity, and oblige them to apply themselves to such investigations as may be deemed most important to general prosperity. The decrees which the corporation may formulate are not to be questioned, and, as the idea of the sovereignty of the people is one of the most pernicious that civilisation has advanced, but slight attention will be paid to the inclinations of the masses. In each nation there will be a governing body and a body governed, in which latter the citizen will occupy the position for which his abilities have fitted him. Thereafter religion and metaphysics will disappear. Scientific dissidence will be effaced, and an invariable and uniform political dogma will at last be accepted by united and peaceful nations.

To the clear-headed and matter-of-fact audience which was Comte's, theories such as these were viewed with suspicion. The idea that there is no God had in it nothing that was alarming; the prophecy of the overthrow of superstition and the general adoption of positivist tenets seemed not unreasonable; the prohibition against idle speculations and the complementary recommendation to treat only with the real were received with open favour; but the sturdiest could not look without terror on a future governed by philosophers. 

When this horizon was disclosed, it is probable that Comte had already entered into what is known as his pathological period. In earlier years he suddenly lost his reason, and as suddenly recovered it. The border-lands of genius and insanity are never well defined, and it is not unlikely that before the *Cours de philosophic positive* was completed, something of that of which he had too much, something of that weight of thought which obscures the vision and tips the scales of common-sense, was again at work, though this time more dumbly and dimly than before. Thereafter the champion of the actual who had wished to lead God to the frontiers, and there thank him kindly for his provisory services, lapsed into a morbid mysticism. The sceptre of the world which he had given to intellect was transferred to sentiment. It was for the heart to rule and for the intellect to obey. 

The *Philosophie politique* in which his ideas on this subject are conveyed, shows, even amid the luxuriance of luminous thought, the same evidence of mental decadence as is noticeable in Kant's *Kritik der Pradischen Vernunft*. Both belong to the senilia of great minds. During the year that intervened between its appearance and the publication of his chief work, Comte conceived what his biographers term a platonic affection for a lady whose influence over him was of such a nature, that, aided by the historical meditations in which his life had been passed, he dreamed of a happiness that should be universal, and of a world that should be ruled, not by a corporation of salaried philosophers, but by love in its purest and most disinterested form. 

The pompous Religion of Humanity which he then evolved, and which has no more connection with positivism than an opera-bouffe has with logarithms, saddened the boldest among his adherents. It found adepts - what vagary has not? The altruism which it inculcated is certainly not without charm; but the deification of humanity past and future, the transformation of earth into a fetish, space into fate and numbers into virtues, are among the most deplorable instances of the aberrations of genius. After shutting out the unknowable, the door was opened to superstition; after banishing metaphysics, sentiment was beckoned in to occupy its place; religion was superseded by idolatry; and the heavens, that no longer told of the glory of God, were set ablaze with the memories of great men. 

In its uncorrupted form, positivism is a modification of materiaUsm. Among theologians there is a disposition to regard both in the same light. But no positivist likes to be called a materialist. He shows as much displeasure at the term as he would were he called a theist or a pantheist. And, indeed, the lines of demarcation, if not always broad, are none the less apparent. At the origin of things, theism places a personal and infinite Being; pantheism sees in all things the immanency of a Being that is infinite but impersonal; and materialism asserts that the cause of all things lies in the arrangement and properties of force and matter. Positivism, on the other hand, knows nothing of an infinite Being, whether personal or impersonal; in the spheres that are inaccessible to it, it recognises nothing but matter and the properties of matter but, unlike materialism, it draws no conclusions. According to Littré, positivism is simply a methodical, hierarchic arrangement of the general facts of science, excluding every subjective element, and accepting nothing that is not drawn from experience. 

A positivist, moreover, shows no evidence of delight at being called an atheist. As Littré has described him, an atheist is in a certain measure a theologian. He is not entirely emancipated. He has his explanations of things; he knows how they began. He believes in the chance clash of atoms, or in occult forces, or in a first cause. Of all this the positivist knows nothing. He ignores productive atoms as well as a creating and ordaining force. But whoso thinks that history follows a development that is obedient to a natural law - whoso thinks that the origin of societies, the establishment or mutation of religion, the founding of empires, cities, castes, aristocracies, governments, oracles, prophecies, revelations, theologies, arts and industries, are due, one and all, to the faculties of man - whoso accepts this view has fully accomplished the cycle of mental emancipation. The moment that he leaves no place for the supernatural either in the organic or the inorganic. either among cosmic phenomena or among those of history, that moment he passes initiate into the brotherhood of positivism.

The charm of positivism is the matter-of-fact position which it assumes before the insolvable. If it cuts no old knots, it brings no new tangles. It treats metaphysics with the respect which is due to all that is venerable; in the presence of religion it puts the dialectic broadsword softly back in its sheath. It leaves the great query where it found it. And in this is its wisdom; its agnosticism is its strength. Clamour as we may, there is no answer to our whys and wherefores. There is in us, about and beyond us, an enigma that will defy the Champollions of the future as it has routed the seers of the past. The reason of things lies beyond the sphere of knowledge, and the nearest approach that can be made is in a suspicion that all is relative.

[^9]: Arthur Schopenhauer. Von ihm. Ueber ihn. Frauen- stadt.

[^10]: The Philosophy of Disenchantment. Houghton, Mifflin & Co., Boston
