# A Poet's Verdict

There have been days in the history of the world when the poet was regarded with a respect that approached veneration. He was considered the oracle of the gods, and his voice was listened to with reverence. This pleasant custom has fallen into disuse. The gods have disappeared and carried the divine afflatus with them. In an age like the present, the demand for poets is slight. Their titles have been examined, and it has been found that to be useless is their one patent of nobility. As a consequence, the poet's vocation has seemed to many a synonym of the ridiculous. And yet, as Gautier with a charming affectation of naivete remarked, an inability to write in verse can scarcely be considered as constituting a special talent. But there is another inconvenience; a poet is never rightly appreciated save by his peers; and as his peers are infrequent, the majesty which resides within him often lacks the trumpetings of a herald. Then, too, in an era of remorseless activity, it is only quiet people who live in the country that find leisure to listen to the footfalls of the Muse. For the benefit of such as they, verse may be divided into three broad classes: that which pleases the author's enemies, that which pleases the author's contemporaries, and that which passes unobserved to pleasure the idlesse of posterity. Of these classes, the verse of Leconte de Lisle belongs to the third. 
Any one who has taken an interest in French literature during the last decade can hardly have failed to notice the number of new writers that have come into being, and more particularly the inferiority of their work. In explanation of this surge of mediocrity, many theories might be advanced; but perhaps the most palpable would be that the literature of our expiring century, after having passed from youth to virility, has begun to experience the maladies and garrulities of old age. But however the subject may be viewed, it is at least evident that the paladins of 1830, who were as revolutionary in literature as their ancestors were in religion, have passed away, and also that their methods have so far disappeared with them that the day before yesterday Victor Hugo seemed like a living, anachronism. Readers latterly have refused to be interested in the phantasies of the romantics, and perhaps their pages were a trifle over-coloured; but their excuse lay in the fact that literature had become impoverished through conventionalities; there were synonyms instead of words; and in place of ample vocabularies there were small niceties of expression. All this the romantics did away with. They breathed health and vigour into an enervated dictionary, and startled Europe with the opulence of their adjectives.

It was in those victorious days that Gautier threw aside his brush and went in a famous red waistcoat to guy the philistines at the birth-night of Hernani. In graver years Gautier complained that in the eyes of the bourgeois he had never ceased to wear that crimson garment, and somehow, save among the liberal few, he has always been looked upon more or less askant. It has been said that it was his purpose to seek the hazardous and display it, but it must be admitted that what he had to say he told with a grace such as had been seldom heard before. He chose his words for their colour, for their aroma, as one may say; and it is related that he objected now and then to an accent because it took away something from the charm which the grouping of certain letters otherwise conveyed. 

Through those days, too, Alfred de Musset passed with the indolence of a dissolute young god. He joined the ranks of the romantics, as did all men of talent, but he joined them more as an amateur than a professional: the familiar ballad in which the moon is represented as suspended over a steeple like a dot over an *i*, opened for him the doors of the cénacle without even giving him the trouble to knock. In a subsequent poem he asked forgiveness for that misdeed; and though he boasted that his Muse went bare of foot like Truth, she might still have been pictured as shod with buskins of gold. 

Another of the heroes of this epoch was Alfred de Vigny. Some one has said that the face of a poet is never known until years and sorrow have marred its original beauty; but to this rule de Vigny was an exception. He was famous when quite young, and his bust, as it stands today in the lobby of the Theatre Français, arrests the attention even of the indifferent. At the time to which allusion is made, he mingled but little with his fellows, appearing only when the moral support of his presence was needed. In later years, in spite of his talent, his beauty and his position, de Vigny, devoured by melancholy, turned his back entirely upon the world, and retired into what Sainte-Beuve has termed his *tour d'ivoire*. 

In the wake of these poets came the familiar figure of Charles Baudelaire. Recently he has been described as having had the appearance of a deHcate prelate, a trifle depraved. This description might be suggested by the mere reading of his verse. In the work of every poet there is something of the individual, and it is probable that few have studied the chiselled lines which he worked up with even a shrewder eye for the Satanic than that which was given to Edgar Poe, without calling up some such picture of their author. Baudelaire entered the ranks when the battle was won, but nevertheless he managed to flaunt a standard that has troubled the vision of many an after-comer.

So swiftly does time go by, that of these writers little more than tradition now remains. In the eyes of contemporary critics, de Musset is a dislocator of Alexandrines, de Vigny is a memory, Baudelaire a curiosity, and Gautier a model. Yet each of them left a legacy that is still disputed. From de Musset descends the gift of eloquence; in Baudelaire's testament is the heirloom of lurid effect; de Vigny has devised his morbidity; while Gautier's bequest is perfection in form. Taken together, they were the poetic embodiment of the agitation of which Voltaire, Holbach and Diderot were the heralds. "Je ne crois pas, ô Christ, à ta parole sainte," cried de Musset, and the cry was echoed by his fellow workers. 

In a literary sense, these poets were, on their first appearance, very generally looked upon as impertinent innovators, and in their assault upon the classicists they caused much rage and rhetoric. Viewed at this distance, the disturbance seems unnecessary; for, after all, what is romanticism but the art of pleasing one's contemporaries, and what is classicism but the art which delighted earlier generations? Turn about is always fair play. In a little while Hugo will be a classic, precisely as Racine is beginning to be considered a romantic. But be this as it may, the seething passion which in 1830 seemed more alluring than the chill restrictions of former years, gradually disappeared, and its place was taken by the serene impassibility of another group of poets who were called the Parnassians. 

The advent of this new school was necessarily less boisterous than that of their predecessors: for that matter, they excited more ridicule than anger; and it is related that a cabman in a street row, after having called his adversary everything that was unpleasant, hurled at him with withering contempt as last and supreme reproach, the unavengeable insult, "*Parnassien, va!*"

Of the poets who made up this group, the better known are MM. Sully-Prudhomme and François Coppée. Sully-Prudhomme is an avowed materialist and frankly pessimistic. His poems may be summarised as a series of very delicate impressions intermingled with a fair amount of philosophic suggestion. His repertory is not extensive. It consists in three or four themes and their variations - such, for instance, as the familiar aspiration toward the infinite, man's sentiment of nothingness before the immensity of the universe, the agony of doubt, and the usual communion with Nature. The limits of this range do not necessarily imply a lack of ability. The art in any form of verse consists merely in the skill with which one or more of half-a-dozen old-fashioned sentiments is rendered, and in this respect the work of Sully-Prudhomme is generally irreproachable. In his treatment of purely personal dramas, the mental and moral combats which we all of us wage with ourselves, he leaves little to be desired, and it would be difficult to mention a poet who has entered more deeply than he into the psychological develop- ments of the century. For all this he has received much praise, and if his verse is ever criticised, it is because it is at times a trifle vague. Sully-Prudhomme has been as honestly puzzled by the discord between the real and the ideal as any writer of his class; but in his perplexity his thought floats away to uncertain heights, and there disappears with a flutter of restless in-quietude. To put the matter briefly, Sully-Prudhomme very often seems as though he were about to say something well worth the telling, but before he has gotten it safely on paper the force of the idea has vanished.

François Coppée is another of the dispersed Parnassians. His negations, if more carefully veiled than those of Sully-Prudhomme, are none the less discernible. He is at times dramatic, but his sadness is always insistent. To be sad is admittedly the poet's privilege; yet to be simply sad, and to express such a state of being as who should say, "I hunger" or "I thirst," is not necessarily poetic; rather is it commonplace. To be worth the telling, grief should express a thought that is neither humdrum nor familiar; it should lay bare fresh possibilities or set new limits to resignation: if it does not do this, then, however readily the tears may flow, however gracefully the grief be told, it is what a boulevardier would call *le vieux jeu* - the old story, of which we are most of us thoroughly tired. It is this old story that M. Coppée re-tells; and though the telling is managed with much refinement, it is impossible to call it novel. M. Coppée has also much to say about his boredom. Boredom, however, is not a flexible topic; indeed, unless it is handled with unusual dexterity, there is a danger that the reader will find it even more irritating than the writer, and thereupon withdraw his attention and support. Boredom also is more of a fine art than is generally supposed, and not to every one is it given to disentangle original ideas from that which is flat and unprofitable. Leopardi and Baudelaire have done so, it is true; but between them they managed to throttle the subject and share the booty. For a later comer like M. Coppée, nothing was left. 

MM. Prudhomme and Coppée have both sat at the feet of Leconte de Lisle. Today they are better known than he, but neither of them have ventured to rate their work above that of their master. In this modesty much good taste is shown. He has none of their faults, and, moreover, he has genius, which both of them lack. In comparison with him they are as concettists to Dante.

Leconte de Lisle is perhaps the most perfect poet of France. It is he who is the rightful heir to the legacies of the romantics, and these possessions he has rounded and improved with an erudition which embraces history, philology, archaeology, anthropology, and doubtless much more beside. In spite of this, or perhaps on that account, his literary luggage is scant. He has translated a few ancient authors, written a drama or two, and pubUshed three compact volumes of verse. In speaking of the latter, it is difficult to describe them in a phrase, though this perhaps may be accomplished in saying that they do not contain a commonplace line. The three volumes are respectively entitled, *Poèmes antiques*, *Poèmes barhares*, and *Poèmes tragiques*. The first division, which is largely made up of Vedic hymns and Greek idyls, is one in which the characteristics of the author are best displayed, and in which his impersonality is most strongly marked. Many of the poems in this series bring with them a haunting impression that they are translations from some unknown Valmiki, while others might be taken for the work of Max Müller turned poet. 

When these poems were first published, they created among the lettered an intense admiration. It was admitted that lines of such splendour and impersonal serenity had never been hewn before and certainly, after the ardour of the romantics, their impassibility could not have been other than a refreshing change. It was, however, the fortune of the book to appeal only to scholars to the newspaper public it was unintelligible; the author had made no effort to please; and, moreover, he had declined to make any concessions to the ordinary reader. The result might have been foreseen; Brahma was declared to lack actuality; and it was held to be tiresome to construe a modem poet with a Greek dictionary. What, it was asked, has Juno done to be called Héré, and why must the sky be ouranos? 

As was the case with the series just mentioned, the *Poémes barbares* found favour only with the few. To the general public they seemed very subversive. They displayed a pessimism which was new to France, and which, being new, was eyed with suspicion. Then, too, Leconte de Lisle was calmly anti-theistic. The bravado of Maréchal is boyish in comparison to his grave disdain of things celestial. In the *Poémes barbares* there are lines that startle and coerce, lines in which the horrible is expressed with such colour and yet with such austerity that the reader shudders as he reads and admires as he shudders. Beside them, the declamations of that dissolute Greuze of literature, Alfred de Musset, sound cracked and thin - like a man's laughter, as Mr. Swinburne has it, heard in hell. 

The *Poémes tragiques* are not as satisfactory as are the others. They are made up of a dozen or more recitals which have much to do with the shedding of blood, a few ballads, villanelles, pantoums and sestines, together with a bar or two of pure harmony.

Leconte de Lisle is the Goya of verse, and yet, through a delicious contradiction, one of the most noteworthy characteristics of his work is its constant evocation and suggestion of the beautiful. No other modern poet, except perhaps Mr. Swinburne, has shown a better acquaintance with the road to Paphus. And it would be a task full of charm to follow him from the jungles of the Indian peninsula to the cool lakes of Norway, to fan Leïlah and kiss Glaucé. Unfortunately, the purpose of these pages will not permit of such pleasant digressions, and the beautiful must be neglected that the poet's anti-theism may be the more quickly understood. By way of introduction, a momentary examination of the poem *Qaïn* will not, it is imagined, cause any after reproach of time misspent. 

The scenario is simple and audacious. The son of Elam, Thogorma the seer, a captive among the Assyrians, dreams of a night in the mysterious ages when the voice of God echoed through the universe, and in his dream he sees Henokhia, the city of giants, in whose highest tower is the tomb of Cain. Cain's descendants are wending their way homewards from the chase. Thogorma sees them disappear in the immense orb of the ramparts, while night, bringing a vague terror and dumb dread, mantles the great stairways that turn in red broad spirals to the winds. He hears the roar of lions, chained on the ascending steps, and beneath the porticos the clamours of crocodiles rise from the reservoirs. Then, abruptly, from the confines of the outlying desert, a spectre, loosed from Gehenna, surges through the shadows, and Thogorma hears the spirit anathematise Cain and all his race. 

Cain awakened, stands upright in the granite sepulchre where for ten centuries he had slept with his face to the sky. His eyes, haunted by one supreme remembrance, contemplate through the preceding epochs the vanished days when the world was young and with his thoughts rich; with the memory of the earth's primal innocence and beauty, he calls to the phantom to be silent and narrates his sombre history. Conceived while his parents were labouring under the divine malediction, his mother, Eve, swooning in the brambles, gave birth with a shriek of horror to Jehovah's victim, to him who was Cain. Nursed with tears, his boyhood knew no smile. What had he done, he wondered, to be punished too? And so, later, in the knowledge of his exile he accosts the angel on guard at the gates of Eden, and learns that on the morrow he is to know the reason of his birth. On the morrow the reason is made apparent. Jehovah arms his hand against Abel, and incites him to kill the brother whom he tenderly loved.

Here ends Cain's account of his life; but immediately, in his awakened thirst for vengeance, he prophesies that when Jehovah is wearied with the world and shall seek by means of the deluge to destroy it, he, Cain, will save the ark - which the poet represents as constructed in spite of Jehovah - whereupon man, no longer brave, but cowardly and envious, will rise from the flood with its mud in his heart. Cain, the avenger, continues:

> Dieu triste, Dieu jaloux qui dérobes ta face,
> Dieu qui mentais, disant que ton oeuvre était bon, 
> Mon souffle, ô Pétrisseur de I'antique limon, 
> Un jour redressera ta victime vivace. 
> Tu lui diras: Adore! EUe répondra: Non! 

> Afin d'exterminer le monde qui te nie, 
> Tu feras ruisseler le sang comme une mer, 
> Tu feras s'acharner les tenailles de fer, 
> Tu feras flamboyer, dans I'horreur infinie, 
> Pres des bûchers hurlants le gouffre de l'Enfer 

> Mais 

> Je ressusciterai les cités submergées, 
> Et celles dont le sable a convert les monceaux:
> Dans leur lit écumeux j'enfermerai les eaux:
> Et les petits enfants des nations vengées, 
> Ne sachant plus ton nom, riront dans leurs berceaux!

> J'effonderai des cieux la voûte dérisoire. 
> Par delà l'épaisseur de ce sépulchre bas 
> Sur qui gronde le bruit sinistre de ton pas,
> Je ferai bouillonner les mondes dans leur gloire:
> Et qui t'y cherchera ne t'y trouvera pas. 

> Et ce sera mon jour! Et d'étoile en étoile,
> Le bienheureux Eden longuement regretté
> Verra renaître Abel sur mon coeur abrité; 
> Et toi, mort et cousu sous la funébre toile. 
> Tu t'anéantiras dans ta stérilité.

Apart from the wonder and majesty of the language, and apart, too, from the intuition which in earlier stanzas enabled the poet to call again into being the life of the past, *Qaïn*, on a first reading, seems to be merely a work of cultured and harmonious blasphemy, and, indeed, so far as the blasphemy is concerned, nothing more vehement has been penned since AEschylus; but yet on a re-reading *Qaïn* is found to be little else than an allegory of the protestation of the intellect against the unintelligible, a revolt at the mystery of pain. 

This protestation, which is as old as philosophy, and which in recent years seems to have increased in volume and significance, has been conveyed by Leconte de Lisle in other poems with great originality, and with particular power in the parable of the *Corbeau*. Through this poem, as through *Qaïn*, there is a running accompaniment of muffled discontent, which in other verses finds a clear and decided note. Something of this same dissatisfaction was expressed by de Vigny and Alfred de Musset, and yet in their case one is inclined to fancy that the grievance was less reasoned than instinctive; they were at odds, so to speak, with the inevitable; life failed to hold what it had seemed to promise, and in consequence their complaints were more or less personal. But in Leconte de Lisle there is no evidence of personal disappointment, and nothing that can be construed as the outcome of an individual grievance. It is a part of his doctrine that an expression of pleasure or pain deforms the human visage, that the poet's correct attitude is the one which most nearly approaches the impassibility of the statue, and it is this theory which he has carried into his work. 

It is difficult to say to what category of anti-theism Leconte de Lisle belongs. His pantheism is too evident to permit of his being called a materialist, and yet his materialism is so marked that it is difficult to suspect him of any other sympathies with the ideal than those which are purely poetic. He is too aggressive for an agnostic, and yet there are moments when he might be taken for a positivist. Perhaps it will be safest to say that he is a theoretic pessimist, a denomination which is broad enough to include any of the others, and at the same time is serviceable in conveying the exact shade of his thought. 

The pessimism which is manifest in the verse of Leconte de Lisle has nothing of Renan's serenity, and none of the calculations of Von Hartmann. In his case it is the formal protest against the enigma of grief which characterises the philosophy of the earliest thinkers, but one which is entirely free from the shackles with which they delayed the hope of ultimate emancipation. It is not that the idea of absorption in Brahm, or the extinction in Pari-Nirvana, is disagreeable to him ; on the contrary, they are dreams through which he lovingly trails his verse, but they are dreams. 

> Pleurez, contemplateurs! Votre sagesse est veuve Viçnou ne siege plus sur le lotus d'azur.

That of which he seems best convinced is the irremediable existence of what apparently has no reason for being. History is little else than the tale of an uninterrupted shudder; chronicles of private life are merely accounts of combats that individuals have waged with fate; and Leconte de Lisle, who is a patient student, has noted compassionately in both the persistence of the law of evil. He should not, however, be considered a follower of Schopenhauer; the majority of his poems were pubUshed before the *Welt als Wille und Vorstellung* had crossed the Rhine; moreover, Schopenhauer did not invent pessimism; Kapila was as much occupied with pain as was that Emerson in black; indeed, it is curious to note that the first metaphysician as well as the latest of great poets are agreed that life is an affliction, and it is also curious to note that the tendency of modern thought is to an agreement with their views.

The soul, whose immortality Robespierre decreed in the law known as that of the i8th Floréal, year II.; the soul, which all antiquity, Plato included, accorded to beasts, but whose possession Christianity has limited to man; the soul, which is reported to come no one knows whence, and to depart no one knows whither, has for Leconte de Lisle a purely verbal existence. Robespierre, it is true, knew nothing about primitive man; but Leconte de Lisle does, and he knows, too, that a gorilla to which a soul is refused today is not a whit more elevated than was man in the sylvan age - in that age, in fact, when he had no other weapons than the branches which he tore from a tree. And if a soul be refused to primitive man, at what epoch was the gift bestowed? Is it a result of evolution, or, as certain theologasters have asserted, is it naturally one with the body, and only separable and capable of immortality through the influence of grace divine? The last century combatted these theories with logic. Leconte de Lisle has at his disposal not alone the logic of yesterday, but the science of today, and to him the soul is a phantom evoked by the conscience.

"If you do not believe in a soul and in a future life," said some one to Goethe, "what do you consider to be the object of the present?" To which Goethe, with Olympian egotism, answered tersely, "Self-improvement." One may fancy that to Leconte de Lisle the object of life is none other. He was born in the Isle de Bourbon something over sixty years ago, and came to Paris when quite young. From his early home he brought little else than memories of the beauty of Nature and the invincible immensity of her forces, memories that have since served as frames and backgrounds to his verse. In Paris he followed the developments of science, and studied history, religions and life. From them he learned that man has two antagonists, himself and the exterior world; he found, too, that man is a prey to influences which mould him to their profit, and that humanity had aggravated its misfortunes by inventing explanations which it termed beliefs. Since then, in the quietest ways, he has passed his hours in satiating that vague curiosity which besets even the most indifferent, and in con- vincing himself not only of the nothingness of creeds, but of the nothingness of life. Life, he says:

> La vie est comme l'onde ou tombe un corps pesant:

> Un cercle étroit s'y forme et va s'élargissant, 

> Et disparait enfin dans sa grandeur sans terme. 

> La Maya te séduit, mais, si ton coeur est ferme, 

> Tu verras s'envoler comme un peu de vapeur 

> La colere, l'amour, le désir et la peur, 

> Et le Monde illusoire aux formes innombrables 

> S'écroulera sous toi comme un monceau de sables.

Gibbon, who was fond of fine paragraphs, declared all religions to be equally true to the vulgar, equally false to the philosopher, and to the statesman equally useful. But Gibbon omitted the poet; and to such an one as Leconte de Lisle no religion can be true, if for no other reason than that there is no criterion of truth; no religion can be wholly false, for every religion has enjoyed an hour of undeniable actuality; and no religion can be deemed useful if the need of it has disappeared. To his thinking, religions have served their purpose. Compounded of fables more or less absurd, and of ethics more or less wholesome, in their obscure origins they were intended to be explanations of natural phenomena with which to-day we are better acquainted. As to Christianity, it is to Leconte de Lisle an artistic creation, powerfully conceived, venerable in its antiquity, and one whose place is now marked in the museum of history.

It has been objected, that should this view be accepted, no one would turn to the Bible for instruction, and as a consequence the gateways to immorality would be opened wide. Now Plato said that we should esteem it of the greatest importance that the fictions which children first hear should be adapted in the most perfect manner to the promotion of virtue. There are, however, not a few grave thinkers who have asserted that the Bible is inapt to serve such an end. Admittedly the morality which is displayed in the Synoptic Gospels is admirable, but it is sometimes forgotten that it is an integral part of the teaching of Socrates and the Socratics. M. Havet has shown its sweetest precepts flowing from their lips. In other portions of the Bible there are verses that exalt the spirit like wine there are delicacies of thought and felicities of expression that both soothe and charm; but one must needs be a paradoxist to claim either as an aid to the promotion of virtue. Beside, as has been hinted in earlier pages, morality is more a question of temperament than of instruction. For that matter, we are most of us well aware that the instruction sometimes defeats its aim. Mr. Froude relates that when St. Patrick preached the gospel on Tarah Hill, the Druids shook their heads. The king, Leoghaire, marked their disapproval wonderingly, and asked, "Why is it that that which the cleric preaches seems so dangerous to you?" "Because," they answered, "he preaches repentance, and the law of repentance is such that a man shall say, 'I may com- mit a thousand sins, and if I repent it will be not worse with me; I shall be forgiven; therefore will I continue to sin.'" Leconte de Lisle has therefore put the Bible reverently aside, and in looking back through the dreams from which it came and into the visions which it has evoked, he has murmured with the sadness of the tender-hearted:

> O songe, ô désirs vains, inutiles souhaits, 

> Ceci ne sera point, maintenant ni jamais.

There is no help there, nor is there any elsewhere. The Orient is asleep in the ashes of her gods. The star of Ormuzd has burned out in the skies. On the banks of her sacred seas, Greece, hushed for evermore, rests on the divine limbs of her white immortals. In the sepulchre of the pale Nazarene, humanity guards its last divinity. Every promise is unfulfilled. There is no light save perchance in death. One torture more, one more throb of the heart, and after it nothing. The grave opens, a little flesh falls in, and the weeds of forgetfulness which soon hide the tomb grow eternally above its vanities. And still the voice of the living, of the just and of the unjust, of kings, of felons and of beasts, will be raised unsilenced, until humanity, unsatisfied as before and yet impatient for the peace which life has disturbed, is tossed at last, with its shattered globe and forgotten gods, to fertilize the furrows of space where worlds ferment.

On this vista the curtain may be drawn. Neither poet nor seer can look beyond. Nature, who is unconscious in her immorality, entrancing in her beauty, savage in her cruelty, imperial in her prodigality, and appalling in her convulsions, is not only deaf, but dumb. There is no answer to any appeal. The best we can do, the best that has ever been done, is to recognise the implacability of the laws that rule the universe, and contemplate as calmly as we can the nothingness from which we are come and into which we shall all disappear. The one consolation that we hold, though it is one which may be illusory too, consists in the belief that when death comes, fear and hope are at an end. Then wonder ceases; the insoluble no longer perplexes; space is lost; the infinite is blank; the farce is done.
