# Bibliography {-}

In addition to the authorities cited in the text, the writer desires to express his indebtedness for facts and suggestions derived from the following works:

* "Hindu Philosophy," Davies 

* "Buddhism" (Hibbert Lectures), Rhys-Davids

* "Sacred Books of the East," edited by Max Müller

* "Hinduism," Monier-Williams

* "Buddha, sein Leben, u.s.w.," Oldenburg

* "Traduction du Tao-te-King," Stanislas Julien

* "Le Génie des Religions," Quinet

* "Geschichte des Materialismus," Lange

* "Pyrrhon," Waddington

* "La Religion Romaine," Boissier

* "Histoire des Origines du Christianisme,"  Renan

* "Histoire Naturelle des Religions," Véron

* "Doctrines Sociales," Guyot 

* "Histoire du Diable," Réville

* History of Rationalism," Lecky 

* "La Renaissance," Marc-Monnier

* "L'Allemagne," Heine

* "Le Matérialisme," Janet

* "Auguste Comte et la Philosophie Positive," Littré

* "Diderot," Scherer

* "Memoires pour servir à I'Histoire de la Philosophic," &c., Damiron

* "Le Roi Voltaire," Houssaye

* "Les Contemporains," Lemaître

* "Histoire du Christianisme," Leconte de Lisle

* "History of Philosophy," Lewes 

* "Dictionnaire des Sciences Philosophiques." 
