# Part 2: The Age Of Man

Eärwa is seen as the cradle of civilisation, the home of the Cûnuroi and the greatest
nations in the history of the world. But it is not the only continent in the world. To the
south, beyond the Three Seas, lies the desolate desert land of Kutnarmu, dominated by
vast deserts and untraversable wastes. To the east, beyond the vast Kayarsus Mountains,
lies another land: Eänna, the Land of the Uplifted Sun.

Little is known of Eänna, even today. Explorations of that continent have revealed
mountains, deserts and plains, populated sparsely. Such explorations have not
progressed far before turning back for lack of supplies, or have not returned at all. But
we know that the earliest tribes of independent men dwelt in Eänna. Even as their
western brethren were enslaved by the Cûnuroi, becoming the Emwama, the men of
Eänna were building the rudiments of civilisation. Over time they became divided into
five distinct tribes: the Ketyai, the Norsirai, the Satyothi, the Scylvendi and the
Xiuhianni. The Tribes warred against one another but were also united by religion. The
Tribes came to believe in the Hundred Gods, a hundred distinct, individual spiritual
20entities, divine aspects of the God-of-Gods, who responded to their prayers and
intervened in the affairs of men.

Originally, sorcerers were respected amongst the tribes. They were seen as wizards and
prophets both, Shamans , and for centuries they dominated the spiritual discourse of
humanity. But others became jealous of their power. The Old Prophets, non-sorcerous
servants of the Hundred, rose to power, propelled by divine miracles. They proclaimed
that all sorcerers were damned to an eternity of pain and suffering for their challenge of
the gods’ power. In time the Shamans were defeated, and sorcery outlawed by the word
of the Gods. The sorcerers were reduced to the Few, a tiny number of warlocks and
witches practising at the very fringes of society, whilst the philosophical notion of the
God-of-Gods lost importance, becoming a “placeholder” in theology.

The new religion, the Kiünnat tradition, was given form and structure through the
Tusk. A colossal bone-artifact, the Tusk was inscribed with the holy words and stories of
the Five Tribes, accumulated over centuries. It was gifted to the Tribes by strangers who
journeyed out of the west. The age of the Tusk is unknown, save it far predates the
Breaking of the Gates, which took place (according to tradition) 4,132 years before
Anasûrimbor Kellhus's Great Ordeal marched onto the Istyuli Plains.

The Tribes of Men dwelt in the wilds of Eänna for centuries. Their forays into Eärwa
were met with enslavement or death at the hands of the Cûnuroi, whom the Tribes
soon came to curse as the Oserukki, "Not Us", the Nonmen. It was a hard existence in a
hand land.

Despairing of the lot of men, Angeshraël, a priest or holy man of the Tusk, climbed to
the peak of Mount Eshki, fasting and praying to the Hundred for guidance. At length,
he descended from the mountain and found a hare to skin and eat. Once he had his
fill, he was joined at his fire by a man, at first glance a traveller of the wastes. But
Angeshraël recognised the man as the god Husyelt, the Holy Stalker made manifest,
and fell to his knees. Husyelt asked why he did not throw his face into the earth as
homage demanded, so Angeshraël did as he bid, even though this meant bowing his
head into his fire. Angeshraël burned his face, but the god acknowledged his piety.
They talked for a time before Husyelt left him. The experience ended the time of
Angeshraël the man and began the time of Angeshraël, the Burned Prophet.

He went amongst the Five Tribes, declaring that beyond the western mountains lay a
land of bounty and gift which was the rightful birthright of the Tribes. It was held by an
accursed race of False Men whose extermination was called for by the Tusk itself. The
False Men wielded great powers, but when the Tusk was delivered unto the Tribes
certain "gifts" had come with it, metal spheres which would render these powers useless.
Angeshraël's words spread amongst the Tribes and soon found great favour. He urged
those who would follow him to gather on the slopes of Mount Kinsureah.

There Angeshraël made his final case, arguing for the Five Tribes to cross the Great
Kayarsus and claim the Land of the Felled Sun, Eärwa, the promised land. There was
tremendous doubt and discussion. One of the Five Tribes, the Xiuhianni, rejected his
words and left, scattering back into Eänna. But Angeshraël convinced the rest by
performing a great sacrifice, slaying his son Oresh as a sign of his conviction.

The four remaining tribes agreed to follow the Burned Prophet. In their multitudes,
they swarmed through the mountain passes of the Great Kayarsus and found their way
barred by the Gate of Thayant, the Gates of Eärwa, which the Nonmen had fortified in
ages long past. Great assaults were made, but even reduced by their wars with the
Inchoroi, the Cûnuroi were able to throw back every assault through their Qûya mages.
The Tribes had the power of the Chorae to aid them, but even this was checked by the
Qûya, who had experience of resisting the weapons.

Reluctantly, an accord and truce was made amongst the Four Tribes. It was agreed that
sorcerers could again practice their magic in the service of the Gods. Thus, the first
sorcerous schools were founded, organisations of wizards and warlocks (but not
witches; the Kiünnat teachings insisted on the inferiority of women in matters both
temporal and spiritual, a stipulation that would not be thrown down until the time of
Kellhus four thousand years later). Although practicing Anagogic sorcery (rooted in
tradition and superstition) far inferior to the Gnosis of the Qûya (rooted in
mathematics and logic), the sheer number of the Halaroi sorcerers soon overcame the
Nonmen.

The Gate of Thayant was broken and shattered. Beyond, according to many historians,
lay the great Cûnuroi mansion of Siöl itself. The Four Tribes ranged through its halls,
putting the Cûnuroi to death and casting down the far gates, allowing the Halaroi in
their tens and hundreds of thousands to swarm through and out onto the plains of
north-eastern Eärwa.

The Tribes threw down the gates in ruin, an act immortalised as the "Breaking of the
Gates", the beginning of recorded history and also the beginning of the Second Age,
Far Antiquity and the Age of Bronze.

The four tribes swept across Eärwa from the north and east, throwing down the great
High Mansions one-by-one. Some fought bitterly, but others, traumatised by millennia
of tragedy, opened their gates and bared their throats to the inevitable. After the fall of
Siöl, Nihrimsûl followed, and then the remnants of Viri and far Illisserû. Only Ishoriöl
and Cil-Aujas survived of the great mansions. The Cûno-Halaroi Wars were fought over
generations but ended in the defeat of most of the Cûnuroi in Eärwa.

Once secure in Eärwa, the tribes found new homes. The hardy Norsirai settled the
north, particularly the lands to the south of the Sea of Neleöst along the fertile River
Aumris. The Scylvendi settled the lands further south, between the Atkondras
Mountains and the Hethanta Mountains, on the Jiünati Steppe and the lands south as
far as the unhospitable Great Carathay Desert. The Ketyai, the most numerous tribe,
made their home on the rich Kyranae Plains and the lands extending north and east
around the Meneanor Sea and Sea of Nyranisas, as far east as the Southern Kayarsus.
The Satyothi went to the far south-west of Eärwa, beyond the Atkondras range and
Carathay Desert, settling the lands to the west of the Hinayati Mountains as far as the
Great Ocean itself.

The first human nations arose soon after. The Satyothi, isolated from the rest of Eärwa
by geography and distance, established a kingdom known as Angka, a forerunner of
modern Zeüm. The Ketyai established the kingdom of Shigek, the first nation of the
Three Seas, around the broad delta of the River Sempis. Another Ketyai kingdom was
established at Nilnamesh in the far south, beyond the Carathay Desert. The Scylvendi
disdained the trappings of civilisation, preferring to remain pastoralists dwelling on the
steppes and plains.

But it was in the Ancient North that human civilisation first truly took hold in Eärwa.
The River Aumris and the surrounding region became the focus of such settlements,
with the great Norsirai cities of Trysë, Sauglish, Etrith, Lokor and Ûmerau founded in
relatively short order. Controversially, these city-states disdained the command of the
Tusk to exterminate the Nonmen and began trading with the Cûnuroi of Ishoriöl to
the north-east, to their mutual enrichment. The power of the Aumris River cities grew
quickly. Somewhere in the 4th Century after the Breaking of the Gates, Cûnwerishau,
the God-King of Trysë, made a pact with Nil'giccas, the King of Ishoriöl. He received a
copy of the Isûphiryas , the chronicle of the history of the Nonmen prior to the
25Breaking of the Gates and the oldest extant work of literature in the world. The Cûno-
Halaroi Wars ended with an accord of peace and trade.

By 430 Year-of-the-Tusk, the God-Kings of Trysë had been overthrown and Ûmerau
had became the primary power of the Aumris River Valley. By 500 the Ûmeri Empire
had formed, the first truly great empire of men, extending along the full length of the
Aumris River and extending across the lands to either side. This also coincided with the
growth in power of the Ketyai to the south, with the Seto and Annaria tribes colonising
the length of the River Sayut and the Secharib Plains.

In 555 the Nonman Tutelage began. The Cûnuroi, mostly of Ishoriöl, formed an
alliance with the Norsirai of the Ûmeri Empire and began teaching them in arts both
mundane and sorcerous. Most notably, the Nonmen Qûya imparted to the Norsirai
Anagogic sorcerers the secret of the Gnosis, the most powerful form of sorcery known
to exist. It was also around this time that the subtle Cûnuroi game of benjuka was also
taught to men. Those Nonmen who went to live amongst humans and serve them as
teachers were called Siqû.

The next three centuries saw the Ûmeri Empire flourish thanks to this alliance. In 560
the Great Library of Sauglish was founded by Carû-Ongonean, the third Ûmeri God-
King. Ten years later he founded the fortress of Ara-Etrith, "New Etrith", which would
later be called Atrithau.

Emilidis, the Artisan, the creator of the Sublime Contrivances (the greatest works of
Nonman sorcery, including the Day Lantern, the Immaculate Rim and the Barricades
themselves), deigned to teach some of the sorcerers of man. About 661 he founded the
Gnostic School of Mihtrûlic, the Contrivers. Gin'yursis, a Cûnuroi of Cil-Aujas exiled
from his home mansion, travelled to the Ancient North and undertook tutoring of
men in the arts of sorcery. In 668 he founded the Gnostic School of Sohonc. His
student Sos-Praniura would then found the Gnostic School of Mangaecca in 684,
under the tutelage of Cet’ingira. The power of the Ancient North increased thanks to
these schools of learning and sorcery.

In 750 the Heron Spear, Suörgil ("Shining Death"), seized from the Inchoroi King Sil
by Cû’jara Cinmoi himself, vanished from its place of safekeeping, deep in the heart of
Ishoriöl. Unbeknown to the rulers of that mansion, Cet'ingira (later "Mekeritrig",
"Traitor of Men") had arranged the theft. After the end of the Cûno-Inchoroi Wars,
Cet'ingira had been sent into the Golden Court of the Incû-Holoinas on the orders of
Nil'giccas. He returned sane and whole, but his companions who had accompanied him
had been driven mad and were put to death. However, it now appeared that Cet'ingira
had subtly surrendered his allegiance to the Inchoroi, two of whom had - somehow -
survived the twenty-year purge of the Ark. Cet'ingira delivered the Heron Spear to the
Ark and arranged for it to be hidden in its environs (the interior remained barred from
entry). In 777 Cet'ingira set about the corruption of the School of Mangaecca, revealing
to them the existence of the Golden Ark and the Inchoroi. Over the following
centuries the Mangaecca raised great fortifications about the Golden Ark as they
attempted to penetrate Emilidis’s Barricades, to no avail.

In 809 the great river town of Cenei was founded on the Kyranae Plains, soon
establishing itself as the greatest Ketyai power north of Shigek. Just two years later the
great kingdom of Akksersia was founded on the northern shores of the Sea of Cerish,
with its capital at Myclai.

The nations and city-states of Eärwa circa 1110 Year-of-the-Tusk.

In 825 the Nonman Tutelage ended with a crime most foul, a rape committed by the
Siqû Jiricet against Anasûrimbor Omindalea, the daughter of Sanna-Neorjë, a ruling
noble of the Ûmeri Empire. When Ishoriöl refused to hand over Jiricet for trial, the
Empire expelled all Cûnuroi from within its borders and ended the alliance.
Omindalea would die bearing Jiricet's son, Anasûrimbor Sanna-Jephera, known as
"Twoheart". Holding the child blameless for the sins of his father, Sanna-Neorjë made
Sanna-Jephera his heir, resulting in the extreme longevity of many of his line.

By 850 Akksersia had sent colonists across the Sea of Cerish, founding the city of
Kelmeöl on the southern shores of the sea. The people of this region soon became
known as the Meöri. By 1104 the single city-state had expanded into the Meöri (or
Meörn) Empire, extending south to the River Wernma.

In 917 the Ûmeri Empire collapsed, overrun by the Cond tribesmen of Aulyanau the
Conqueror. This led to a second period of domination over the Aumris Valley by
Trysë. In 927 the Cond conquered Atrithau and settled several tribes in the region.

Shaeönanra, Grandmaster of the Mangaecca and the reviled leader of the Unholy Consult, is confronted
by Titirga, Grandmaster of the Sohonc, in 1119. Titirga wields the fabled Diurnal, the mighty Day
Lantern crafted by the Nonman Emilidis thousands of years earlier.

In the second half of the 11 th Century (some say 1086 but this would make him far
younger than he is oft-depicted) Shaeönanra was born in Ûmerau. He was the son of a
treasurer and showed tremendous aptitude for sorcery. He was taken in by the
Mangaecca and became the school's most promising student. By 1111 he had already
become the Grandvizier of the Mangaecca and had learned forbidden knowledge about
the Incû-Holoinas. Aided by the Cûnuroi traitor Cet'ingira, Shaeönanra set about
tearing down the glamour surrounding the Golden Ark, finally succeeding in
destroying it and making contact with the last two surviving Inchoroi, Aurax and
Aurang. In 1119 Shaeönanra and Aurang defeated Titirga, the Grandmaster of the
Sohonc and the most powerful sorcerer in history, after luring him into a trap in the
old Nonman mansion of Viri.

Shaeönanra, Cet’ingira and Aurang now formed an alliance, an Unholy Consult, with
the goal of finishing the job the Inchoroi had begun thousands of years earlier:
reducing the population of the World to 144,000 so it might be sealed shut against the
29Outside and ending the judgement of the heavens (and hells) on mortals, thus saving
their souls from eternal damnation.

In 1123 Shaeönanra announced to the world that he had discovered a means of saving
the souls of those damned by sorcery, utilising a secret hidden deep within the Ark, but
was promptly denounced for impiety. The Mangaecca were outlawed, fleeing Sauglish
for Golgotterath. For the next one thousand years they would attempt to bring about
the salvation they had promised.

By the end of the 13th Century Akksersia had become the most powerful Norsirai
nation, extending north from the Sea of Cerish onto the Plains of Gâl. At the same
time the city-state of Shir on the River Maurat had conquered the tribes of Set-Annaria
and founded new empire, Shiradi, trading with the Meöri to the north. However, the
Aumris Valley and the area around Atrithau had fallen under the yoke of the Scintya, a
new migratory tribe of Norsirai tribes. By 1381 Atrithau had liberated itself from the
Scintya and founded a new nation, Eämnor, which rapidly became one of the pre-
eminent powers of the Ancient North.

In 1408 Anasûrimbor Nanor-Ukkerja I, the Hammer of Heaven, defeated the Scintya
once and for all, driving them from the Aumris Valley in abject defeat. He then seized
the Ur-Throne in Trysë and declared himself the first High King of Kûniüri at the age
of just thirty. Kûniüri rapidly becomes the largest and most powerful empire of men in
Eärwa, extending north to the Yimaleti Mountains, east to the shores of the Cerish Sea,
south to Sakarpus and west to the Demua Mountains. Kûniüri was careful to maintain
good relations with Eämnor to the west, the Meörn Empire to the south-east and
Akksersia to the north-east. These four powers soon became immensely rich on trade
and cooperation, particularly against the Sranc who had begun to trouble the North in
worrying numbers (the Great Sranc Wars of the 13 th Century are now largely believed
to have been the work of the Consult, seeking to control the former servants of the
Inchoroi with mixed results).

Anasûrimbor Nanor-Ukkerja I died in 1556 at the age of 178, his long life the result of
Nonman blood in his veins. Upon his death, he divided the empire between his sons,
creating Aörsi (in the north, between the Neleöst Sea and the Yimaleti Mountains) and
Sheneor (in the east, between the seas of Neleöst and Cerish) in addition to Kûniüri
itself.

In the 15th Century, the Shiradi Empire was conquered by Xiuhianni invaders from
Eänna, who had crossed the southern Kayarsus in the vicinity of Jekhia. The city of Shir
was destroyed, but the imperial dynasty was able to relocate to Aöknyssus and, after
twenty years of warfare, managed to defeat the Eännan invaders. By 1800 the Shiradi
Empire had been firmly re-established and bolstered by the presence of the Surartu, an
Anagogic school of sorcerers (and forerunners of the modern Scarlet Spires) based at
the river fortress of Kiz in the city of Carythusal.

In 1591 the long, uneasy period of dominance by Shigek over the Kyranae Plains came
to an end. The Shigeki Empire had spent centuries gradually being sapped by internal
rebellions and clashes with Nilnamesh far to the south, particularly by Nilnamesh's
attempts to colonise the Middle-Lands of Amoteu on the Three Seas between their
empires. The native Kyranae plainsfolk managed to overthrow and defeat Shigek at the
Battle of Narakit. This was a precursor to the rise of the kingdom of Kyraneas itself,
with its capital originally at Parninas but later at Mehtsonc. Kyraneas defeated and
conquered both Shigek and Amoteu, forming a large empire stretching south along the
western coast of the Three Seas.

In 1896 Ajencis, who would soon be famed as the father of syllogistic logic and algebra,
as well as a philosopher of repute, was born in Mehtsonc. He would die in 2000, at the
age of 103, having written Theophysics , The First Analytic of Men and The Third
Analytic of Men, three of the greatest works of human knowledge and philosophy.

This was the age of great men, of warring cities and clashing empires. The lives of
humans were brief but passionate, the rapid rise and fall of empires likely bewildering
to the long-lived and slower-burning Cûnuroi. But there were also signs of growing
31maturity, with men like Ajencis (and his philosophical Kûniüri sparring-partner,
Ingoswitu) seeking true wisdom and larger, more stable nations forming such as
Kûniüri, based more around trade than warfare. What would have become of the great,
vast civilisation of the Ancient North and its neighbours in the Three Seas is fascinating
to speculate, but events meant that this was not to be.

In 2089 Anasûrimbor Celmomas II, the High King of Kûniüri, was born. In the exact
same year was born Seswatha, the son of Trysëan bronzesmith. These two men would
stand history upon its end, for they were fated to live in the time of the Apocalypse.

The nations and city-states of Eärwa circa 2089 Year-of-the-Tusk, on the eve of the Apocalypse.
