# Part 3: The Apocalypse

The man known to history as Seswatha and to the Sranc as "Chigra", "Slaying Light",
was born in Year-of-the-Tusk 2089 in Trysë, the son of a caste-menial bronzesmith.
Whilst still a child, he was identified as one of the Few, those that carry the Mark of
sorcery. He was taken to Sauglish to study with the Gnostic School of Sohonc, at the
time the largest and most powerful of the dozen or so sorcerous schools of the Ancient
North. Seswatha was a prodigy, his grasp of the Gnosis subtle and strong. Circa 2104,
at the age of fifteen, Seswatha would be proclaimed a sorcerer-of-rank, the youngest in
the School's history.

During this period Seswatha befriended Anasûrimbor Celmomas, the heir to the
imperial throne of Kûniüri who was studying with the Sohonc. The same age as
Seswatha and both intrigued by history, they became fast friends and allies. As Seswatha
grew in power and might through the ranks of the Sohonc, so Celmomas became
33famed as a warrior, general and scholar. Their great friendship was tested, however,
when Celmomas's most beloved wife Suriala (variously translated as Suiyela) gave birth
to their son Nau-Cayûti. Celmomas knew that Seswatha and Suriala shared a mutual
affection and became concerned that Nau-Cayûti was not of his blood. But such was his
love for his friend - and his inability to conclusively prove the truth of the matter - that
he did not have him publicly rebuked, merely withdrawing his friendship for a time.
Seswatha knew the truth, that Nau-Cayûti was his son, the result of a tryst with the
Queen while her husband lay in a drunken stupor in the King-Temple of Trysë.

Seswatha was a master sorcerer but also a keen politician. He befriended Anaxophus, a
young prince of Kyraneas, and treated with Nil'giccas, the Nonman King of
Ishterebinth (the "Exalted Stronghold"), as Ishoriöl was now more frequently called.
Seswatha's insights were keen, his mind sharp, his sorcery formidable and his manner
one of ease, all attributes that saw him rise to become Grandmaster of the Sohonc in
his early thirties.

What happened next remains a matter of great debate. According to legend and The
Sagas , Seswatha received a delegation of Nonmen Siqû in Sauglish. Although the
Nonmen Tutelage was not reinstated, Seswatha had nevertheless forged closer ties with
Ishterebinth than had been seen since those times. According to some accounts,
Nil'giccas rewarded Seswatha's friendship with intelligence which was not so much
disquieting as alarming.

It had been long known that the School of Mangaecca had fled Sauglish to seek refuge
in Golgotterath. Its dark leader, Shaeönanra, survived thanks to Inchoroi knowledge
and his own sorcerous research. By the 14th Century, he had even been given a new
name: Shauriatas, "Cheater of Gods". The Mangaecca had not been seen since, but
their hand, and that of their Inchoroi overlords, was suspected in the Great Sranc
Wars, a series of strikes by hordes of Sranc out of Agongorea against Aörsi to the east
which had sorely tested that nation and led to the construction of a major stronghold,
Dagliash, on the Urokkas (in fact, atop the very ruins of ancient Viri). But in those days
Sranc were not a numerous, constant threat blanketing the North. They were mostly
34confined to Agongorea and the Yimaleti Mountains, and although their numbers were
concerning, they were not as inexhaustible as in later centuries. Or so it was supposed.

The Siqû warning was stark: the Mangaecca yet lived within the golden halls of the Ark
and they had formed a forsaken alliance - an Unholy Consult - with the surviving
Inchoroi princes. Worse still, their delvings and explorations of the Ark had uncovered
ancient secrets and disturbing ways of using the Tekne, the ancient art of science and
engineering that the Inchoroi had once employed to create weapons such as their staffs
of light and creatures such as the Wracu and Sranc, but had seemed to lose more and
more knowledge of with every passing year.

The Siqû warning convinced Seswatha that a threat was building in the pits of
Golgotterath and that, left unchecked, it would eventually destroy the world. This
threat was given a name by the Nonmen, one that Seswatha held close and only told
those closest to him: No-God.

The origin of this intelligence is unknown: some Mandate commentators suggest that
the Consult deliberately informed the Sohonc of the threat to trigger the very war that
now resulted, whilst others suggested that Consult traitors let the knowledge slip. But
given that all collaborators of the Consult were taken before the Inverse Fire and none
beheld its flames without breaking, this seems unlikely.
Whatever its origin, Seswatha took this knowledge to his old friend, who now ruled as
Anasûrimbor Celmomas II, High King of Kûniüri, the greatest nation in all Eärwa.
Celmomas may have been inclined to distrust his old friend for the alleged betrayal
with his wife, but he also respected his judgement. In the end, Celmomas was
convinced that Golgotterath remained a threat to the world and that threat needed to
be destroyed before it could unleash a horror that would bring about the end of
everything.

35The opening battles of the Apocalypse: 1. Sursa (2125). 2. The Great Investiture (2125-32). 3. Dagliash
(2133). 4. The Burning of the White Ships in Aesorea (2134). 5. Shiarau (2136).

In Year-of-the-Tusk 2123, Anasûrimbor Celmomas II called for the Great Ordeal, the
assembling of a vast host of armed and sorcerous might to be cast at Golgotterath, to
bring down and destroy the threat of the Consult and the Inchoroi once and for all.
Aörsi, which lay in the shadow of the Golden Ark and had suffered most from their
depredations, rallied to the call almost immediately, King Anasûrimbor Nimeric
contributing many tens of thousands of warriors already hardened in battle against
Sranc and Bashrags and the use of his fleet for transport and resupply. Nil'giccas sent
Qûya mages and Ishroi warriors from Ishterebinth, and Kyraneas sent a detachment of
troops, reflecting Seswatha's friendship with Prince Anaxophus (the prince himself was
still only fourteen, and it is unclear if he took part in the Ordeal at such an early age or
had returned to Kyraneas).

In 2124, the Great Ordeal crossed onto the plains of Agongorea but was engaged by a
host of Sranc and Bashrags. The resulting battle was indecisive and the Ordeal
withdrew across the Sursa to winter in Dagliash. Celmomas renewed the offensive in
the early spring, fording the Sursa before the Consult could prepare a defence. They
were forced to retreat to Golgotterath and allow the Ordeal to encircle it. The Great
Investiture lasted for six years but failed to starve the Consult into surrender.

36This period was marked by squabbling and petty jealousies erupting between the
commanders of the Ordeal, along with military disagreements on how to proceed. The
Investiture was complete, but the Consult seemed able to resupply at will. The Ark was
too well-defended for any conventional assault to succeed, and the Consult mages were
capable of resisting even the combined might of the Qûya and Sohonc. At one stage, in
the Great Chorae Hail, the Sohonc lost a third of their number in an ill-advised assault
ordered by Celmomas. Seswatha’s reputation and leadership were tested but he
remained in command of the sorcerers in the Ordeal. In 2131, a more serious dispute
erupted between Celmomas and Nimeric, resulting in Celmomas withdrawing the
Kûniüri contingent of the Ordeal, to the disbelief of Seswatha.

A Gnostic sorcerer battles a Wracu of Golgotterath.

A year later the Consult went on the offensive. Employing passages reaching under the
Black Furnace Plain and into the Ring Mountains, the Consult launched devastating
assaults into the Ordeal's rear and flanks. Much-reduced by the absence of the Kûniüri
forces, the Ordeal's army almost collapsed. Qûya and Sohonc sorcery allowed at least a
small part of the army to escape, but Nil'giccas was so enraged to learn of the deaths of
at least two of his sons that he recalled the Cûnuroi contingent of the Ordeal
altogether, leaving Aörsi to fight on alone.

In 2133 Dagliash was taken by the Consult, allowing their armies to cross the Sursa in
force. Western Aörsi was overrun and Nimeric withdrew his forces to his capital,
37Shiarau. Celmomas realised his folly and rallied Kûniüri to rejoin the war in 2134, but
it was too late. The Aörsi fleet fled across the Neleöst to seek shelter in the Kûniüri port
of Aesorea, where it was promptly destroyed by enemy agents in the event known as the
Burning of the White Ships.

In 2135 Nimeric took a mortal wound during the Battle of Hamuir, dying soon
afterwards. In the spring of 2136 Shiarau fell, and with it Aörsi itself. Kûniüri stood
alone.

The latter course of the Apocalypse: 6. Ossirish (2137). 7. Shiarau (2137). 8. Dagliash (2139). 9. The
Second Investiture, ending in Initiation (2142-43). 10. The Fields of Eleneöt (2146). 11. Trysë (2147). 12.
Sauglish (2147). 13. Eämnor (2148). 14. The Fords of Tywanrae (2149). 15. Kelmeöl (2150). 16. Inweära
(2151). 17. Kathol Pass (2151). 18. Cil-Aujas (2152). 19. Shir (2153). 20. Sumna (2154). 21. Mehtsonc
(2154). 22. Mengedda (2155).

The situation seemed bleak, but in 2137 Anasûrimbor Nau-Cayûti, Prince of Kûniüri,
won a stunning victory over the Consult at the Battle of Ossirish. The armies of
Kûniüri had been hard-pressed by a Consult offensive, but Nau-Cayûti rallied his men
38by facing and slaughtering the Wracu Tanhafut the Red in direct combat, a feat
undreamt of since the Cûno-Inchoroi Wars. Nau-Cayûti then led the victorious army to
rout the Consult at the ruins of Shiarau, driving the remnants back across the Sursa by
the end of 2138. In 2139 he recaptured Dagliash before launching several major raids
across Agongorea, designed not to reinvest Golgotterath but simply slaughter Sranc and
Bashrags.

In 2140, the Consult abruptly switched tacks and kidnapped Aulisi, the beloved
concubine of Nau-Cayûti, bearing her to Golgotterath. Infuriated, Nau-Cayûti may
have decided on a rash assault (possibly the rationale for the act) but was talked down
by Seswatha. Seswatha proposed something else instead: a raid on the Incû-Holoinas,
such as that undertaken by some of the Nonman heroes of old. Seswatha had studied
among the Nonmen of Ishoriöl, donning the famed (and feared) cauldron-helm
Amiolas to gain knowledge that would permit such a raid to succeed. Many historians
consider the story of the raid that followed as being apocryphal due to sheer
unbelievability, but Seswatha's descendants in the School of Mandate have confirmed
(thanks to their sorcerous ability to relive Seswatha's life) that it is true.

Nau-Cayûti and Seswatha entered the Golden Ark, descending through chambers and
passageways that had supposedly been desolate and empty for thousands of years, since
the Cûnuroi had sacked the vessel from top to bottom. But, deep in the vessel's
cavernous hold, they did find a city of horrors, guarded by Sranc and Bashrags. They
failed to find any trace of Aulisi but they did find something that abruptly changed the
fortunes of the war: Suörgil, the Shining Death, the Heron Spear itself.

"I lied. Because I couldn't succeed, not alone. Because what we do here is more
important than truth or love. We search. We search for the Heron Spear."
- Seswatha ( The Thousandfold Thought )

They bore the weapon back to Sauglish in great triumph, but this turned sour when
Nau-Cayûti died soon after, allegedly poisoned by his wife Iëva (some say out of jealousy
over Nau-Cayûti's infatuation with Aulisi, and the fear the other woman would
39supplant her). Iëva insisted on Nau-Cayûti being buried rather than burned, as this had
been his wish during life, although many of his family and comrades did not remember
him mentioning such a desire. But out of respect for his widow, they complied. Some
garbled reports from the time state that Consult agents later defiled the grave of Nau-
Cayûti and destroyed or stole his corpse, which seems a dangerous risk to take for petty
vengeance.

The Consult resumed the offensive in 2141, perhaps hoping for a loss of Kûniüri
morale following Nau-Cayûti's death. This hope proved false. General En-Kaujalau
destroyed a Sranc horde at the Battle of Skothera. In 2142, General Sag-Marmau
inflicted a very serious and debilitating defeat on the Consult (according to some
legends, Aurang himself took the field but was forced to withdraw) and again drove
them back to the Ark itself. Anasûrimbor Celmomas II began the Second Investiture in
the fall of that year, unaware that the Consult themselves were now playing for time as,
deep within the halls of the Ark, their millennial plan now reached its culmination.

An artistic interpretation of the Carapace in the depths of the Ark.

Something happened, an event second only to the original Arkfall in importance and
dread.

To this day no-one knows exactly when transpired, save that in the pits of Golgotterath
the Consult finally achieved what they had been attempting to do for a thousand years,
sparking the very warnings that had led to the Ordeal in the first place. They completed
the construction of the Carapace, a sarcophagus of Tekne origin, fused with eleven
Chorae to render it immune to sorcery. Inside the Carapace they created - or unleashed
- an entity of supreme and terrible power. This entity went by many names: Tsurumah
("Hated One" in Kyranean), Lokung ("Dead-God", by the Scylvendi), Mursiris ("Wicked
North", by the Shiradi) and Cara-Sincurimoi ("Angel of Endless Hunger", by the
41Nonmen), as well as the Great Ruiner and World-Breaker. But his most famous title
was the one first bestowed upon him: Mog-Pharau in Ancient Kûniüric, "No-God".

The No-God first drew breath in the spring of the Year-of-the-Tusk 2143 in the event
known to the Consult as “Initiation”. The Carapace emerged from the dread Ark,
floating above the ground. Gusts of wind started to form around the Object, quickly
becoming first a gale and then a roaring whirlwind. Upon the instant of Initiation,
every unborn child in the world was stillborn, beginning the horror known as the Years
of the Crib. A "feeling of dread" fell across all of humanity, drawing their eyes to the
northern horizon. Sranc, Bashrag and Wracu, including some who had escaped taking
part in the wars so far, were compelled to answer his call and descend on the Black
Furnace Plain and Golgotterath in numbers beyond counting, a horde which blanketed
the horizon.

The host of General Sag-Marmau was destroyed utterly. But the Horde of the No-God
did not march immediately, instead waiting as vast hosts of Sranc gathered and bred.
This gave Kûniüri a very brief space in which to cry for aid. Eärwa answered, the armies
of Ishterebinth marching under Nil'giccas and Kyraneas sending a significant army to
lend aid. Other nations, more distant, began to muster but the distances were too great
and time ran out.

Anasûrimbor Celmomas II led the so-called Second Ordeal into battle against the
Horde of the No-God on the Fields of Eleneöt, which in earlier millennia had been
called Pir Pahal, in 2146. The Horde engulfed the Kûniüri army. Celmomas knew the
only hope was to use the Heron Spear against the No-God. However, although the vast
Whirlwind that symbolised the No-God's presence gathered on the far horizon, the
entity itself refused to give battle, letting its vast army of minions do the work for it.
Celmomas is said to have thrown himself into battle with a rare fury and slain dozens
of enemies, only to be mortally wounded. Seswatha led a rallying force to retrieve the
High King, who lived long enough to impart a prophecy: that an Anasûrimbor would
return at the end of the world. Then he died.

"Did I ever tell you that my son once stole into the deepest pits of Golgotterath? How I
miss him, Seswatha! How I yearn to stand at his side once again. I see him so clearly.
He's taken the sun as his charger, and he rides among us. I see him! Galloping through
the hearts of my people, stirring them to wonder and fury! He says such sweet things to
give me comfort. He says that one of my seed will return, Seswatha. An Anasûrimbor
will return at the end of the world!"

- Anasûrimbor Celmomas II ( The Darkness That Comes Before )

Elsewhere on the battlefield, his heir Anasûrimbor Ganrelka outlived him, becoming
the High King of Kûniüri. According to popular legend, Ganrelka also died on the
Eleneöt Fields, but in reality, he survived thanks to four brave Knights of Trysë.
Ganrelka escaped home, gathered his household, and marched west into the Demua
Mountains. In the remotest peaks, protected by both geography and utter secrecy, the
Kûniüri High Kings had built a stronghold and a shelter, Ishuäl. Ganrelka took up
residence of there, but disease followed and wiped out most of the family...save for
Ganrelka's bastard son, the last living son of House Anasûrimbor. He and his line fell
out of history for two thousand years.

43The Sarcophagus of the No-God, protected by the ever-present Whirlwind.

By the end of 2147 all of Kûniüri was overrun. The great river-cities of the Aumris
Valley were obliterated: Trysë, Ûmerau and Sauglish itself, with its famed library. The
Nonmen of Ishterebinth retreated over the Demua Mountains to their Mansion. The
Horde of the No-God pursued, laying siege to the Exalted Mansion for two years. The
Mansion shut its famed inner gate, reinforced from material harvested from the Ark in
millennia past, and neither the No-God nor even the fabled Sun Lance of Aurang (the
last functioning Inchoroi spear of light, save the Heron Spear) could gain entry.
Repulsed, the No-God turned south and destroyed Eämnor (although sparing its
capital, Atrithau, due to the complications of attacking a city raised on anarcane
ground and thus immune to sorcery) in 2148. Abandoning the siege of Ishterebinth,
the remainder of the Horde destroyed Akksersia in 2149 (after the Battle of Tywanrae
Fords), and the Meörn Empire collapsed in 2150, despite a hardy defence. Inweära was
cast down in 2151, although the Horde chose to avoid Sakarpus and its vast Chorae
44Hoard to instead rush the Kathol Pass - the gateway to the entire Three Seas - before it
could be fortified.

The Battle of Kathol Pass, fought in the autumn of 2151, was an unexpected victory for
the forces of men. A retreating army of Meöri warriors led by Nostol ran into an
advancing force of Nonmen out of Cil-Aujas, led by King Gin'yursis, a powerful wielder
of the Gnosis. They made common cause and successfully repulsed several waves of
attacks from the Horde on the pass. Shockingly, the Meöri turned on and betrayed the
Nonmen, slaughtering their army and then sacking Cil-Aujas. The reasons for this are
unclear, but may be related to the rising levels of religious fervour amongst the Norsirai
refugees (perhaps hoping that the Hundred Gods would intercede and destroy the No-
God for them), who hoped that by staying true to the teachings of the Tusk – including
the commandment to destroy the False Men – they could invoke the protection of the
Gods. It is also possible that the Meöri believed they could use Cil-Aujas as a refuge
should the No-God advance further south. Gin'yursis's death saw him curse the Meöri
for their betrayal, a curse sometimes used to explain the famous fractiousness of the
men of Galeoth (founded by the Meöri descendants), although Gin’yursis’s curse had
in fact been directed at all mankind.

During this period, the populous and packed cities of the south cried out for succour
and divine intervention. They prayed to the Hundred Gods, but received no reply. The
people begged their priests to explain why the Hundred had not interceded and the
priests could not answer. Many years later, confused records of this time suggest that
the priests had in fact petitioned for help and gotten only bizarre responses: the Gods
could not see or feel the presence of the No-God, only the destruction that followed in
his wake, which they blamed solely on humanity itself. The Hundred could not
intervene because they could not even perceive the problem in the first place, and it
may be that that this nullification of divine perception is one of the reasons the No-
God was named as such. Humanity stood alone.

In 2153, the Horde of the No-God destroyed the Shiradi Empire at the Battle of
Nurubal, plunging the empire into chaos and collapse. It then turned west to invade
45Kyraneas. Anaxophus, Seswatha's old friend now ruling as King Anaxophus V, led his
nation with skill and cunning. The Scylvendi, the long-established pastoralists living
beyond the mountains to the north-west, had unexpectedly declared for the No-God
and invaded Kyraneas's flank, threatening to trap the kingdom in a vice at the Battle of
Mehsarunath. Anaxophus evaded the trap and escaped to the south. He chose not to
defend either the royal capital at Mehtsonc or the holy city of Sumna (from where the
Holy Tusk was evacuated by sea to Nilnamesh) instead choosing to fight a war of
irritation and attrition, testing the flanks of the No-God's horde and withdrawing when
the enemy attempted to respond.

Kyraneas was effectively overrun and destroyed by the end of 2154. But Anaxophus V
and his army, now aided by Seswatha and the remnants of the Gnostic Schools,
survived. They withdrew through the mountains to the ruined, ancient city of
Mengedda. The city had once been a trading post between Shigek and the cities of the
Kyraneas Plains when the age of man was young, but innumerable battles had been
fought then over the past two thousand years. The blasted landscape and ruins
provided Anaxophus and his army with cover and defences. More importantly, the
long, attritional warfare favoured by Anaxophus had helped reduce the size of the
Horde to one where victory by sheer weight of numbers was no longer certain.

Anaxophus's gamble worked: to ensure victory and the destruction of the last enemy
who might be any threat, the No-God took the field directly, the terrible Whirlwind
moving towards the Kyranean lines and declaring, as it had done all along, "WHAT
DO YOU SEE?" This allowed Anaxophus to do what he had been planning ever since
his knights had seized the Heron Spear from the Fields of Eleneöt eleven years
previously: he used the weapon directly against the No-God.

Aided by Seswatha, King Anaxophus V of Kyraneas uses the Heron Spear against the No-God.

As the Apocalypse began in doubt and uncertainty, so it ended with a clear victory. The
Whirlwind burst asunder, the No-God was destroyed and his armies were routed.
According to some reports, the Carapace itself was reduced to ashes, ashes which were
carried by the winds to all the corners of the Three Seas where they caused the Indigo
Plague. However, Mandate scholars insist that the No-God's body (if it could be called
that) and the damaged Carapace were saved by Consult sorcerers and borne back to
Golgotterath.

The end of the war was draped in controversy, for the knowledge that Anaxophus had
stolen the Heron Spear and kept it secret for a decade as the Ancient North and the
Shiradi Empire (Kyraneas's great rival to the east) were overrun and destroyed did not
endear him as the saviour of mankind, as perhaps should have been the case. However,
Anaxophus claimed that the disaster of the Eleneöt Fields had happened because the
Heron Spear had been deployed prematurely before the No-God had engaged, and that
he had no choice but to wait - no matter the cost - for the No-God to show himself
before he could risk using the weapon. This tactical claim has been supported -
although not altogether wholeheartedly - by the Mandate.

Another, more minor debate has also taken place in the centuries since the defeat of
the enemy: due to the No-God’s very presence in the World inhibiting procreation,
47more than a few commentators have pointed out that the Consult had no need to go
on the offensive. Instead, the Consult could have simply had the Whirlwind raging in
the shadow of Golgotterath (or, to avoid counter-attacks, in even more remote corners
of the World) and, after a century or so, the human population of Eärwa would have
been extinguished. Mandate commentators have countered by suggesting that either the
No-God could not be entirely controlled once unleashed, or the weapon had a finite
lifespan. No conclusive answer has been provided for this quandary.

The end of the war resulted in the infamous Indigo Plague, which caused great misery
and suffering around the Three Seas, but also in a regrouping of civilisation. Seswatha
gathered together the few surviving Gnostic sorcerers and founded the School of
Mandate, based at the fortress of Atyersus on an island in the middle of the Three Seas.
Seswatha knew that the No-God had been destroyed and the Consult defeated, but the
Inchoroi Princes yet lived, the Consult sorcerers yet survived and the hordes of Sranc
and Bashrags (and even a few surviving Wracu) had only dispersed. But most damning
of all was the prophecy given to Seswatha by his friend and ally Celmomas at the
moment of his death:

“An Anasûrimbor will return at the end of the world!" - The last words and prophecy of
Anasûrimbor Celmomas II ( The Darkness That Comes Before )

The First Apocalypse was over. Now the Mandate had to prepare humanity for the Second.
