# Part 4: The Age of Warring States

The Apocalypse destroyed the civilisation of the Ancient North. Two great cities,
Atrithau and Sakarpus, had survived but otherwise all of the glories of the Norsirai had
been lost and the surviving remnants of that once-great people pushed south into the
Three Seas. Attempts to found new cities and settlements in the north foundered
under vast numbers of Sranc. Leaderless and without direction, they continued
breeding, raiding and rampaging. With a truly vast amount of terrain to range freely
across, almost the entire northern half of the continent, their breeding could not be
controlled and within a few centuries their numbers were beyond calculation.
Fortunately, they showed no appetite for a concerted push into the Three Seas.

The borders of the Ceneian Empire after each major conquest: Gielgath (2349), Cepalor (c. 2390),
Shigek (2397), Xerash and Amoteu (2414), Nilnamesh (2483), Cingulat (2484), Amarah (2485), Cironj
(2508), Nron (2511), Ainon (2518), Cengemis (2519) and Annand (2525). The latter conquests were
carried out by Triamis I, the Great, the first Aspect-Emperor of the Three Seas (2456-2577).

The fall of the No-God at the battlefield of Mengedda spelt the end of the Consult's
plan to destroy the world, but not the Consult themselves. They retreated - according to
some, taking the No-God's Carapace with them - and sought refuge in Golgotterath.

49With initially thousands and later millions of Sranc infesting all the lands between the
Three Seas and the Yimaleti Mountains, the victorious armies of Kyraneas and their
sorcerous allies were unable to pursue. The ravages of the Indigo Plague of 2157 soon
exhausted what was left of Ketyai strength, already pushed to breaking point by decades
of warfare and accompanied by the death of Anaxophus V shortly after the end of the
war, led to the collapse of Kyraneas.

Seswatha survived the Apocalypse, in fact living until 2168 when he died at the age of
79. Shortly after the end of the Apocalypse, with the School of Sehonc effectively
destroyed, he founded the Gnostic School of Mandate, based in the fortress of Atyersus
on the island of Nron. A year later he founded Attrempus on the mainland to the
north-east. Fearing that his successors would forget the lessons of the Apocalypse,
Seswatha underwent a sorcerous ritual upon his death. His heart was extracted from his
body and placed in a chamber in Atyersus. Every Mandate schoolman, upon joining the
organisation, would undergo a ritual known as the Grasping. This ritual would transfer
Seswatha's memories to him. Every night he would dream the details of Seswatha's life,
the great battles, the descent into Golgotterath, the preparations for the Apocalypse
and the final battle with the No-God. In this way, the knowledge and fear of the
Consult would live on. The Mandate scoured the Three Seas searching for Consult
agents, occasionally exposing and destroying them. But for the most part the Consult
seemed willing to remain in hiding in far Golgotterath.

Although the Ancient North and the northern Three Seas had been ravaged by the No-
God, the southern nations remained untouched by the war. Amoteu, Shigek and
Nilnamesh soon proved resurgent and the refounded city-states of the Kyranae Plains
fell into internecine warfare, beginning the Age of Warring Cities (lasting
approximately from 2158 to 2477 Year-of-the-Tusk). This period may well have seen a
relapse into barbarism had not humanity found a new saviour.

Inri Sejenus, known to history as the Latter Prophet, was born in 2159. At a young age,
he claimed to be the pure incarnation of the Absolute Spirit ("the very proportion of
the God") and to have been sent to amend the teachings of the Tusk. He argued for a
50fairer world and a willingness to embrace God in His singular aspect as well as that of
the Hundred. The extant Kiünnat sects at first dismissed Sejenus as a fringe
philosopher, but as he got older he attracted vast followings. His teachings were widely
disseminated and his popularity boomed. In 2198 Sejenus was arrested and sentenced
to death by King Shikol of Xerash. In 2202 the execution was carried out and Sejenus
was put to death outside the city of Shimeh, in what had been Amoteu (at that point a
subservient nation to Xerash). However, the King himself then died and it was said by
the faithful the Sejenus returned to life and ascended to the Nail of Heaven from the
temple at Kyudea, outside Shimeh (alternate stories say it was from Shimeh itself).

Sejenus's movement, Inrithism, slowly spread throughout the Three Seas. It was fought
against by the Kiünnat cults, but soon become irresistible. A framework was set up that
disseminated the teachings of Sejenus, The Tractate , through sub-temples worshipping
the Hundred. This became the Thousand Temples, with a single leader, the Shriah, at
its head. Although Shimeh was the holiest city in Inrithism for the martyrdom of
Sejenus, the presence of the Tusk led to the religion basing itself in Sumna (to where
the Tusk had been returned following the No-God's defeat), which capitulated in 2469.
In 2505, the religion gained official recognition as the state religion of the Ceneian
Empire, which by that point had become the pre-eminent power of Eärwa.

Cenei had been founded over a thousand years earlier, but had spent most of its
existence as a modest river town on the Phayus, the greatest river of the fertile Kyranae
Plains. The destruction of Mehtsonc during the Apocalypse had been carried out with
such thoroughness that the ruins were deemed uninhabitable, and over successive
generations downriver Cenei instead absorbed a lot of the returning refugees. The city
grew in size and power, and when the Age of Warring Cities began it was well-placed to
fight both defensively and offensively. In 2349, it captured Gielgath, at the mouth of
the Shaul, effectively giving it control over the intervening southern Kyranae Plains.
Xercallas II completed the reconquest of Kyraneas and his successors conquered
Cepalor in the north (inhabited by the descendants of Norsirai refugees) and then
Shigek to the south by 2397.

The root of Ceneian success was the Imperial Army, which was thoroughly well-trained
and formidably equipped. The organisation of the army, its ability to absorb recruits
from newly-conquered provinces and its willingness to change tactics resulted in a
military force arguably unmatched before or since in Eärwa. The Imperial Navy was
likewise impressively-organised. Between 2397 and 2414 the two institutions would
combine to outflank the Carathay Desert and deliver a series of raids and then
conquests in Enathpaneah, Xerash and Amoteu, capturing the Holy City of Shimeh
along the way. General Naxentas, who delivered this stunning victory, declared himself
the first Emperor of Cenei. He would be assassinated within the year, but his successors
built on his achievements.

Triamis I became Emperor in 2478, beginning the Ceneian Golden Age. In 2483, he
conquered Nilnamesh, defeating King Sarnagiri V. The following year he invaded
Cingulat, on the far north-western coast of the continent of Kutnarmu. Triamis turned
west, leading his armies to the borders of Zeüm, the great Satyothi power of far western
Eärwa which had succeeded ancient Angka. He defeated a mighty host at the Battle of
Amarah and would have invaded but his homesick troops mutinied. He returned to
Cenei and consolidated his gains.

Returning home, he found the empire caught in a religious conflict between the
Kiünnat cults and Inrithism, which was threatening to spill over into outright war.
Triamis spoke to leaders on both sides, but found that Ekyannus III, Shriah of the
Thousand Temples, was both more reasonable and convincing as a religious leader. In
2502 Ekyannus instituted the "Emperor Cult" of the Thousand Temples and dubbed
Triamis the Aspect-Emperor of the Three Seas. In 2505 Triamis himself converted to
Inrithism, naming it the state religion of the Ceneian Empire. He then spent ten years
putting down religious rebellions whilst also concluding the conquests of the island
nations of Cironj (2508) and Nron (2511). Shortly afterwards he invaded the eastern
Three Seas, conquering the successor-nations of the old Shiradi Empire: Ainon (2518),
Cengemis (2519) and Annand (2525). For his achievements in conquering almost the
entire Three Seas, Triamis was dubbed "The Great".

Eärwa circa 3000 Year-of-the-Tusk, at the height of the Ceneian Empire. The Empire dominated the
continent for eight hundred years prior to its collapse in the 34 th Century. It was the largest and most
powerful nation-state in history, unrivalled until the rise of the New Empire of Anasûrimbor Kellhus a
thousand years later.

The following Aspect-Emperors would maintain the borders of the empire, keeping the
Ceneian Empire as the centre of political, military and religious power in Eärwa for
eight centuries. The weakness of the Ceneian Empire was not in its military strength,
but in its political succession, with brief but bloody civil wars often being the
mechanism for a transference of power. The constant instability eventually resulted in
the Empire growing lax and overconfident. In 3351 Cenei was sacked by the Scylvendi
under Horiötha King-of-Tribes, triggering the collapse of the empire. The destruction of
Cenei was brutal, with the city burned to the ground and all of its treasures, including
the Heron Spear, lost or stolen. The great fortress of Batathent was destroyed shortly
afterwards.

The final collapse is generally dated to 3372, when General Maurelta surrendered his
legions to Sarothesser I. Sarothesser had led the south-eastern part of the empire in
breaking away from Cenei. In this year, he ascended the Assurkamp Throne in
53Carythusal as the King of High Ainon. Cengemis and Nilnamesh also broke away,
spelling the end of the Ceneian Age. In 3374 Aöknyssus became the capital of a new
nation, Conriya.

By 3411 the port city of Momemn at the mouth of the Phaysus, had supplanted lost
Cenei as the pre-eminent city of the Kyranae Plains. Under the Trimus Dynasty
Momemn became the capital of Nansur, first a small kingdom and then (under the
succeeding Zerxei and Surmanate dynasties) a mighty empire, proclaiming itself the heir
to both Kyraneas and Cenei. By 3619 the Nansur Empire had conquered Shigek and
Amoteu but failed to expand those conquests into the eastern Three Seas, where the
power of High Ainon was unassailable. Later in the century Nansur and High Ainon
formed a brief military pact, perhaps planning to carve up the Three Seas between
them, but ultimately this idea foundered and the pact dissolved. In 3643 Norsirai
tribesmen living north-east of Nansur consolidated into the kingdom of Galeoth,
followed in 3742 by the founding of Ce Tydonn, which supplanted and replaced
Cengemis. In 3787 the Thunyeri, a robust warrior-people descended from the ancient
Meöri Empire, were displaced by growing numbers of Sranc from the lands south of the
Sea of Cerish, moving down the Wernma River and becoming raiders and pirates
which would trouble the Three Seas for two centuries before they consolidated as the
kingdom of Thunyerus in 3987.

The ambitions of Nansur to once again seize control of the Three Seas were thwarted
by a series of events along the fringes of the Great Carathay Desert. Fane, an Inrithi
priest living in Eumarna, was found guilty of heresy by the Thousand Temples in 3703
and cast into the Carathay Desert to die. Fane went blind in the desert, but also
experienced a series of religious insights and revelations. He emerged from the
southern sands wielding a power known as the Water of Indara, a form of sorcery both
unknown and alien to the Schools of the Three Seas. The Kianene, the raiders and
tribesfolk of the Great Salt, welcomed him amongst their ranks and listened to his
teachings. Fan'oukarji I, Fane's son, took those teachings and translated them into a
holy mission to destroy Inrithism, with the ultimate goal of casting down the Tusk (the
"Cursed Thorn" in their tradition).

54A Cishaurim sorcerer wielding the Water of Indara. Although still vulnerable to Chorae, Cishaurim are
not Marked as other sorcerers are and their presence cannot be felt by others of the Few. The reasons for
this remain unknown to the sorcerous schools of the Three Seas. The Water of Indara is believed to be
more powerful than most of the anagogic sorcery of the Three Seas, checked only by the Gnosis of the
Mandate.

The Kianene swept out of the desert in the so-called White Jihad (3743-71). The
Kianene armies were supported by followers of Fane who had also cast out their eyes
and gained the powers of the Water. They became known as the Cishaurim. As proof
of their righteousness, the Cishaurim showed that, unlike followers of the sorcerous
schools like the Mandate and the Scarlet Spires, they were not Marked. According to
some, they were not damned to an eternity of torment as other sorcerers were (although
this remains highly debated amongst some commentators). Their presence could not be
felt by other sorcerers, but Chorae were still anathema to them.

By 3771 the Kianene had conquered Mongilea and large portions of Eumarna,
founding a new capital at Nenciphon on the River Sweki, and converted the Girgashi
people of the desert to Fanimry. Kian had emerged as a powerful new player on the
shores of the Three Seas, although not one yet taken seriously by the Nansur Empire or
the Thousand Temples. In 3798 the Shriah, Ekyannus XIV, ordered the extermination
of the sorcerous schoolmen, declaring them to be unclear abominations. The Scholastic
Wars raged for the next eighteen years and saw several lesser schools destroyed.
However, it also provided the impetus for the Scarlet Spires to seize control of High
55Ainon, bringing the might of one of the great powers of the Three Seas under their
control. The Mandate survived a ten-year blockade and siege of Atyersus, although it
curtailed its mainland activities, and the Mysunsai "mercenary" school came into
existence. By 3818 the pogrom had been called off, but many sorcerers throughout the
northern Three Seas had lost their lives.

This, of course, reduced the ability of the Thousand Temples and the Nansur Empire
to resist the onslaught of the Kian and their Cishaurim. The rest of Eumarna fell in
3801, followed by Enathpaneah in 3842 and Xerash and Amoteu by 3845. The Sack of
Shimeh outraged both the Thousand Temples and all followers of Inrithism as a whole,
but there was no appetite for a counter-assault. The Kianene maintained the initiative.
In 3933 the Dagger Jihad of Fan'oukarji III saw both Shigek and Gedea fall to the
Kianene, bringing the borders of Kian to the very doorstep of Nansur. In the resulting
turmoil, the Surmante Dynasty was destroyed and replaced by the Ikurei family. The
Ikurei then reorganised the Nansur army and were able to defeat no less than three
Kianene invasions of the empire over the next several decades.

Meanwhile, the Mandate were facing mixed fortunes. Early in the 3900s they lost track
of the last Consult agents in the Three Seas. For three centuries, they scoured the lands
for any sign of the enemy, only to find that they had completely disappeared. This
disconcerting event was accompanied by a more positive one: House Nersei of Conriya
forged a strong alliance with the Mandate, accepting their schoolmen as tutors and
advisors. The Nersei dynasty used this advice to shore up their political support and
eventually take the throne of the kingdom. The Mandate also gifted their secondary
fortress of Attrempus to the Nersei family, giving them a strong bulwark to use against
possible attack.

Towards the end of the 41st Century the Three Seas were posed on a knife's edge.
Nansur had checked the advance of the Kianene Empire, but was unable to mount an
effective counter-offensive. The nations of the eastern Three Seas schemed as usual and
the sorcerous schools intrigued. The Mandate kept a watchful eye for the Consult, but
could find no trace of them anywhere.

56The beginnings of the road that led to the Holy War and the new Great Ordeal were
modest. In 4079 the Scylvendi leader of the Utemot tribe, Skiötha urs Hannut, died.
He was succeeded by his son, Cnaiür urs Skiötha, a warrior of tremendous repute for
savagery and intelligence. Cnaiür was advised by a strange man from the Ancient
North, from the lands beyond Atrithau which were believed to be completely lost to
Sranc. This man convinced Cnaiür to kill his father, having seduced his mother.
Afterwards he vanished into the southern deserts, to Cnaiür's fury and declarations of
vengeance.

This man was named Anasûrimbor Moënghus.

Eärwa circa 4109 Year-of-the-Tusk, on the eve of the Holy War and the arrival of Anasûrimbor Kellhus in the Three Seas.
