# Part 5: The Holy War

After the great disaster at Eleneöt Fields and the resulting fall of Kûniüri, the house of
Anasûrimbor was presumed destroyed and its line extinguished. But this was not so.
Anasûrimbor Ganrelka survived the disaster and managed to escape to Trysë. There he
gathered his household and retreated to Ishuäl, the stronghold that Celmomas II had
constructed high in the Demua Mountains as a last redoubt. After their arrival, a
sickness spread through the refugees and killed them all, one by one, until only
Ganrelka's bastard son and his court poet, a man of dubious repute, survived. The poet
was hurled to his death from the ramparts of the fortress by the young boy, but the
prospects for his survival were bleak. Only the arrival of more survivors saved him.

These survivors called themselves the Dûnyain. Their true origins are unknown, but
theorised to lie in the ascetic sects that arose across the Ancient North prior to the
Apocalypse, prioritising reason and intellect ahead of passion, sentiment or emotion.
They believed that true volition and control – a union with the Absolute – could only
come through the Logos, or reason unmarred by sentiment, and the ability to adapt to
circumstances rather than reacting to them or clinging to false precepts out of ideology
or obstinacy. Their primary belief was that if a person can master "what comes before",
they can control and predict all the outcomes that follow. Before the Apocalypse they
were, reluctantly, part of the world and its problems. But, fleeing the shadow of the No-
God, they stumbled across Ishuäl. Its utter isolation gave them a chance to fulfil what
they saw as their destiny.

Ishuäl, stronghold of the Dûnyain, hidden in an isolated valley of the Demua Mountains.

The Dûnyain and Ishuäl fell out of history for almost two thousand years. Left alone in
the high peaks, they continued to develop their skills of reading faces and voices and
developing the skills of pure reason. Things may have stayed that way, but in the 4070s
Year-of-the-Tusk they were discovered by a roving band of Sranc, unusually driven into
the high peaks. The Dûnyain destroyed these creatures, not knowing what they were
(having lost their own history along the way). Concerned that Ishuäl's location had
been compromised, they selected one of their number to go out into the world and
investigate. They chose Anasûrimbor Moënghus.

Moënghus's exploration of the outside world confirmed that Ishuäl remained safe, and
that the lands were filled with these ravaging Sranc for hundreds of miles in all
directions bar to the south, where a city of men known as Atrithau lay at the feet of the
Demua Mountains. The Dûnyain were satisfied that they were secure, but concerned
that Moënghus had been "polluted" by his contact with the outside world. He was
accordingly sentenced to die.

Moënghus, however, survived the execution order and fled into exile. He travelled
south, past Atrithau and across the Sranc-infested lands of Suskara to reach the Jiünati
Steppe. There, after surviving capture by a Sranc band (itself a remarkable fact), he was
in turn captured by the Utemot tribe of the Scylvendi and forced into servitude in the
household of Skiötha urs Hannut. Moënghus had soon seduced Skiötha's wife and
59turned his son Cnaiür against him. Cnaiür murdered his father, securing his leadership
of the Utemot, but Moënghus soon departed, disguised as a Scylvendi warrior. Cnaiür,
realising the depth of his betrayal, became enraged and vowed vengeance. Moënghus
passed south into the Kianene Empire – having scarred his arms and dyed his hair to
survive the Scylvendi lands but also making him unable to pass into the Nansurium -
but was again taken prisoner, this time to be sold into slavery.

Anasûrimbor Moënghus after blinding himself and becoming a Cisharuim, known as Mallahet. His lack of emotions and passion meant that he was unable to fully master the Water of Indara.

Again, Moënghus rose to a position of power and influence. He travelled to the Holy
City of Shimeh to learn the Psûkhe, the ways of channelling the Water of Indara, but
even after putting out his eyes he discovered that he was unable to use more than a
trickle of sorcery. Too late, he realised that the Psûkhe relied on passion to empower it,
the very trait the Dûnyain had bred out of themselves. However, in this process of
trying to master the Water he also trained his other senses to compensate. During a
discussion with one man, he noted many discrepancies in his manner of speech that
60could not be explained by simple lying or emotion. He subjected this man to torture
and eventually discovered the truth: the man was a "skin-spy", a creation of the Consult.
For three centuries, since the last Consult agent was publicly slain by the Mandate, the
Consult had infiltrated these creatures into positions of power across the Three Seas as
part of their plan to bring about the Second Apocalypse. Moënghus learned from the
skin-spy that the Consult believed they could resurrect the No-God and unleash the
end of the world in a matter of decades, at best.

Moënghus determined that the destruction of the world would not be an optimal
outcome for the Dûnyain struggling to master the Logos and it should be prevented.
He sent in motion a multi-pronged plan to this end. He had sired a number of children
by world-born women but all but one of them had shown significant defects,
abnormalities and mutations (the Dûnyain’s multi-millennial breeding efforts had
rendered them mostly incompatible with the rest of humanity). He had them all put to
death apart from the most promising: Maithanet. Although not a true Dûnyain,
Maithanet was intelligent and canny with considerable skills at manipulation, taught by
his father. Moënghus ordered him to enter the Thousand Temples in Sumna and rise
to a position of power and influence. Maithanet complied, within a matter of years
rising far through the religious orders thanks to his intellect, reason and expertly-
feigned religious fervour.

For three centuries, the Consult infiltrated the Three Seas through the use of their skin-spies, such as this one taking the appearance of Esmenet of Sumna. Undetectable to sorcery or mundane scrutiny, they
were defeated by Dûnyain analytic conditioning, which allowed them to be identified through
inconsistencies in their speech, as well as their skin and bone structure.

As Maithanet rose high in the ranks of the Temples, Moënghus used the little of the
Psûkhe he had mastered to send a Cant of Calling to Ishuäl. Speaking to the Dûnyain
in their dreams, he demanded that they send his son, Kellhus, to his side. The Dûnyain
debated and decided that Moënghus had gone insane and was a danger to the security
of their order. Anasûrimbor Kellhus was dispatched with a simple mission: to find and
kill Moënghus. The Dûnyain knew he dwelt in a distant city called Shimeh, but
nothing beyond that.

In the rest of the Three Seas, controversy had arisen around the rise of the hitherto
unknown Maithanet to the rank of Shriah of the Thousand Temples. Maithanet
exposed and defeated three plans to assassinate him, and using his considerable
charisma and power he soon had the fractious religious leaders of Inrithism unified as
they had not been in centuries. The leaders of the Mandate learned that Maithanet
planned to announce a Holy War, but they feared this would be directed against the
sorcerous schools. They ordered one of their number, a worldly agent called Drusas
Achamian, to travel to Sumna to investigate further.

62In Sumna Achamian reunited with his lover, a prostitute named Esmenet, as well as
several political allies and a former student-turned-informant, Inrau. Inrau was soon
murdered by agents of the Consult, sparking Achamian’s paranoia that the Consult
survived and yet remained a threat. The Three Seas awaited the news of the Holy War's
target and all were relieved to learn that it was to be directed against the heathen Fanim
of Kian. As thousands of warriors from across the northern and eastern Three Seas
converged on the Nansur Empire, which guarded the frontier with Kian, a shocking
alliance was announced: the Thousand Temples had forged an agreement with the
Scarlet Spires, the sorcerous rulers of High Ainon, to provide a counterbalance to the
Fanim Cishaurim (with whom the Spires had been fighting a secret war for a dozen
years). These great events saw Achamian ordered to accompany the Holy War and spy
on it for the Mandate.

Meanwhile, the Nansur Empire had instigated a military confrontation with the
Scylvendi. At the Battle of Kiyuth, early in 4110 Year-of-the-Tusk, a Nansur army under
Exalt-General Ikurei Conphas, the nephew and heir to the Emperor, defeated a
significant Scylvendi army under the overconfident King-of-Tribes, Xunnurit. The
defeat was unprecedented, the Scylvendi driven from the field in disarray with
tremendous loss of life and Xunnurit taken in chains back to Momemn. Among those
forced to flee the battlefield was Cnaiür urs Skiötha. In the years since his betrayal by
Anasûrimbor Moënghus, Cnaiür had become the chieftain of the Utemot, famed for
his both his savage intelligence and his unrelenting skill at war, the self-declared "Most
Violent of All Men". This claim was supported by his extensive swazond, the ritual scars
Scylvendi carved into their own flesh to celebrate kills in battle.

In the aftermath of Kiyuth, Cnaiür visited the graves of his ancestors only to find a
wounded man of the north, surrounded by hordes of dead Sranc. Helping him heal, he
learned that this man was Anasûrimbor Kellhus, travelling south to kill his father, the
hated Moënghus. Cnaiür decided to travel with Kellhus to help him achieve this goal.
Crossing the steppe and approaching the Nansur border, they slaughtered a band of
Scylvendi slavers and freed a young woman named Serwë. Serwë revealed that the
63armies of the Three Seas were gathering around Momemn, the capital of the Nansur
Empire, in preparation for the gruelling march on Shimeh, eight hundred miles or
more to the south.

The approximate route of the Holy War.

The Holy War gathered its strength, tens of thousands of soldiers marching from
Galeoth and Thunyerus, Ce Tydonn and Conriya, High Ainon and the Nansurium
itself. However, the Nansur Emperor, Ikurei Xerius III, saw a chance to manipulate the
Holy War to his own purpose. He agreed to provide the Holy War with his armies, the
support of his sorcerous school, the Imperial Saik, and the leadership of his famed
general Ikurei Conphas, in return that the lands conquered by the Holy War should be
64returned to Nansur control, as the heir to Cenei. This demand proved incompatible
with the notion of a Holy War fought for one religious purpose, with thousands of
troops from other nations potentially slaughtered for the gain of the Emperor in
Momemn. As the debate raged, the first contingent of the arriving armies decided to
march on Shimeh immediately rather than wait for the rest of the host to assemble.
The so-called Vulgar Holy War was destroyed at the Fourth Battle of Mengedda, the
heads of its leaders sent back to Momemn. Xerius attempted to use this knowledge to
press home the need for Nansur leadership in the war to come.

During this controversy, Cnaiür, Kellhus and Serwë arrived at the city, as well as Drusas
Achamian, who had attached himself to the retinue of Krijates Xinemus, the Marshal
of Attrempus. In his youth, Achamian had served as tutor to Crown Prince Nersei
Proyas of Conriya. Although Proyas loved Achamian, he became a devoted follower of
Inrithism and severed his ties with the schoolman, whom he considered damned.
Although Proyas refused to talk to Achamian as their retinue marched on Momemn, he
permitted Achamian to travel with them under Xinemus's parole. Achamian and Proyas
meet the three strangers from the north and Proyas saw an opportunity to outflank the
Emperor's unreasonable demands.

Meanwhile, in Sumna, Esmenet was visited by a man who somehow bewitched and
seduced her to gain intelligence on Achamian's activities. Horrified and believing that
the man may be linked to the Consult, Esmenet travelled to Momemn to try to find
Achamian. Along the way, she was almost stoned to death in an Nansur village for
bearing the caste-mark of a prostitute, but was saved by a Shrial Knight named
Sarcellus. He offered her protection on the road to Momemn.

In Momemn the leaders of the Holy War gathered to discuss the situation. To
everybody's shock, Nersei Proyas proposed that the Holy War accept Cnaiür as their
battle commander. Cnaiür had helped engineer a great Scylvendi victory over the
Kianene at the Battle of Zirkirta several years earlier and knew the ways of their enemy.
Cnaiür also unexpectedly acquitted himself well in a verbal battle of wits with Ikurei
Conphas. Kellhus, posing as a Prince of Atrithau who had foreseen the Holy War in his
65dreams, offered a reasoned analysis of the situation which cut to the heart of the
matter. The assembled nobles agreed to accept Cnaiür as their commander and the
delegate of the Holy Shriah commanded the Emperor to provision as the Holy War as
required under religious order. Outmanoeuvred, the Emperor was forced to stand
down. So as not to appear petty, he also allowed the imperial forces to join the Holy
War. However, during the meeting Kellhus visually identified one of the delegates,
Skeaös, as having something wrong with his face. The Emperor noted Kellhus's interest
and had Skeaös seized and interrogated. In this way, the Emperor came to learn of the
existence of the skin-spies, and that the mad old stories of the Mandate may have some
truth to them.

The Holy War marched from the Nansur Empire, crossing the mountainous frontier
with the northernmost Kianene province, Gedea. However, attempts to delay the
march to allow consolidation of the main army with late-arriving elements met with
disapproval from the leading forces, most notably Prince Coithus Saubon and his
headstrong forces from Galeoth. On the advice of Kellhus, whose intelligence, analysis
and prophetic dreams were the talk of the army, Saubon marched and secured an early
victory at Mengedda. This battle was hard-fought, with many of the Shrial Knights slain
and the Kianene only withdrawing once the bulk of the rest of the Holy War arrived,
but the victory enhanced Saubon's position and made him more trusting of Kellhus.

The rest of the Holy War consolidated. Esmenet was reunited with Achamian, who, in
violation of Mandate law, declared her his wife, but Kellhus immediately identified
Sarcellus as a skin-spy. He chose not to give this information away, knowing it risked
exposing himself as well.

Gedea and the northern half of Shigek fell to the Holy War, the Kianene armies
retreating south of the Sempis. Kellhus gave a series of sermons under the famed
Ziggurats of Shigek which attracted thousands of listeners. More than a few of the army
began to refer to him as the Warrior-Prophet.

Drusas Achamian, a sorcerer of the Mandate, turns the Gnosis against his captors from the Scarlet Spires.

Achamian taught Kellhus in the ways of the world, finding him a quick and formidable
study in history, mathematics and philosophy. Achamian soon discovered that Kellhus
was one of the Few and could use sorcery, but refused to betray his school by teaching
him the Gnosis. Torn by his respect for Kellhus, his desire for Esmenet and his loyalty
to the Mandate, Achamian sought solitude to think things through, but was captured
by the Scarlet Spires. The Spires had long desired mastery of the Gnosis, which eclipsed
their own sorcery, and had now learned of the existence of the skin-spies. Eleäzaras, the
master of the Spires, put Achamian to the question, even blinding his friend Xinemus
to try to get Achamian to talk. However, Seswatha’s gift also rendered Mandate
sorcerers immune to torture. Achamian was eventually able to escape and turn the full
might of the Gnosis upon his captors.

The Holy War marched on without Achamian (an absence that caused Esmenet great
distress), crossing the Sempis Delta and fighting a major battle under the fortress walls
of Anwurat. Despite heavy losses the Men of the Tusk prevailed and marched on into
Khemema. This was the most dangerous part of the journey, as Khemema was where
the Great Carathay Desert met the Meneanor Sea. No food grew there and no water
could be found. The Holy War had to brave the desert coastlands southwards for
almost two hundred miles. To survive the crossing the fleet had to be resupplied with
food and water by the Imperial Nansur navy. But the Kianene Padirajah had
67anticipated this move and deployed the Kianene fleet to intercept. In a great battle in
Trantis Bay, the Nansur fleet was defeated and put to rout by the Fanim. The Holy War
was cut off from succour and left to die in the burning wastes.

But the Holy War survived. Anasûrimbor Kellhus found great reserves of water far
below the desert sands and the army was saved, although much-reduced. The army
burst from the desert and besieged the great, ancient mercantile city of Caraskand.
Although ravaged by disease and starvation, the Holy War was able to take the city,
helped by treachery, and sacked it savagely. No sooner was this done, however, than the
Padirajah himself took the field. Kascamandri ab Tepherokar led a vast army out of the
south to besiege Caraskand and starve the Men of the Tusk into surrender or death.

Around this time Kellhus received a message from his father, borne by a Cishaurim.
Moënghus told Kellhus that soon he would grasp the Thousandfold Thought. The
nature of this concept eluded Kellhus, save it was an extension of the Dûnyain method
of foretelling future events through probability trances, predicting the future by
mastering what comes before. He was forced to execute the Cishaurim to maintain his
cover before he could learn more.

The Holy War had become torn between traditional Inrithi, led by Sarcellus and Ikurei
Conphas, and those who revered Kellhus as the Warrior-Prophet. The former became
known as the Orthodox and the latter, led by Nersei Proyas and Coithus Saubon but
with Esmenet placed high in their ranks, as the Zaudunyani , the Tribe of Truth. The
tensions between the two sides rose and resulted in a failed assassination attempt on
Kellhus and a failed counter-assassination attempt on Sarcellus and Conphas. The
chaos finally resulted in a trial. Sarcellus and Conphas won this trial and had Kellhus
denounced as a false prophet. Serwë, whom Kellhus had taken as wife, was executed
and her body was tied to Kellhus, who was then hung upside down from a tree on a
massive iron ring, a circumfix. Achamian returned at this point, learning that Esmenet
was pregnant by Kellhus (and that Serwë has borne a son, named Moënghus for
Kellhus's father, given to Esmenet to raise). Furious, he confronted the dying Kellhus
only to be told that many skin-spies had infiltrated the Holy War and only Kellhus
68could identify them. Reluctantly, Achamian begged for Kellhus's release but was
rebuffed by Ikurei Conphas.

But in this moment Cnaiür exposed Sarcellus as a Consult skin-spy by defeating him in
battle and severing his head. This causes the creature's face to return to its normal
appearance, to the horror of the witnesses. The Holy War repented, lowing Kellhus
from the Circumfix to find that he had survived. However, during his ordeal Kellhus
had nearly been broken, weeping and having visions of the Apocalypse, including
hearing the voice of the No-God. He recovered swiftly and produced a miracle: he
pulled forth Serwë’s heart from his own chest.

The Warrior-Prophet, now hailed as something more than a man, led the Men of the
Tusk from Caraskand in a direct assault on the Padirajah's army and, despite their
starved frames and lesser numbers, defeated it, with Kellhus himself killing
Kascamandri. Fanayal, Kascamandri's son, was declared the new Padirajah and fled the
field with as many surviving Kianene forces as possible. The Holy War had triumphed
and the road to Shimeh lay open.

At this time, the Consult descended upon the Ancient North. From the Neleöst to the
Cerish Sea and beyond hordes of Sranc suddenly acted with purpose, turning on
remote tribes of men who had survived - or been allowed to survive - on the Plains of
Gâl and the Istyuli Plains. Caravans daring the great crossing from Sakarpus to Atrithau
were taken prisoner and everywhere one question was asked, again and again: "Who are
the Dûnyain?"

Rested and, to an extent, resupplied, the Holy War issued forth from Caraskand and
marched south, though ancient Xerash and Amoteu. Kellhus, now universally accepted
as the Warrior-Prophet, had grasped what his father called the Thousandfold Thought:
a web of probability and consequence designed to defeat the Consult and halt the
resurrection of the No-God and the destruction of the world. Kellhus again asked
Achamian to teach him the Gnosis and this time Achamian complied. Kellhus told
Achamian that the time for sorcerers to be hated and feared and damned was over, and
69that Kellhus would declare their damnation to be at an end. In addition, Cnaiür's
public revelation of the skin-spy Sarcellus, Achamian's relating of the Celmomian
Prophecy (confirming that an Anasûrimbor would return at the end of the world) and
the awe that Kellhus was now held in combined to convince the Men of the Tusk that
the ancient stories were true: the Consult was real and working to bring about the
return of the No-God. The Mandate overnight were transformed from a joke to
prophets and guardians standing against the Second Apocalypse.

Meanwhile, Cnaiür was given the task by Kellhus of arranging the death of Ikurei
Conphas, whose mad dreams of becoming emperor and bringing about the rebirth of
Cenei and Kyraneas now posed a threat to the Warrior-Prophet. The deed was to be
done in the port city of Joktha, but Conphas turned the trap on Cnaiür and almost
killed him. The Scylvendi was rescued by a detachment of Consult skin-spies, eager to
win the allegiance of one of their former minions (the Scylvendi having fought for the
Consult in the Apocalypse).

Meppa, the most powerful Cishaurim to survive the Holy War.

The Holy War marched on. Mighty Gerotha, capital of Xerash, fell. To avoid a brutal
sacking the masters of the city were commanded to killed four-tenths of the city's
70population. Twenty thousand were put to the sword to appease the Men of the Tusk.
This example spread ahead of the Holy War and cities and fortresses and towns the
length of Xerash and Amoteu threw open their gates to avoid the same fate. Fanayal's
forces skirmished with the Holy War, eventually destroying their main scout formation,
but ultimately had to fall back on Holy Shimeh, leaving the way open for one last push
by the Holy War.

And at that moment, the Inchoroi came before Anasûrimbor Kellhus.

Using a vessel known as a Synthese, taking the form of his lover Esmenet, Aurang
spoke to Kellhus, trying to divine the nature of the Dûnyain and that of Kellhus
himself. Instead, it gave up more of itself and its goals. Kellhus learned that the
Inchoroi considered themselves a race of lovers, consumed by appetites of the flesh.
This was their nature and they were damned for it by the metaphysics of the universe,
condemned to roil and burn for all eternity in scouring fire. To avoid this fate the
Inchoroi had to destroy the people of the world. By slaughtering the population of the
world and bringing about the return of the No-God, the Inchoroi would seal shut the
world from the Outside, barring it from the view and the judgement of the gods. Only
then could the Inchoroi die, satisfied that they would not suffer eternal damnation as
their slain kin and as sorcerers still did.

Kellhus gave little in return, but told Aurang that the No-God spoke to him in his
dreams, that Mog-Pharau blamed the Inchoroi and the Consult for his defeat on the
plains of Mengedda and he would have his revenge.

The confrontation yielded little useful intelligence for the Consult, but it served to
distract Kellhus whilst an attempt was made on Achamian's life, to deny Kellhus the
Gnosis. This also failed.

The Holy War reached Shimeh and prepared to assault the city. The Scarlet Spires
summoned three Ciphrang, demons of the Outside, to cause panic and terror in the
city and divert the attention of the Cishaurim. A final push would ensure victory, but
71the Men of the Tusk were divided by the need for a rapid, final assault and the need for
caution: less than a sixth of the forces that set out from Momemn over a year and a half
earlier survived. Any prolonged siege or assault would sap their strength dangerously.
At the moment of the great battle, however, Kellhus left them. He commanded the
battle to the valour of the Men of the Tusk, but he had a task to attend to elsewhere.

Kellhus struck west for Kyudea, an ancient and ruined city built near the remains of an
old Nonman mansion. In that mansion Kellhus finally found his father: Anasûrimbor
Moënghus, known to the Kianene as Mallahet. Moënghus told Kellhus that he knew
that Kellhus's journey would open his eyes to the secrets and mysteries that he had
encountered himself, setting out from Ishuäl thirty years earlier, and he set the Holy
War in motion to clear the way for Kellhus's journey. However, Moënghus was unable
to predict what would happen when the Holy War turned on Kellhus and tried to kill
him. When Kellhus explained how he survived, through having visions of the
Apocalypse and the No-God, Moënghus concluded that his son had been driven
insane. Kellhus, as befitting a Dûnyain, analysed the possibility but rejected it.

Moënghus revealed that twelve years earlier the Cishaurim had discovered the first skin-
spies. Reasoning they were the creations of the Scarlet Spires, despite Moënghus’s
claims otherwise, they assassinated the Grandmaster Sasheoka, beginning a clandestine
war between the two orders. He then interrogated the skin-spies and learned of the
Consult and the threatened Second Apocalypse. Kellhus realised that if his father
accepted that he was damned to eternal torment he may take the same view as the
Inchoroi, that destroying humanity may be the only way to seal the Outside and end
the threat. To remove the danger, Kellhus stabbed his father and then left, innovating
the use of a Cant of Transposition to transport himself to Shimeh.

In the meantime, Cnaiür had returned to the Holy War and sought out Achamian. He
told the sorcerer of the Dûnyain and the true nature of both Kellhus and Moënghus.
He and his skin-spy liberators then left, following Kellhus's trail to Moënghus where
they found the man dying. Achamian tried to convince Esmenet to abandon Kellhus's
cause but she refused.

Drusas Achamian uses the Gnosis to defeat Zioz, a Ciphrang demon from the Outside.

The Holy War launched its assault on Shimeh. Initial successes turned sour when it was
revealed that Fanayal and the Cishaurim had prepared a trap, allowing part of the Holy
War to enter the city before trapping and destroying it. The ferocity of the Men-of-the-
Tusk again took the Fanim by surprise, but their numbers were no longer enough to
deliver them victory.

Ikurei Conphas's Nansur columns, pursuing Cnaiür, prepared to enter the fray. Having
learned of the death of his uncle in Momemn, Conphas had declared himself Emperor
and prepared to use his military might to end the threat of the Warrior-Prophet once
and for all. However, Conphas overreached and was killed on the battlefield by
Saubon. His forces were then redeployed against the Fanim of Kian, helping deliver a
shocking defeat to them. Elsewhere on the field the Scarlet Spires, driven into an
enraged frenzy to avenge their slain Grandmaster, drove the Cishaurim to the brink of
defeat, aided by the late-arriving Imperial Saik. But victory was still poised on a knife's
edge. It was only gained when Kellhus translocated himself into the midst of the last
surviving Cishaurim, slaying them before they even knew what was happening. Kellhus
had now mastered the Metagnosis, a more powerful and formidable form of the Gnosis
lost for millennia, even to the Nonmen.

The Warrior-Prophet delivered Shimeh to the Men of the Tusk.

For this last, great victory, Anasûrimbor Kellhus was proclaimed Aspect-Emperor of the
Three Seas, acclaimed so by the Holy Shriah, the Thousand Temples, the School of
Mandate, and all the princes and kings who had followed the Holy War on its great
journey. He was acclaimed by all...bar one.

Drusas Achamian came before his former pupil and repudiated him. He renounced his
role as tutor and advisor to Kellhus, his place in the Mandate, he renounced his
prophet and his wife before going into exile. Kellhus told him that the next time he
came before the Aspect-Emperor, Drusas Achamian would kneel.

A stylised representation of Anasûrimbor Kellhus. Born in Ishuäl in 4076, he was sent out into the World in 4109 at the command of the Dûnyain. By 4122 he had conquered the Three Seas, mastered the Gnosis and been crowned Aspect-Emperor.
