# Part 6: The Unification Wars

Word of the great victory at Shimeh spread to all the corners of the Three Seas. The
Holy War had triumphed. The heathen Fanim had been put to rout and the Holy City
restored to the Faithful. But even more remarkable were the stories that accompanied
the news. A new leader had emerged from the ranks of the Holy War. He had survived
death, performed great miracles and pulled the battered, bloodied remnants of the
crusade to a victory against odds unthinkable. Here was a story from the very Sagas
brought to life.

75Anasûrimbor Kellhus was proclaimed the Aspect-Emperor of the Three Seas by the
Shriah of the Thousand Temples. Tens of thousands of Men of the Tusk, forged in the
burning heat of the Great Carathay and tempered on the battlefields of Caraskand and
Shimeh, swore themselves his eternal subjects, his Zaudunyani , the “Tribe of Truth”.
Even three of the sorcerous schools (the Imperial Saik, the Scarlet Spires and the
Mandate) had sworn to his service. His victory, his rule, seemed unquestionable.

But history is never so simple. Across the Three Seas there was shock that this man, this
prince of nothing , had come out of nowhere and seemingly subverted the Holy War to
his own ends. Many dismissed him as a fraudster, or even a Ciphrang, a demon from
the Outside sent to lead men to their destruction. Some who may have been tempted to
hear him were disgusted to hear that he preached of the threat of the Consult and the
Inchoroi: children’s stories that no-one but those doddering old fools in Atyersus took
seriously. Armies were summoned, swords forged and bows strung as the opponents of
the new Aspect-Emperor, the Orthodox, braced themselves for war. Likewise,
Maithanet’s support for Kellhus had shattered the Thousand Temples, leading to many
priests – the Schismatics – taking up arms in defence of the faith and in opposite to the
Shriah.

Only one nation declared for Kellhus in its totality: Conriya, united under the rule of
Nersei Proyas. Every other nation splintered, the entire caste-nobility of the Three Seas
divided. Provinces and palatinates and principalities declared for or against Kellhus,
often depending on the zeal of their troops and rulers still encamped with the Holy
War around Shimeh. Most of civilised Eärwa teetered on the brink of civil war, moreso
in the Nansurium after the unexpected deaths of both Emperor Ikurei Xerius and his
heir, Ikurei Conphas, on campaign, leaving the Ikurei Dynasty extinguished.

But the Holy War was not done. Refreshed, reinforced (by the Mandate and other
sorcerers flocking to Kellhus’s banner) and resupplied, the Holy War struck south and
west into Kian proper. The long war had exhausted the fighting strength of the Fanim
and they could offer no effective resistance. Fanayal ab Kascamandri was unable to rally
his people and melted away into the Carathay Desert. By the end of 4113 the Holy War
76had seized Nenciphon and installed the Emperor and Empress in the White-Sun
Palace. Many soldiers formerly loyal to the Empire now switching their loyalty to
Anasûrimbor Kellhus. Massar ab Kascamandri, the brother of Fanayal, underwent the
Whelming, the spiritual induction into the ranks of the Zaudunyani, and swore his
entire nation to the service of Kellhus.

In 4114 Kellhus published a tract on sorcery. The Novum Arcanum attracted great
attention for its revelations and insights into sorcery and logic. The following year
Kellhus announced a great gathering of sorcerers from across Eärwa and they came in
unprecedented numbers to learn from him and hear his great Rehabilitation of Sorcery.
All Shrial and Tusk condemnations of the practice were rescinded and sorcerers were
no longer held to be anathema. Through such acts Kellhus won every sorcerer of rank
and power in Eärwa (save one) to his side, the sorcerous schools united under his
banner.

A witch of the Swayal Compact wielding the Gnosis. In magical power they matched the Mandate, whilst in terms of sheer numbers they outstripped all of the other schools, making them arguably the most powerful force in Eärwa apart from the Aspect-Emperor himself.

Kellhus also made his second great proclamation: the Manumission of the Feminine.
All limitations – legal, spiritual or moral – placed on the comportment of women were
struck down. Women now had full equal rights to men across the Three Seas. This was
initially a more controversial declaration, and seized upon by Kellhus’s opponents as
77proof of his madness, but it was also popular amongst, of course, the women of the
Three Seas, particular with regard to inheritance and property rights. Even more
dramatic was that the combination of the two declarations effectively ended the ban on
women joining the Few. For centuries women wielding sorcery had been scorned as
witches , burned at the stake or stoned to death even by those men who trafficked with
sorcerers themselves. Now they were allowed to come out of the shadows, in numbers
which caught the men of the Three Seas by surprise.

Even more breath-taking was what Kellhus did for these women: he commanded the
Mandate to instruct them in the ways of the Gnosis, and gave to them the abandoned
Cûnuroi Mansion of Illisserû in Holy Amoteu as their stronghold, now renamed
Orovelai. He made them a simple promise, to support and empower them in return for
their support in turn. This became known as the Swayal Compact, the name also taken
by the witches (a name many of them now wore with pride). Within a decade their
knowledge and mastery of the Gnosis rivalled that of the Mandate and their numbers
far outstripped them.

Kellhus won loyalty, even fanatical and maddened loyalty, in his own way. Within a
year of the fall of Nenciphon, his missionary-zealots had begun making their way across
the Three Seas. They became known as the Zaudûn Angnaya, the “floating college” of
young aspirants who learned from Kellhus whenever they could. They sought to
persuade through argument, reason and, whenever that failed, conviction . Horrified
stories spread amongst the Orthodox of “suicide sermons”, when Angnaya would slit
their own throats in front of the vast crowds to prove their absolute faith. At first, they
used such demonstrations as proof of Kellhus’s danger and insanity, but the
unshakeable faith and certitude of the zealots shook the Orthodox, who had no
spiritual answer for them.

The Unification Wars. In less than ten years, Anasûrimbor Kellhus brought the Three Seas under his
rule. With the final capitulation of Nilnamesh in 4122, Kellhus became its sole political, military,
religious and sorcerous leader: its Aspect-Emperor, with approximately 75 million souls living under his ule.

By the end of 4114 war had come: the Fanim inspired a massive uprising in Shigek, but
this had been crushed by Rash Soptet, Lord of the Sempis. The growing rift in the
Thousand Temples erupted in bloodletting, the War-between-Temples. Nilnamesh,
long separated from its Inrithi brethren by the width of the Kian Empire, also declared
against Kellhus.

In 4115 Prince Shoddû Akirapita assembled a large army in Nilnamesh and moved to
defend the border. The Zaudunyani were defeated at the Battle of Pinropis, to their
surprise. Kellhus took time to regroup, during which time his allies achieved greater
victories: in 4116 Coithus Narnol declared for Kellhus and delivered Galeoth almost
intact to his banner. King Hringa Vûkyelt likewise unified Thunyerus in Kellhus’s
name and expelled the Schismatics from the kingdom. The following year both Ce
Tydonn and High Ainon became divided in a bitter civil war, followed by the
declaration of Ce Tydonn for Kellhus in 4118. Cironj also fell in this year.

High Ainon presented Kellhus with a major problem: the nation was vast and unruly at
the best of times but unified in its fear of the Scarlet Spires. But the Holy War had
almost destroyed the order altogether, with barely a dozen sorcerers-of-rank surviving
the conflagration at Shimeh. To their humiliation, Kellhus award the Mandate
command of Kiz, the former Scarlet Spires stronghold in Carythusal. From there the
Mandate was able to bring the rule of the Aspect-Emperor to lower Ainon, but the full
capitulation of the kingdom took longer. In 4120 the Sack of Sarneveh took place,
Kellhus himself leading the capture of the city. Although successful, the Toll of
Casualties (a meticulous accounting of the cost of each victory, which Kellhus
abandoned after this point) recorded more than five thousand children slain. This news
escaped the city, encouraging further resistance to Kellhus. However, by the end of
4121 High Ainon had fallen and declared for Kellhus.

At this point, a curiosity took place, one which even the most fanatical Zaudunyani
have struggled to reconcile with their extolling of Kellhus as a messenger of the divine.
Following the conquest of High Ainon, Kellhus spent four months in Kiz as a student
of Heramari Iyokus, the famed Blind Necromancer and a master practitioner of the
Daimos, the sorcerous art of communing with and summoning demons. At the end of
this tutelage Kellhus emerged with two grotesque demon head bound to his hip by
their hair: the Decapitants. Kellhus demurred on explaining their origin, often ignoring
the question altogether. Rumour said that the Aspect-Emperor had somehow plumbed
the very Hells themselves for knowledge and returned with the heads as trophies of his
victory, and to remind the Aspect-Emperor of the fate awaiting all those who were
damned.

Also in 4121, the Nilnameshi capital of Invishi had finally fallen to the Zaudunyani.
However, Prince Akirapita refused to capitulate, gathering a new army. It was not until
this army was destroyed at the Battle of Ushgarwal in 4122 and the Prince slain (his
body was found in a well in Girgash in 4123) that Nilnamesh could finally be said to
have been brought into the fold. This left only Fanayal ab Kascamandri out of the
Aspect-Emperor’s many foes, and his forces were reduced to a few tribesfolk of the
Great Salt.

The Unification Wars were declared over in 4122. Maithanet, having won the War-
between-Temples, crowned Anasûrimbor Kellhus the Aspect-Emperor of the Three Seas
in Momemn, which Kellhus had taken as his capital. Kellhus and his wife, Esmenet,
now had several children – Kayûtas (b. 4112), Theliopa (b. 4114, in Nenciphon), Serwa
(b. 4115) and Inrilatas (b. 4117) – and more would follow, the twins Kelmomas and
Samarmas (both b. 2124). They had also adopted the son of Cnaiür urs Skiötha and
Serwë, Moënghus II (b. 4111) as their own. The result was that they had already
established a dynasty, one with the power to rule the Three Seas for generations to
come.

But the new goal of the Anasûrimbor family was not to simply rule. Kellhus declared
war on Golgotterath and the Unholy Consult. He declared his goal was to destroy the
dread Ark and cast down its Golden Horns forever. His purpose was to forestall the
return of the No-God, prevent the Second Apocalypse and to save the World itself. To
this end he commanded the establishing of the greatest army in human history. Swords
and armour were forged on a titanic scale. Horses were bred in their tens of thousands.
Supply caches were established in the northern Empire, near the Kathol Pass leading to
the vast Istyuli Plains. Sorcerers were called to train and learn as they never had before,
and to prepare for the war to come, which would be known as the Great Ordeal.

Drusas Achamian, the only Wizard (a sorcerer-without-a-school) of the Three Seas.
