# Part 7: The Great Ordeal

At one time Drusas Achamian was an agent of the Mandate, a sorcerer haunted by
dreams of Seswatha, hero of the First Apocalypse, and by fears that the Second was
coming. During the chaotic swirl of the Holy War he found a man whom he believed
could save humanity and lead it to victory over the ancient foe, the Unholy Consult.
Anasûrimbor Kellhus led the Holy War to victory, but in doing so he stole away
Achamian’s love, Esmenet, and subverted the religious fervour and faith of millions to
build himself an empire.

Faced with the choice of kneeling to the Aspect-Emperor or repudiating him,
Achamian chose the latter. Unimpeded, at the Aspect-Emperor’s express command,
82Achamian fled into the wilds of Galeoth, erecting a tower to live in solitude and
meditate on one question: “Who is the Aspect-Emperor?”

Achamian knew only a few facts and hints, gained from the all-too-brief revelations of
Cnaiür urs Skiötha in the dying hours of the war. He knew that Kellhus was Dûnyain,
the member of an almost unknown sect that had survived the Apocalypse and the two
thousand years since in utter solitude, pursuing intellectual and philosophical pursuits.
He had teased out the name Ishuäl from Seswatha’s dreams, the secret redoubt of the
House Anasûrimbor ere the fall of Kûniüri, but did not know where it could be found.
In desperation, he plunged further into the dreams, ploughing into them night after
night, writing down every nuance and every detail for signs of clues to the Dûnyain’s
origins, which he now believed lay in the catastrophes of those times. Over time he
teased some new revelations from the dreams, such as the fact that Seswatha had
seduced his friend Anasûrimbor Celmomas II’s wife, and that the famed hero Nau-
Cayûti may have been born from Seswatha’s line rather than the house of
Anasûrimbor. But, although historically scandalous, Achamian could not tease
meaning from such revelations.

In the early spring of 4132 Year-of-the-Tusk, nigh on twenty years since the Fall of
Shimeh, Drusas Achamian received a surprising visitor: Anasûrimbor Mimara, the
oldest child and first daughter of Esmenet of Sumna. Born long before the Holy War,
when famine stalked the city and her mother was forced to give her away to save her
life, Mimara’s life had been hard and cruel. Not long after Esmenet was installed in
Momemn as Empress, she sent agents to scour the Three Seas to find Mimara and
eventually they succeeded. But in the cold hallways of the Andiamine Heights, Mimara
did not found the home she sought. Her half-brothers and half-sisters, the children of
Kellhus, were not quite human and she found forging a bond with the mother who had
abandoned her too difficult. Mimara eventually learned that she was of the Few, but
sorcery was denied to her at her mother’s command, even among the newly-crafted
School of Witches, the Swayal Compact. Frustrated, she abandoned Momemn and
sought out Achamian, the sorcerer-without-a-school, a wizard.

83Mimara tried to convince Achamian to teach her the Gnosis, but Achamian resisted,
even after she seduced him. Instead they swapped stories, Achamian revealing his quest
to find Kellhus’s birthplace and Mimara revealing her own harsh upbringing. In the
midst of the conversation, Mimara revealed something Achamian was not expecting:

The Great Ordeal marches, old man.

The Great Ordeal arrives at Sakarpus, the City of the Plains and home to the famed Chorae Hoard.

From across the Three Seas assembled an armed host dwarfing any in history. A third
of a million men, clad in the finest armour and carrying the stoutest blades. A
thousand or more sorcerers, assembled from all of the Schools. Tens of thousands of
horses, millions of arrows. An army ten years in the planning. It gathered near the
Kathol Pass, assembling under the watchful eyes of the Believer-Kings and the great
heroes of the Holy War, chief amongst them Coithus Saubon and Nersei Proyas.

84The army marched north and west, through the mountains and into the edges of
civilisation. They closed around Sakarpus, the mighty city-of-the-plains which had
survived even the No-God itself during the First Apocalypse and whose mighty Chorae
Hoard struck fear into the hearts of sorcerers. But not the Aspect-Emperor. Kellhus
moved to take the city and King Horweel chose resistance, but also knew that his
resistance was doomed. He commanded that his son, Sorweel, be kept safe, even as his
own death drew near. After the city’s surrender, Kellhus came before Sorweel and told
him that he was now King of Sakarpus and that his father would forgive him for
surviving where his father had not. Sorweel was inducted into the ranks of the Great
Ordeal, riding in the Scions, a horse company made up of princely hostages from across
Eärwa. Sorweel’s new friends and allies including Zsoronga ut Nganka’kull, the
Successor Prince of Zeüm, and Eskeles, a Mandate sorcerer who taught the young king
Sheyic, the common tongue of the Three Seas. Sorweel also learned of the Aspect-
Emperor’s rise to power and why so many regarded him as a prophet.

Also assigned to Sorweel was a slave, Porsparian. However, Porsparian was also an
initiate of the Cult of Yatwer, the fertility goddess. He moulded the face of Yatwer out
of the dirt and took mud from her lips to paste over Sorweel’s face. Afterwards, Sorweel
found himself able to lie to the face of the Aspect-Emperor and not be discovered .
Yatwer’s blessing rendered Sorweel immune to the Aspect-Emperor’s supposedly holy
sight, which could discern almost instantly the presence of Consult skin-spies and read
the untruths from the lips of practiced liars. Instead, Kellhus believed that Sorweel had
become a true follower and named him a Believer-King, one of the most exalted rulers
in all Eärwa...and a dagger positioned close to the Aspect-Emperor’s heart.

Mimara’s news panicked Drusas Achamian, who believed that momentous events were
passing, maybe even the events that would trigger the Second Apocalypse rather than
forestall it. Indeed, from his dreams he recalled the great First Ordeal of Celmomas, an
army fashioned at the urging of Seswatha to destroy Golgotterath ere the rise of the No-
God but which had ultimately failed. Leaving Mimara behind, Achamian travelled to
Marrow and there commissioned the services of the Skin Eaters, a party of “scalpers”,
85mercenaries who travelled the far side of the Osthwai Mountains in search of Sranc
bounty.

Achamian told them of fabled Sauglish, the greatest seat of learning in Eärwa. It had
fallen to the No-God during the Apocalypse, but its Great Library had not been
completely destroyed. There, Achamian hoped to find the secret location of Ishuäl.
However, he also claimed the fabled Coffers, the Library’s great treasury, likely still
endured and would reward the mercenaries with great riches. The mercenaries were
dubious, since the mission would involve crossing many hundreds of miles of
dangerous territory, but their greed and the urging of their mysterious Nonman ally,
Incariol or “Cleric”, convinced them to take the commission. Soon after setting out
they were joined by Mimara, who had tracked Achamian from his home. Fearing for
her safety amongst such dangerous men, Achamian claimed her as his daughter.
Mimara disclosed to Achamian a secret that she had been hiding her whole life: she
bore a “secret eye”, one which can see the absolute good and evil in all people.
Achamian recognised this as the Judging Eye , an exceedingly rare and potent ability.
Troubled, he would not reveal more.

The Skin Eaters make their way through the ancient ruins of Cil-Aujas.

Soon after setting out, the party discovered that the passes through the mountains had
been closed by spring blizzards. They instead chanced the ancient Nonman Mansion of
Cil-Aujas. The Mansion had survived the ancient Cûno-Inchoroi Wars, the wars against
the invading hordes of men and even the No-God, but had been betrayed and sacked
by the armies of men allied to it, an act of treachery renowned in history. The scalpers
passed through the mountain only to find it infested with Sranc. A dangerous running
battle through the mountain eventually ended in an even greater horror: the shade of
Gin’yursis, the Nonman King of Cil-Aujas, possessed Cleric and attacked the rest of the
party. The rest of the group was outmatched, but Mimara used her Judging Eye on one
of their Chorae, transforming it into a shining white Tear of God. This caused
Gin’yursis’s shade to dissipate, and a troubled Cleric to return to normal. Shaken, the
party emerged on the far side of the Osthwai Mountains and began the gruelling march
– the slog-of-slogs – through the forested wilderness.

In Momemn, capital of the New Empire, the Empress Esmenet struggled to hold the
Empire together in her husband’s absence. Her most capable children and stepson –
Kayûtas, Serwa and Moënghus – had joined the Great Ordeal. Her daughter Theliopa
remained as an advisor, but she was scarcely human, possessing uncanny insights and
wisdom that had cracked her sanity. Inrilatas was locked away atop the Andiamine
Heights for his own safety and the safety of those around him. Only the twins
Kelmomas and Samarmas gave her any joy, but she was unaware that Kelmomas was a
cunning, conniving little creature, possessing both the analytical power of the Dûnyain
and a callous disregard for the consequences of his actions. Kelmomas engineered the
death of his idiot twin, determined to make his mother love him all the more.

But a new threat grew from within the Empire. Psatma Nannaferi, the outlawed
Mother-Supreme of the Cult of Yatwer, declared her goddess’s war against the House of
Anasûrimbor. A holy assassin, the White-Luck Warrior (so-called because how he
walked the perfect path of circumstance and fortune), revealed himself and his mission
to lay waste to the House Imperial. Yatwer, as the god most fervently and widely-
worshipped by the slaves and caste-menials of the Three Seas, commanded enormous
respect and power and soon unrest began to spread throughout the entire Empire.

87Distracted by Samarmas’s death, Esmenet employed the aid of her brother-in-law
Maithanet, Shriah of the Thousand Temples, to overcome this new threat. Maithanet
reminded her that the gods could not see, perceive or even comprehend the No-God
and were utterly blind to the coming threat of the Second Apocalypse (as they were to
the First, seeing it instead as inexplicable carnage wrought by man against himself).
Maithanet advised turning the Yatwerians against themselves by convincing their
official Matriarch, Sharacinth, to condemn Nannaferi. This plan was successful, albeit
only when Kellhus translocated from the Ordeal to the palace to cower the woman, but
sabotaged when Kelmomas, seeking to further isolate his mother from her other
concerns, murdered Sharacinth and her retinue. This further turned the poor of the
Empire against the imperial family.

The Skin Eaters fled from Cil-Aujas into the Mop, the vast, untamed forests covered
the lands north and east from the Osthwai Mountains to the Sea of Cerish. Their
course would take them through the ruins of the Apocalypse, skirting the edges of the
fallen Meörn Empire. The road was long and beset by challenges: Sranc in ever-
increasing numbers, and rival scalpers eager to kill them and loot their bodies. There
was also a threat from within. Using her conditioned training gained whilst in
Momemn, Mimara discovered that one of their number, Soma, was a skin-spy.
Achamian attempted to parley with the creature, but it chose to flee. It shadowed the
party, intervening during a Sranc raid to kill one of the creatures before it could harm
Mimara, to her bemusement. It informed her that she was pregnant with Achamian’s
child. Soma was working on the orders of the Inchoroi, communicating with them by
Synthese. Their order was that Mimara must be protected all the way to Golgotterath if
necessary. All of the prophecies must be respected, “the false as much as the true”.

The Great Ordeal entered the heart of the vast Istyuli Plains, a colossal tableland
extending across thousands of miles. Concerned with supply, the Aspect-Emperor
ordered that the Ordeal should split into four armies and march separately to improve
their chances of foraging. Believer-King Sorweel earned respect for his scouting (using
both his native knowledge of the plains and also information gained from his divine connection to Yatwer), which uncovered evidence of Sranc having been in the region
recently but having now fallen back before the Ordeal. Such signs grew until they
become indisputable: a vast Sranc Horde was gathering ahead of the Ordeal, giving way
before it and accumulating all of the tribes of the plains. The numbers lying beyond the
northern horizon defied all rationality, and the Scions raced back to the Ordeal to give
them warning.

The Culling. Hundreds of sorcerers scour the edges of the Sranc Horde, forcing them back whilst outriders of the Great Ordeal slaughter the stragglers. This would continue day after day for months as the Ordeal crossed the Istyuli Plains, and it barely held the Sranc at bay.

They halted at last, swamped by the enemy and protected from death only by Eskeles’
sorcerous wards. At Sorweel’s urging, Eskeles found a way of alerting the Ordeal by
illuminating the sky above him with a Bar of Heaven. They were rescued by witches led
by Anasûrimbor Serwa and returned to the Ordeal. Sorweel was praised for his actions,
which had saved the Ordeal from a costly ambush. In the aftermath of the action, the
Ordeal deployed its sorcerers to begin the Culling, with hundreds of sorcerers using
vast amounts of power to burn Sranc in their thousands and tens of thousands from
above. The slaughter was immense, but the losses were made good – and more – by
freshly-arriving Sranc clans from the High Istyuli.

89Sorweel confessed his relationship with Yatwer to his friend Zsoronga, who realised that
Sorweel had been positioned as a Narindari , a divine assassin sent to murder Kellhus.
This seemed confirmed when Kellhus sent the order to execute all slaves and
unnecessary non-combatants to help preserve food supplies, Porsparian amongst them.
Before his death, Porsparian summoned a visage of Yatwer. Yatwer gave Sorweel a
mighty gift: a single Chorae, hidden in a pouch that could shield its detection by the
Few. The image disappeared and Porsparian killed himself. Sorweel was now trusted
enough to get close to the Aspect-Emperor and kill him, but feared that Yatwer’s
protection would not be enough. He sought out Serwa to thank her for saving him, and
discovered that she could also not detect either his hidden Chorae nor his deception.

Soonafter, surprising news came: Ishterebinth, last of the Nonmen Mansions, had
rallied to Kellhus’s cause. A Nonmen emissary of King Nil’giccas offered to support the
Ordeal if, in return according to the ancient codes, three hostages were sent to the
Mansion and the Ordeal could prove its worth by retaking Dagliash, the ancient
fortress of men built atop the fallen Mansion of Viri. For his hostages Kellhus chose his
stepson Moënghus, his daughter Serwa...and Sorweel. Using metagnostic cants of
translocation, Serwa took her brother and Sorweel to Ishterebinth at great speed. On
this journey Sorweel learned that Serwa and her stepbrother were involved in an ill-
advised, passionate relationship.

The Great Ordeal approached the shores of Neleöst, the Misty Sea, but also fell into a
trap. The Army of the South fortified the ruined stronghold of Irsûlor on the western
flank of the Ordeal, unaware that the Sranc Horde had swung to the west in an attempt
to catch them by surprise. The Mandate and the Vokalati schools joined forces to burn
the Sranc, but the creatures suddenly surged through the curtain of magic to swamp the
fortress. The Consult had also hidden a legion of Bashrags within the ruins. At a key
moment, they emerged to shatter the human lines. In the slaughter that followed the
Army of the South was utterly destroyed, many sorcerers dying with them.

In the wake of the catastrophe, with near a quarter of the Ordeal lost, the three
remaining armies of the Ordeal reunited and heard the command of the Aspect-Emperor on the holy heights of the great hill Swaranûl, overlooking the sea. The
Ordeal had exhausted its supplies and would now have to eat the bodies of the fallen
Sranc.

Cleric, a Nonman Erratic working with the Skin Eaters.

The Skin Eaters pressed on across the Istyuli Plains, crossing the line of march of the
Ordeal. With rations low, Cleric had taken to dispensing Qirri , a form of Nonman
sustenance, to the company. It fortified them, allowing them to march longer and
harder than would otherwise be possible. Mimara eventually learned the truth: Qirri
was the powdered remains of ancient Nonmen heroes, and the pouch Cleric carried
contained none of than the remains of Cû’jara Cinmoi himself. Horrified, Achamian
attempted to refuse the Qirri. He was bound and gagged by the other scalpers. Captain
91Kosoter then revealed that he was an agent of Anasûrimbor Kellhus, begging Mimara to
help save him from damnation. Mimara used the Judging Eye on Kosoter and
discovered that his soul was blackened from the atrocities he had carried out at the
Aspect-Emperor’s command, and he was utterly beyond redemption.

The party reached the ruins of Sauglish, but Mimara had discovered another truth:
Cleric was none other than Nil’giccas himself, the High King of Ishterebinth and the
great hero of the Cûno-Inchoroi Wars. She disclosed this to Achamian, who was
released. Kosoter ordered Cleric and Achamian into the ruins to find the Library and
the Coffers, whilst he kept Mimara as surety. However, Kosoter’s men, traumatised by
the horrors of their journey, turned on and murdered him. Mimara would have been
killed had not the skin-spy Soma returned and saved her for reasons still unclear.

In the ruins of Sauglish Achamian attempted to reason with Cleric by awakening his
memories of Nil’giccas, but this backfired, awakening instead the Nonman’s desire for
pain and suffering, for only those things made impressions in his multi-millennial
memory. Their burgeoning discord was interrupted by the discovery within Sauglish of
Wutteät, the Father-of-Dragons, a dread Wracu of the Ark who had once borne the
obscene King Sil on his back. Achamian attempted to reason with the creature in
exchange for the map to Ishuäl, learning that he had travelled on the Ark with the
Inchoroi from other worlds. The goal of the Inchoroi was to reduce the number of
souls on any given world to just 144,000, in pursuit of their cause of sealing the world
against the Outside and avoiding damnation.

Battle erupted and the Mandate schoolman and Qûya sorcerer combined their power
to drive the creature from the skies, as in the days of old. But Nil’giccas turned on
Achamian and would have killed him, had Achamian not noticed that Nil’giccas had
raised no sorcerous wards of his own, inviting his own destruction. Achamian,
sorrowfully, complied. Afterwards he burned the great Nonman’s remains, taking the
ashes as Qirri. In the ruins of the library, using Seswatha’s memories, he found the map
showing where House Anasûrimbor had secretly built Ishuäl, high in the Demua
Mountains.

Returning to the camp, Achamian found Mimara safe but the skin-spy, Kosoter and
most of his men dead and the rest fled. They now set out north and west for the
mountains.

Second Negotiant Malowebi, a Mbimayu Schoolman of Zeüm, was sent to the camp of
Fanayal to assess his strength and see if the Fanim and Zeüm could strike up an alliance
to oppose the Aspect-Emperor. Malowebi was unimpressed with Fanayal, whose twenty
years of exile in the desert had taken a toll, but was more heartened by the continued
survival of Meppa, the Last Cishaurim. The Fanim marched on the Sempis River
Valley, Malowebi accompanying them as an observer on behalf of the Great Satakhan.

The paths of the Great Ordeal and the Skin Eaters.

In Momemn, the Empress learned of the advancing Fanim armies. Disturbed, and
aware how militarily weak the New Empire was in Kellhus’s absence, she showed
Kelmomas a secret network of tunnels riddling the Andiamine Heights. Suspicious of
Maithanet’s role in events, the Empress asked her children for help. Theliopa suggested
that she use Inrilatas to sound out Maithanet’s goals. Although mad, Inrilatas had also
93inherited more of his father’s gifts than any of his siblings. Esmenet complied,
convincing Maithanet to visit Inrilatas. The only other person present was Kelmomas.
Maithanet admitted he had doubts about Kellhus’s plans, but only because Kellhus has
allowed his love for his children and wife to cloud the Thousandfold Thought (to the
surprise of Kelmomas, who believed his father incapable of such an emotion). Inrilatas
exposed Kelmomas’s crimes, shocking even Maithanet, before attempting to murder
him. He failed and Maithanet killed Inrilatas in self-defence. Kelmomas denounced his
uncle as an assassin and murderer, throwing the city into an uproar. Esmenet
contracted an assassin to kill her brother-in-law, unaware that the man she found for
the job was the White-Luck Warrior himself.

The Fanim armies took Iothiah, the capital of Old Shigek, impressing even the sceptical
Malowebi. After the conquest Fanayal was confronted by Psatma Nannaferi who,
speaking for the Cult of Yatwer (and Yatwer herself), cultivated an alliance with the
Fanim to bring down the demon-emperor Kellhus. Malowebi reported on these events
to his Satakhan but cautioned that Kellhus emptying the Three Seas of armies
suggested that he genuinely believed in the threat of the Consult and the No-God. The
Satakhan nevertheless sensed an opportunity. He told Malowebi to offer Fanayal an
alliance: High Holy Zeüm would support the Fanim if they could take Momemn itself.

Esmenet met with her assassin in secret in the city, only to find that Maithanet’s troops
had captured the palace in her absence. Taken into hiding by her captain of the guards,
Esmenet fretted over the fate of her children, especially Kelmomas. However,
Kelmomas made use of the secret passages she had shown him to hide from guards,
occasionally emerging to steal food (and, horrifically, to kill guards and use them for
sustenance).

Esmenet was eventually found and taken back to the palace. Maithanet demanded to
know why she had tried to kill him, but she said this had not been her intent. Using his
Dûnyain conditioning, Maithanet realised she spoke true. Maithanet released her and
told her his suspicion: that Kellhus had created the New Empire purely as a machine to
create the forces he needed to march on Golgotterath. That achieved, he no longer
94required the Empire and had abandoned it to its ruin. Esmenet was horrified.
Maithanet announced the reconciliation of the Imperial Throne and the Thousand
Temples, but was suddenly struck down by the White-Luck Warrior, acting on
Esmenet’s orders. Esmenet declared Maithanet a traitor and heretic, the murderer of
the Aspect-Emperor’s son. The city rallied to her cause, just the trumpets of the Fanim
sounded out and Fanayal’s army arrived to besiege the city.

Achamian’s dreams had been changing for years, but now they had taken on a new
level of detail, images from not just Seswatha but also his great friend Celmomas and
his son Nau-Cayûti. On the Fields of Eleneöt, Achamian saw Celmomas’s death from
the perspective of Celmomas himself . At the moment of his death he uttered his
famous prophecy, that at the end of the world an Anasûrimbor would return. But when
he uttered this prophecy it was because a vision of Gilgaöl, God of War, had come
before him, holding an image of a man. And that man was Anasûrimbor Kellhus. This
revelation shocked Achamian but he did not know what to make of it.

In Ishterebinth, the envoys Sorweel, Serwa and Moënghus were seized by the Nonmen
and put to the question. Sorweel quickly discovered that Nil’giccas was missing, having
fled in ages past, and that the remaining Nonmen had formed an alliance with the
Consult. The interrogation of Sorweel discovered his connection to Yatwer and his
destiny was to kill the Aspect-Emperor. Upon the revelation of this news, he was
released into the custody of Oinaral Lastborn, who could provide him aid in his quest.
He was given the Amiolas, one of the greatest sorcerous artifacts in Nonman history,
which bonded his soul to that of a slain malcontent, Immiriccas. This resulted in
Sorweel learning the Nonman language, but also learning the truth of the Unholy
Consult: through Immiriccas’s memories he relieved some of the Cûno-Inchoroi Wars.
Thus, the Consult’s gambit backfired: Sorweel became convinced of the righteousness
of the Aspect-Emperor’s cause.

Anasûrimbor Serwa, daughter of the Aspect-Emperor and Grandmistress of the Swayal Compact.
Wielder of the Metagnosis, the most powerful sorcerer since Titirga himself, save only her father.

Oinaral had also become doubtful of the wisdom of allying with the great enemy, so
took Sorweel into the deepest part of the mountain. They sought Oirûnas, Oinaral’s
father, a great hero of the wars against the Inchoroi. Find him they did, but the hero
had been driven utterly insane by the passage of the millennia. In a rage, he slew his
son and tore the Amiolas from Sorweel’s face, but Sorweel was able to guide him to the
inhabited part of the mountain. There Oirûnas, Lord of the Watch, slew Nin’ciljiras,
the Consult pretender to the throne of Ishterebinth and the last survivor of the line of
Nin’janjin. During the resulting chaos Sorweel freed Moënghus, who had been near
broken by his captivity, and Serwa, who had not. Serwa sang her metagnostic cants of
destruction...

96The Great Ordeal marched north from the charnel fields of Irsûlor, crossing into the
ancient, long-fallen kingdom of Aörsi. With their food gone, the Ordeal followed the
command to consume Sranc. The Culling took on a new form, with Sranc corpses now
collected for consumption. As the Ordeal marched, its character changed, becoming
something more animal. The Exalt-General, Nersei Proyas, became concerned at this
turn of events, believing it threatened both the spiritual and moral superiority of the
cause. He turned to his Aspect-Emperor, hoping for reassurance, but instead Kellhus
admitted the unthinkable: that he was just a man searching for answers and doing the
best he could. He was no god, no prophet, just a man, with a man’s needs. He
“seduced” an uncomprehending Proyas.

This act broke Proyas’s faith in the Aspect-Emperor. He sought advice and aid from his
brother in rank and war, Coithus Saubon, but Saubon remained constant in his belief
in the Aspect-Emperor’s plans.

Now the Great Ordeal drew close to the River Sursa and the small mountain range
known as the Urokkas, which lay above the fallen Nonman mansion of Viri. During
the time of the First Ordeal and the Apocalypse, a great fortress called Dagliash had
been built atop Antareg, the northern-most of the mountains. Kellhus now planned to
use the geography of the region to go on the offensive.

The great Sranc Horde was forced to divide around the mountains and skirt the river,
allowing the Ordeal to concentrate the bulk of its forces against a smaller fraction of
the Horde and destroy it in detail. The sorcerers brought their full power to bear
against the Horde and bloody slaughter was wrecked in a fashion never before seen.
The Sranc were suddenly being annihilated at a speed they could not replace, and their
destruction seemed imminent.

However, Kellhus perceived movement in the fallen mansion and realised that the
Consult had seeded many Sranc and Bashrags in the ruins, preparing to catch the
Ordeal unawares. Saubon led an assault on the mountain of Antareg and engaged the
Bashrags instead, defeating the Consult’s plans.

Victory seemed near, so the Inchoroi Aurang took the field, challenging the sorcerers.
Saccarees, the head of the Mandate, met the challenge but Aurang suddenly fled.
Sensing this was a distraction, Kellhus returned to the peak of Antareg and emptied it,
pulling the contents of the fallen fortress of Dagliash and the Nonman mansion below
up into the sky and hurling them down onto the Horde. Amongst the artifacts pulled
out of the ruins was a strange Tekne device, a cube with unknown figures on it,
changing, counting down...

The Aspect-Emperor translocated from the field, leaving behind a command to the
Great Ordeal to flee Dagliash, to abandon the mountain. The army complied but for
those closest to the device there was no time. A tremendous light filled the sky, a
roaring blast that consumed the mountain top, most of the Sranc Horde and an
appreciable fraction of the Great Ordeal. Coithus Saubon and those closest to the
device were killed instantly, vaporised by a fireball that rose into the sky and became a
dark mushroom cloud filling the sky. This was a weapon that the Inchoroi had
deployed before but rarely, only in the most desperate days of their wars with the
Nonmen. A Scalding.

Drusas Achamian and Anasûrimbor Mimara arrived at Ishuäl, the stronghold of the
Dûnyain. They sought answers but instead found ashes: the Thousand-Thousand Halls
were a desolate ruin, the bones of men, Bashrags and Sranc and Nonmen everywhere.
They also learned what had already been suspected, that the Dûnyain were not fully
human. Through surgery and genetic manipulation, they had reduced their women to
little more than breathing wombs for their sons, the so-called Whale-mothers. The
Judging Eye confirmed what was now obvious: despite their claims to rationality and
cold logic, the Dûnyain were absolute evil, beyond any question. The question now
arose if Kellhus was also evil. Achamian told Mimara that their mission now had a new
goal: to apprehend Kellhus with the Judging Eye.

They also found survivors, the son and grandson of Kellhus. They learned that the
Consult had finally found Ishuäl and assaulted it in a fury. It had taken years of bitter
98fighting, but they finally destroyed the fortress, leaving behind just two survivors
scrabbling for sustenance in the dark. The man and the boy were Dûnyain, quick to
analyse and grasp Mimara and Achamian’s desires and motivations, but they were also
stymied by both Achamian’s sorcery and by the Judging Eye, which rendered their
attempts at deception moot. The father – the Survivor – whose sanity was already
precarious after the fall of Ishuäl, was driven to madness by the revelations and by the
Qirri he was given to consume. He threw himself to his death.

The three travellers descended the mountains north and eastwards. On the horizon
they saw a storm and, using sorcery, Achamian magnified the image to show the horror
cloud rising above the far northern shore of the Misty Sea. Then they were captured,
taken prisoner by the Scylvendi. To his surprise, Achamian found himself once again in
the company of Cnaiür urs Skiötha. He learned that Cnaiür survived the aftermath of
Shimeh and, helped by the Consult skin-spies, had seized control of the entire
Scylvendi race. They now marched to Golgotterath, to the relief of the Unholy Consult.
Cnaiür planned to kill Anasûrimbor Kellhus, his hatred undimmed by the passage of
twenty years. Learning of Mimara’s ability and that they might be enemies of Kellhus
themselves, Cnaiür chose to release them. The boy from Ishuäl fled in another
direction, both the Scylvendi and Achamian content to let him go.

In the wilds of Kûniüri, Achamian dreamed of the First Apocalypse, and the revelations
shook him. Anasûrimbor Nau-Cayûti was poisoned by his wife Iëva, who was jealous of
his love for Aulisi, the love that had compelled him to risk even the dread Ark. At her
insistence, Nau-Cayûti was buried rather than burned, but he was not dead. The poison
had merely given him the appearance of death. His still-breathing body was dug up by
Aurang and borne to the Incû-Holoinas. There, he was tormented and tortured by the
Consult, who demanded to know the location of the Heron Spear. He discovered that
Shaeönanra still lived thanks to a hideous contrivance, a device which bound several
still-living people together. Shaeönanra soul moved between the bodies as a way of
constantly avoiding death and thus prolonging his life for millennia. Nau-Cayûti was
subjected to every horror imaginable but did not break. He refused to disclose the
location of the Heron Spear, enduring two years or more of interrogation. Finally, he
99was forced to join a line of prisoners, weighed down by chains. They were slowly drawn
through the Ark and taken, one by one, inside a strange object: a sarcophagus with
eleven Chorae embedded in it.

The Carapace of the No-God. Awakening, Achamian was horrified at the revelation,
but could not yet grasp its full implications.

A representation of Ajokli, the Four-Horned God of Deceit.

In Momemn Esmenet had restored order and commanded the defence of the city,
defying several attempts to attack the walls. Kelmomas was more intrigued by the
White-Luck Warrior, seeing him stalk the halls and bring about the death of his sister
Theliopa, who had been the greatest threat to him. Kelmomas has been driven mad,
hearing the voice of his twin Sarmamas in his ear and believing that Ajokli, the evil
Four-Horned God, was now his protector. In an unguarded moment, Kelmomas was
caught celebrating his sister’s death by his horrified mother and fled.

A powerful earthquake struck Momemn, the gods again moving against the House of
Anasûrimbor in its moment of weakness. The Fanim prepared to attack, only for
Kellhus to translocate straight into their midst. He killed Fanayal and Nannaferi
100without hesitation, brought down Meppa in a sorcerous exchange and took Malowebi
as a prisoner. Malowebi attempted to invoke the Blue Lotus Treaty between Zeüm and
the Empire to ensure his safety, but the Aspect-Emperor was unimpressed. Using his
sword, he decapitated Malowebi and replaced his head with that of one of the
Decapitants, the demon-heads affixed to his hip. The possessing demon took on the
form of Malowebi as he was ordered by Kellhus to return to Domyot and kill the Grand
Satakhan. Malowebi’s head, still conscious and aware, was tied to his hip instead.

Kellhus then returned to the palace, telling Esmenet he had returned to rescue her. The
White-Luck Warrior struck, Kelmomas distracting his father at a crucial moment...

A fresh earthquake struck the city, the Andiamine Heights collapsing in on themselves
and everyone inside.

Thousands of miles to the north, Nersei Proyas regrouped the Ordeal, finding that only
a third of the force that had left the Empire now survived. With the Aspect-Emperor
missing, he commanded them to muster, to take as much sustenance as they could and
to cross the Sursa. The Golden Horns of Golgotterath were very close now.

Momemn fell. The city was destroyed, the waters of the Meneanor flooding the city
even as earthquakes wracked it. Kellhus, Esmenet and Kelmomas translocated through
the Metagnosis, saved from death at the last moment by Kellhus’s sorcery. Kellhus told
Esmenet that the Empire had served its purpose: it was a ladder he needed to reach
Golgotterath. Only the Great Ordeal matters now. He also discerned Kelmomas’s role
in the murders and destruction that had befallen the palace prior to the Fanim attack.
Esmenet was struck with horror by her son’s actions. Kellhus told his son he would
spare him to spare his mother’s heart. They resumed their journey back to the Ordeal.

Ishterebinth fell in to chaos. Sorweel, freed from the Amiolas, fled the mountain with
Serwa and Moënghus. Moënghus was filled with despair from his torture, but Serwa
seemed invigorated from the experience. Sorweel now knew the truth of the horror: he
had seen the halls of the Min-Uroikas, he had witnessed battlefields eight millennia
gone and had beheld the Whirlwind through ancient eyes: the No-God was real and
the Second Apocalypse was coming. This now wedded Sorweel to the Anasûrimbor
cause and he now believed fully in Kellhus...and his daughter. For her part, Serwa told
Sorweel from her Mandate memories that Seswatha had worn the Amiolas three times
and she recalled its power through her inherited knowledge. Astonished by the love
that Sorweel held for her, Serwa submitted to an un-Dûnyain impulse and took him as
her lover. During their flight north along the Demua, the trio were cornered by a
Scylvendi scouting party on the mountain known as Shaugiriol , “Eaglehorn,” and
Serwa translocated them across the Leash, but at the last moment Moënghus fell from
her grasp – or was pushed – and was left behind. Serwa warned Sorweel that Moënghus
had been broken by Ishterebinth and the greater cause was served by leaving him
behind rather than reuniting his broken remnant with the Ordeal.

The Great Ordeal crossed the Wair Chirsaul, the Mandible Ford, and marched into the
choking emptiness of Agongorea. At first the march was triumphant, the surviving
members of the Ordeal filled with confidence from their survival of the Scalding at
Dagliash. But soon despair – and Dolour – replaced the triumph. Their Aspect-
Emperor had left them, and they had left their food behind. Each Ordealman had
scavenged as much Sranc-flesh as they could find, but soon this neared exhaustion.
102Agongorea, the Field Appalling, was lifeless. Nothing lived there, not the meanest weed
or the smallest ant. The Ordeal risked starvation...until they saw the two golden threads
gradually taking shape on the horizon. Their destination was finally in sight.

To the south, Achamian and Mimara finally reached the Leash to find the straits
clogged with untold thousands of corpses, most of them Sranc, washed out of the
Neleöst by the Scalding. Achamian realised this meant that Kellhus had achieved a
great victory and was now marching on Golgotterath. Time grew short.

The Ordeal made the final crossing and descended into madness. Many of their horses
were eaten, and then men turned on men, first criminals and would-be deserters, and
then those who had been Scalded. To survive, the Ordeal had to feast on itself. Sorweel
and Serwa returned to find the army gripped in a fever of horror, one they had to
endure even as the Golden Horns grew taller on the horizon. The Ordeal breached the
Occlusion, the vast debris ring thrown up by Arkfall, and made camp before the Horns,
There, a semblance of normality returned to the host, but so did a sense of guilt for
what they had endured to come so far. Sorweel was horrified, his disgust for the Aspect-
Emperor returning. He gave himself up to the White Luck utterly.

Then, just as despair threatened to grip the Ordeal, Anasûrimbor Kellhus returned. He
found the Ordeal gripped by darkness so lit the way to sanity by claiming that Nersei
Proyas had betrayed them and led them to depravity on the orders of the Consult.
Proyas was struck down from his rank and imprisoned. Zsoronga of Zeüm was held to
blame for his nation’s betrayal and put to death. The Great Ordeal was given scapegoats
to blame its own madness upon, and thus was absolved of its sins. When Proyas
demanded to know why, Kellhus told him a horrific truth: that in order to stand
outside the perception of time and the Gods, the Consult must at some point win and
close the World to the Outside. Whether that happened now or millennia hence was
immaterial: at some point the Consult’s victory was inevitable. Against that, all
sacrifices were just.

Moënghus awoke to find himself a prisoner of Cnaiür urs Skiötha...of his father.
Cnaiür and the Scylvendi marched on Golgotterath and Moënghus was made to march
with them.

Achamian and Mimara joined the Ordeal as it arrayed for battle before the Golden
Horns. Learning of the fate of Proyas, Achamian begged Kellhus for mercy, falling to
his knees (as long ago foretold) to ask for that boon. But Kellhus refused. For her part,
Mimara tried to behold Kellhus with the Judging Eye, as she had long ago promised,
only to find that the Eye refused to open. When it finally did, outside of Kellhus’s
presence, it told her only that her mother Esmenet was truly holy, radiating with the
golden light of the undamned.

Before the final confrontation, Kellhus called his lords together for a benediction, the
Last Whelming, to prepare them for war. Sorweel came before Kellhus as had been
promised. A Chorae in his hand, the White Luck protecting him from Kellhus’s
Dûnyain sight, all Sorweel had to do was strike. But the White Luck did not protect
Sorweel from Kelmomas’s piercing gaze. Before he could strike down Kellhus, Sorweel
was stabbed and killed by Kelmomas. The threat was eliminated, but it could not be
seen. To Kellhus and the others, Kelmomas had murdered a true believer in the Aspect-
Emperor for no reason. Kelmomas was taken away in chains. His father counselled his
death, but his mother gave the child a file so he might free himself.

The battle came at last. Cet’ingira, who claimed to have witnessed each of the eight
thousand summers since Arkfall, bandied words with the Aspect-Emperor and then the
Anasûrimbor unleashed the first fruits of his long-ago alliance with the Daimyos. A
host of Ciphrang descended on the Ark, causing great destruction among its defenders
and triggering many of the magical traps set to destroy attackers. The Schools of the
Ordeal pelted the great walls and fortress redoubts with sorcery, and Chorae were used
to weaken the ensorcelled walls. Golgotterath was breached , the Ordeal penetrating the
walls even as the ancient First Ordeal had failed to do so.

But Golgotterath had reserves. A horde of Bashrag was unleashed from within, causing
great destruction in the ranks of the Ordeal. And now the darkest threat of all, a vast
shroud rising from the slopes of the Yimaleti Mountains: a second Sranc horde, equal
or greater to the one destroyed at Dagliash.

Kellhus visited death upon the second Horde but found its numbers so vast that his
attacks were negligible. The Ordeal’s only hope was to gain the mound of Golgotterath
and then hold the broken walls against the new threat. But a fresh attack came from an
unexpected quarter: a traitor-Nonman bearing the Sun Lance, sister-weapon to the
Heron Spear, an Inchoroi Spear-of-Light from the dawn of time. Many great sorcerers
were incinerated by the Lance until Kellhus confronted the Nonman and killed him,
taking the weapon for his own. He turned the Sun Lance not against the Horde, but
against the Canted Horn of Golgotterath itself.

The Canted Horn fell, two miles or more of metal, more ancient than could be
comprehended, which had borne the Ark through the Void itself. How many Sranc
died in the titanic collapse could not be fathomed, nor the number of men whose
hearing was destroyed by the cacophony, a sound unmatched by anything in the World
since Arkfall itself.

The Intrinsic Gate of Golgotterath, and its guardian.

But the battle was not done. The Horde had lost a vast portion of its number, but more
remained, and they now assailed the host of the Ordeal. The Scylvendi descended to
take the Ordeal’s camp, Moënghus putting an end to Proyas’s torment. Mimara, now
deep in the throes of childbirth, had to flee into the battlefield with Achamian and
Esmenet to find succour in the Ordeal’s lines. Skuthula the Black, Worm of Legend,
emerged to hold the Intrinsic Gate itself, the interface between the Ark and
Golgotterath, and there held it against all attackers.

Then Aurang took to the skies. Forced into battle as all hope for the Consult seemed to
fade, he confronted the Holy Aspect-Emperor and fell before him. The Inchoroi’s
corpse was thrown from the sky and left rotting in the chaos below. Spying the gate
through which Aurang had exited the Ark, high on the Upright (and now Only) Horn,
Kellhus entered the Ark and finally confronted his destiny.

106The battle continued. Serwa confronted Skuthula the Black in a battle which would
have stood for the ages, had it not been seen by so few. Serwa avoided a hail of Consult
Chorae bowmen and finally unleashed destruction on the Worm, only for one last
Chorae that had escaped her detection to lay her low. Her brother Kayûtas found her
body and bore it from the field, but it was unclear if she was dead or alive.

The first of Mimara and Achamian’s two children was born.

Inside the Ark, Kellhus found his way to the Golden Court, the heart of the Consult’s
power, and there confronted Cet’ingira and Aurax, brother to Aurang, now the last
surviving member of the Inchoroi species on this World. Cet’ingira told Kellhus that
the Ark had been built by a race of Progenitors who had achieved total technological
mastery and had grasped the Absolute through it, but in doing so had discovered the
threat of damnation that waited for everyone. The Ark was built and populated by their
Tekne creations – including the Inchoroi themselves – and sent forth into the Void,
destroying the population of every world they encountered, reducing the numbers of
each to 144,000 as they had come to believe was necessary to seal the worlds against the
Outside. But to no avail, until the Ark arrived, exhausted, on this World, a holy and
promised place.

Cet’ingira told Kellhus of the truth, that hell and damnation waited for everyone, and
that the only way to avoid this fate was for the Consult to win . Cet’ingira bade that
Kellhus stare into the Inverse Fire and be convinced of the truth...only for Kellhus to
be left unimpressed by it. Kellhus knew that the Inverse Fire showed the reality that
followed death and confirmed that all sentient beings, bar the few especially favoured
by the Gods, were doomed to torment, but it did not interest him. Even the growing
threat of hundreds of skin-spies, each bearing a Chorae, who had surrounded him
seemed of no interest. Cet’ingira, who had seen thousands swayed by the Fire, was left
baffled.

The Throne of Sil, in the Golden Court of the Ark of the Skies.

Kellhus now demanded that the true masters of the Consult show themselves and they
did so: five Dûnyain, the last survivors of Ishuäl. Taken prisoner during the Consult
attack a decade earlier, they had been taken back to Golgotterath for interrogation.
Inevitably, they had suborned it just as Kellhus had suborned the First Holy War.
Shaeönanra had objected and been destroyed. Even the Inchoroi had surrendered their
command of the Unholy Consult to the Dûnyain, realising that only they could
possibly stop Kellhus. Five Dûnyain to defeat one. Everything they had worked for now
led to this place, to Kellhus confronting them and then either surrendering to their
argument or being defeated. Either way, the only way out of the Golden Court lay
through the Carapace, now shorn of its protective Chorae as to admit a sorcerer.

The only way for Kellhus to leave was if he became the No-God, as his ancestor Nau-
Cayûti had before him.

Kellhus agreed this plan was sound, but it had not accounted for his own foresight in
that this could happen: that Dûnyain would survive Ishuäl, would return to
Golgotterath and conquer it. To defeat this eventuality, Kellhus therefore had to make
alliance with an even stronger power. And this he had done.

When he learned the art of the Daimyos and plumbed the hells, returning with the
Decapitants, he had also made alliance with Ajokli, Lord of Hate. A part of Ajokli now
rode in Kellhus, and through the Topos of Golgotterath, a wound in the fabric of the
World ever darker and more terrible than that of Cil-Aujas, Ajokli could now manifest.
And as he saw through Kellhus’s eyes, Ajokli could now comprehend (although at a
remove) the Consult, stepping outof the circle of ignorance that had blinded the Gods
to the threat posed by them.

Kellhus-and-Ajokli killed Cet’ingira and one of the Dûnyain before wresting control of
the skin-spies as a sign of his power. Kellhus’s interest was not in just stopping the
Consult, but in conquering hell itself . Kellhus would evade the threat of damnation by
destroying or enslaving the Gods himself. In return, Ajokli would have all the souls he
wanted to feast upon. The Dûnyain would act as their viceroys in this new world.

Kellhus would save the World by making of it a charnel house. But this was not to be.
Kelmomas appeared, having found his way into the Golden Court thanks to a skin-spy
infiltrator. Kellhus was so shocked to see his son where he was not expected that his
control slipped for at least a moment, the Ajokli aspect bewildered because he could
not perceive the child. This confusion lasted long enough for a skin-spy to strike
Anasûrimbor Kellhus with a Chorae. The Aspect-Emperor turned to salt, killed on the
instant. The Dûnyain seized Kelmomas and threw the son of Kellhus into the
Carapace.

The battle outside had ended, the remaining Upright Horn pulsing with power.
Kellhus apparently descended to greet his victorious troops, but it was an illusion
wrought of the Tekne. Mimara’s second child was stillborn in this moment and with
109the Judging Eye she beheld the truth: the shining Carapace floating down from on
high.

The host of the Ordeal fled, streaming from the mound of Golgotterath even as the
winds began to howl and the Whirlwind took shape once again. The Ordealmen,
reduced from a third of a million souls to a paltry few tens of thousands, were
surrounded by the Sranc Horde and destroyed utterly. Thousands of Chorae flew
through the air, gathered up in their tens of thousands from the detritus of
Golgotterath and cast out by the Whirlwind to strike the fleeing sorcerers, killing them
by the hundreds. The remnants of the Great Ordeal perished in smoke and salt.

Realising he had been cheated of his vengeance, Cnaiür gave himself over to Ajokli,
who was screaming in rage as Kellhus’s soul evaded him, and then to the Whirlwind
itself. He left behind a command that his son Moënghus would succeed him as King-of-
Tribes of the Scylvendi, to command them in the war to come.

Out of the darkness a tiny band fled, flying high over the Sranc Horde in the opposite
direction to the rest of the host. The ancient Wizard, his wife, his son and his old lover
fled before the horror that had been unleashed by the Aspect-Emperor’s miscalculation.

The No-God had returned. The Second Apocalypse had begun.
